loc_to_unit = {
    {"Casket of Souls", "wh2_dlc09_tmb_art_casket_of_souls_0"},
    {"Screaming Skull Catapults", "wh2_dlc09_tmb_art_screaming_skull_catapult_0"},
    {"Hexwraiths", "wh2_dlc09_tmb_cav_hexwraiths"},
    {"Necropolis Knights", "wh2_dlc09_tmb_cav_necropolis_knights_0"},
    {"Necropolis Knights (Halberds)", "wh2_dlc09_tmb_cav_necropolis_knights_1"},
    {"Nehekhara Horsemen", "wh2_dlc09_tmb_cav_nehekhara_horsemen_0"},
    {"Skeleton Horsemen", "wh2_dlc09_tmb_cav_skeleton_horsemen_0"},
    {"Skeleton Horse Archers", "wh2_dlc09_tmb_cav_skeleton_horsemen_archers_0"},
    {"Crypt Ghouls", "wh2_dlc09_tmb_inf_crypt_ghouls"},
    {"Nehekhara Warriors", "wh2_dlc09_tmb_inf_nehekhara_warriors_0"},
    {"Skeleton Archers", "wh2_dlc09_tmb_inf_skeleton_archers_0"},
    {"Skeleton Spearmen", "wh2_dlc09_tmb_inf_skeleton_spearmen_0"},
    {"Skeleton Warriors", "wh2_dlc09_tmb_inf_skeleton_warriors_0"},
    {"Tomb Guard", "wh2_dlc09_tmb_inf_tomb_guard_0"},
    {"Tomb Guard (Halberds)", "wh2_dlc09_tmb_inf_tomb_guard_1"},
    {"Carrion", "wh2_dlc09_tmb_mon_carrion_0"},
    {"Dire Wolves", "wh2_dlc09_tmb_mon_dire_wolves"},
    {"Fell Bats", "wh2_dlc09_tmb_mon_fell_bats"},
    {"Hierotitan", "wh2_dlc09_tmb_mon_heirotitan_0"},
    {"Necrosphinx", "wh2_dlc09_tmb_mon_necrosphinx_0"},
    {"Sepulchral Stalkers", "wh2_dlc09_tmb_mon_sepulchral_stalkers_0"},
    {"Tomb Scorpion", "wh2_dlc09_tmb_mon_tomb_scorpion_0"},
    {"Ushabti", "wh2_dlc09_tmb_mon_ushabti_0"},
    {"Ushabti (Great Bow)", "wh2_dlc09_tmb_mon_ushabti_1"},
    {"Khemrian Warsphinx", "wh2_dlc09_tmb_veh_khemrian_warsphinx_0"},
    {"Skeleton Archer Chariots", "wh2_dlc09_tmb_veh_skeleton_archer_chariot_0"},
    {"Skeleton Chariots", "wh2_dlc09_tmb_veh_skeleton_chariot_0"},
    {"Doomfire Warlocks", "wh2_dlc10_def_cav_doomfire_warlocks_0"},
    {"Sisters of Slaughter", "wh2_dlc10_def_inf_sisters_of_slaughter"},
    {"Feral Manticore", "wh2_dlc10_def_mon_feral_manticore_0"},
    {"Kharibdyss", "wh2_dlc10_def_mon_kharibdyss_0"},
    {"Giant Slayers", "wh2_dlc10_dwf_inf_giant_slayers"},
    {"Dryads", "wh2_dlc10_hef_inf_dryads_0"},
    {"Shadow-walkers", "wh2_dlc10_hef_inf_shadow_walkers_0"},
    {"Shadow Warriors", "wh2_dlc10_hef_inf_shadow_warriors_0"},
    {"Sisters of Avelorn", "wh2_dlc10_hef_inf_sisters_of_avelorn_0"},
    {"Tree Kin", "wh2_dlc10_hef_mon_treekin_0"},
    {"Treeman", "wh2_dlc10_hef_mon_treeman_0"},
    {"Carronades", "wh2_dlc11_cst_art_carronade"},
    {"Mortars", "wh2_dlc11_cst_art_mortar"},
    {"Deck Droppers", "wh2_dlc11_cst_cav_deck_droppers_0"},
    {"Deck Droppers (Bombers)", "wh2_dlc11_cst_cav_deck_droppers_1"},
    {"Deck Droppers (Handguns)", "wh2_dlc11_cst_cav_deck_droppers_2"},
    {"Damned Knights Errant", "wh2_dlc11_cst_cav_knights_errant_0"},
    {"Damned Knights Errant", "wh2_dlc11_cst_cav_knights_errant_1"},
    {"Damned Knights Errant", "wh2_dlc11_cst_cav_knights_errant_2"},
    {"Damned Knights of the Realm", "wh2_dlc11_cst_cav_knights_of_the_realm"},
    {"Damned Questing Knights", "wh2_dlc11_cst_cav_questing_knights_0"},
    {"Deck Gunners", "wh2_dlc11_cst_inf_deck_gunners_0"},
    {"Depth Guard", "wh2_dlc11_cst_inf_depth_guard_0"},
    {"Depth Guard (Polearms)", "wh2_dlc11_cst_inf_depth_guard_1"},
    {"Sartosa Free Company", "wh2_dlc11_cst_inf_sartosa_free_company_0"},
    {"Sartosa Militia", "wh2_dlc11_cst_inf_sartosa_militia_0"},
    {"Syreens", "wh2_dlc11_cst_inf_syreens"},
    {"Zombie Pirate Deckhands Mob", "wh2_dlc11_cst_inf_zombie_deckhands_mob_0"},
    {"Zombie Pirate Deckhands Mob (Polearms)", "wh2_dlc11_cst_inf_zombie_deckhands_mob_1"},
    {"Zombie Pirate Gunnery Mob", "wh2_dlc11_cst_inf_zombie_gunnery_mob_0"},
    {"Zombie Pirate Gunnery Mob (Handguns)", "wh2_dlc11_cst_inf_zombie_gunnery_mob_1"},
    {"Zombie Pirate Gunnery Mob (Hand Cannons)", "wh2_dlc11_cst_inf_zombie_gunnery_mob_2"},
    {"Zombie Pirate Gunnery Mob (Bombers)", "wh2_dlc11_cst_inf_zombie_gunnery_mob_3"},
    {"Animated Hulks", "wh2_dlc11_cst_mon_animated_hulks_0"},
    {"Bloated Corpse", "wh2_dlc11_cst_mon_bloated_corpse_0"},
    {"Fell Bats", "wh2_dlc11_cst_mon_fell_bats"},
    {"Mournguls", "wh2_dlc11_cst_mon_mournguls_0"},
    {"Necrofex Colossus", "wh2_dlc11_cst_mon_necrofex_colossus_0"},
    {"Rotting Leviathan", "wh2_dlc11_cst_mon_rotting_leviathan_0"},
    {"Rotting Prometheans", "wh2_dlc11_cst_mon_rotting_prometheans_0"},
    {"Rotting Prometheans Gunnery Mob", "wh2_dlc11_cst_mon_rotting_prometheans_gunnery_mob_0"},
    {"Scurvy Dogs", "wh2_dlc11_cst_mon_scurvy_dogs"},
    {"Sylvanian Crossbowmen", "wh2_dlc11_vmp_inf_crossbowmen"},
    {"Sylvanian Handgunners", "wh2_dlc11_vmp_inf_handgunners"},
    {"Ripperdactyl Riders", "wh2_dlc12_lzd_cav_ripperdactyl_riders_0"},
    {"Red Crested Skinks", "wh2_dlc12_lzd_inf_skink_red_crested_0"},
    {"Ancient Salamander", "wh2_dlc12_lzd_mon_ancient_salamander_0"},
    {"Ancient Stegadon (Engine of the Gods)", "wh2_dlc12_lzd_mon_ancient_stegadon_1"},
    {"Bastiladon (Ark of Sotek)", "wh2_dlc12_lzd_mon_bastiladon_3"},
    {"Salamander Hunting Pack", "wh2_dlc12_lzd_mon_salamander_pack_0"},
    {"Ratling Guns", "wh2_dlc12_skv_inf_ratling_gun_0"},
    {"Warplock Jezzails", "wh2_dlc12_skv_inf_warplock_jezzails_0"},
    {"Doom-Flayers", "wh2_dlc12_skv_veh_doom_flayer_0"},
    {"Archers", "wh2_dlc13_emp_inf_archers_0"},
    {"Huntsmen", "wh2_dlc13_emp_inf_huntsmen_0"},
    {"War Wagons", "wh2_dlc13_emp_veh_war_wagon_0"},
    {"War Wagons (Mortars)", "wh2_dlc13_emp_veh_war_wagon_1"},
    {"Obsinite Gyrocopter", "wh2_dlc13_huntmarshall_veh_obsinite_gyrocopter_0"},
    {"Feral Dread Saurian", "wh2_dlc13_lzd_mon_dread_saurian_0"},
    {"Dread Saurian", "wh2_dlc13_lzd_mon_dread_saurian_1"},
    {"Razordon Hunting Pack", "wh2_dlc13_lzd_mon_razordon_pack_0"},
    {"Sacred Kroxigor", "wh2_dlc13_lzd_mon_sacred_kroxigors_0"},
    {"Scourgerunner Chariots", "wh2_dlc14_def_cav_scourgerunner_chariot_0"},
    {"Bloodwrack Medusa", "wh2_dlc14_def_mon_bloodwrack_medusa_0"},
    {"Bloodwrack Shrine", "wh2_dlc14_def_veh_bloodwrack_shrine_0"},
    {"Eshin Triads", "wh2_dlc14_skv_inf_eshin_triads_0"},
    {"Poisoned Wind Mortars", "wh2_dlc14_skv_inf_poison_wind_mortar_0"},
    {"Warp-Grinders", "wh2_dlc14_skv_inf_warp_grinder_0"},
    {"River Trolls", "wh2_dlc15_grn_mon_river_trolls_0"},
    {"Rogue Idol", "wh2_dlc15_grn_mon_rogue_idol_0"},
    {"Stone Trolls", "wh2_dlc15_grn_mon_stone_trolls_0"},
    {"Snotling Pump Wagons", "wh2_dlc15_grn_veh_snotling_pump_wagon_0"},
    {"Snotling Pump Wagons (Flappas)", "wh2_dlc15_grn_veh_snotling_pump_wagon_flappas_0"},
    {"Snotling Pump Wagons (Spiky Rollers)", "wh2_dlc15_grn_veh_snotling_pump_wagon_roller_0"},
    {"Athel Tamarha Faithbearers", "wh2_dlc15_hef_inf_mistwalkers_faithbearers_0"},
    {"Knights of Tor Gaval", "wh2_dlc15_hef_inf_mistwalkers_griffon_knights_0"},
    {"Sentinels of Astaril", "wh2_dlc15_hef_inf_mistwalkers_sentinels_0"},
    {"The Skyhawks", "wh2_dlc15_hef_inf_mistwalkers_skyhawks_0"},
    {"Spire Guard of Tor Yvresse", "wh2_dlc15_hef_inf_mistwalkers_spireguard_0"},
    {"Rangers", "wh2_dlc15_hef_inf_rangers_0"},
    {"Silverin Guard", "wh2_dlc15_hef_inf_silverin_guard_0"},
    {"Arcane Phoenix", "wh2_dlc15_hef_mon_arcane_phoenix_0"},
    {"Forest Dragon", "wh2_dlc15_hef_mon_forest_dragon_0"},
    {"War Lions of Chrace", "wh2_dlc15_hef_mon_war_lions_of_chrace_0"},
    {"Lion Chariots of Chrace", "wh2_dlc15_hef_veh_lion_chariot_of_chrace_0"},
    {"Mutant Rat Ogre", "wh2_dlc16_skv_mon_rat_ogre_mutant"},
    {"Wolf Rats", "wh2_dlc16_skv_mon_wolf_rats_0"},
    {"Wolf Rats (Poison)", "wh2_dlc16_skv_mon_wolf_rats_1"},
    {"Glade Riders (Spears)", "wh2_dlc16_wef_cav_glade_riders_2"},
    {"Great Stag Knights", "wh2_dlc16_wef_cav_great_stag_knights_0"},
    {"Bladesingers", "wh2_dlc16_wef_inf_bladesingers_0"},
    {"Malevolent Dryads", "wh2_dlc16_wef_inf_malicious_dryads_0"},
    {"Cave Bats", "wh2_dlc16_wef_mon_cave_bats"},
    {"Feral Manticore", "wh2_dlc16_wef_mon_feral_manticore"},
    {"Giant Spiders", "wh2_dlc16_wef_mon_giant_spiders_0"},
    {"Harpies", "wh2_dlc16_wef_mon_harpies_0"},
    {"Great Hawks", "wh2_dlc16_wef_mon_hawks_0"},
    {"Malevolent Tree Kin", "wh2_dlc16_wef_mon_malicious_treekin_0"},
    {"Malevolent Treeman", "wh2_dlc16_wef_mon_malicious_treeman_0"},
    {"Spider Hatchlings", "wh2_dlc16_wef_mon_spider_hatchlings_0"},
    {"Giant Wolves", "wh2_dlc16_wef_mon_wolves_0"},
    {"Zoats", "wh2_dlc16_wef_mon_zoats"},
    {"Tuskgor Chariots", "wh2_dlc17_bst_cav_tuskgor_chariot_0"},
    {"Ghorgon", "wh2_dlc17_bst_mon_ghorgon_0"},
    {"Jabberslythe", "wh2_dlc17_bst_mon_jabberslythe_0"},
    {"Prisoners", "wh2_dlc17_emp_inf_prisoners_0"},
    {"Chameleon Stalkers", "wh2_dlc17_lzd_inf_chameleon_stalkers_0"},
    {"Coatl", "wh2_dlc17_lzd_mon_coatl_0"},
    {"Feral Troglodon", "wh2_dlc17_lzd_mon_troglodon_0"},
    {"Reaper Bolt Throwers", "wh2_main_def_art_reaper_bolt_thrower"},
    {"Cold One Chariots", "wh2_main_def_cav_cold_one_chariot"},
    {"Cold One Knights", "wh2_main_def_cav_cold_one_knights_0"},
    {"Cold One Dread Knights", "wh2_main_def_cav_cold_one_knights_1"},
    {"Dark Riders", "wh2_main_def_cav_dark_riders_0"},
    {"Dark Riders (Shields)", "wh2_main_def_cav_dark_riders_1"},
    {"Dark Riders (Repeater Crossbow)", "wh2_main_def_cav_dark_riders_2"},
    {"Black Ark Corsairs", "wh2_main_def_inf_black_ark_corsairs_0"},
    {"Black Ark Corsairs (Handbows)", "wh2_main_def_inf_black_ark_corsairs_1"},
    {"Black Guard of Naggarond", "wh2_main_def_inf_black_guard_0"},
    {"Bleakswords", "wh2_main_def_inf_bleakswords_0"},
    {"Darkshards", "wh2_main_def_inf_darkshards_0"},
    {"Darkshards (Shields)", "wh2_main_def_inf_darkshards_1"},
    {"Dreadspears", "wh2_main_def_inf_dreadspears_0"},
    {"Har Ganeth Executioners", "wh2_main_def_inf_har_ganeth_executioners_0"},
    {"Harpies", "wh2_main_def_inf_harpies"},
    {"Shades", "wh2_main_def_inf_shades_0"},
    {"Shades (Dual Weapons)", "wh2_main_def_inf_shades_1"},
    {"Shades (Greatswords)", "wh2_main_def_inf_shades_2"},
    {"Witch Elves", "wh2_main_def_inf_witch_elves_0"},
    {"Black Dragon", "wh2_main_def_mon_black_dragon"},
    {"War Hydra", "wh2_main_def_mon_war_hydra"},
    {"Eagle Claw Bolt Throwers", "wh2_main_hef_art_eagle_claw_bolt_thrower"},
    {"Dragon Princes", "wh2_main_hef_cav_dragon_princes"},
    {"Ellyrian Reavers", "wh2_main_hef_cav_ellyrian_reavers_0"},
    {"Ellyrian Reaver Archers", "wh2_main_hef_cav_ellyrian_reavers_1"},
    {"Ithilmar Chariots", "wh2_main_hef_cav_ithilmar_chariot"},
    {"Silver Helms", "wh2_main_hef_cav_silver_helms_0"},
    {"Silver Helms (Shields)", "wh2_main_hef_cav_silver_helms_1"},
    {"Tiranoc Chariots", "wh2_main_hef_cav_tiranoc_chariot"},
    {"Archers", "wh2_main_hef_inf_archers_0"},
    {"Archers (Light Armour)", "wh2_main_hef_inf_archers_1"},
    {"Gate Guard", "wh2_main_hef_inf_gate_guard"},
    {"Lothern Sea Guard", "wh2_main_hef_inf_lothern_sea_guard_0"},
    {"Lothern Sea Guard (Shields)", "wh2_main_hef_inf_lothern_sea_guard_1"},
    {"Phoenix Guard", "wh2_main_hef_inf_phoenix_guard"},
    {"Spearmen", "wh2_main_hef_inf_spearmen_0"},
    {"Swordmasters of Hoeth", "wh2_main_hef_inf_swordmasters_of_hoeth_0"},
    {"White Lions of Chrace", "wh2_main_hef_inf_white_lions_of_chrace_0"},
    {"Great Eagle", "wh2_main_hef_mon_great_eagle"},
    {"Moon Dragon", "wh2_main_hef_mon_moon_dragon"},
    {"Flamespyre Phoenix", "wh2_main_hef_mon_phoenix_flamespyre"},
    {"Frostheart Phoenix", "wh2_main_hef_mon_phoenix_frostheart"},
    {"Star Dragon", "wh2_main_hef_mon_star_dragon"},
    {"Sun Dragon", "wh2_main_hef_mon_sun_dragon"},
    {"Cold One Spear-Riders", "wh2_main_lzd_cav_cold_one_spearmen_1"},
    {"Cold One Riders", "wh2_main_lzd_cav_cold_ones_1"},
    {"Feral Cold Ones", "wh2_main_lzd_cav_cold_ones_feral_0"},
    {"Horned Ones", "wh2_main_lzd_cav_horned_ones_0"},
    {"Terradon Riders", "wh2_main_lzd_cav_terradon_riders_0"},
    {"Terradon Riders (Fireleech Bolas)", "wh2_main_lzd_cav_terradon_riders_1"},
    {"Chameleon Skinks", "wh2_main_lzd_inf_chameleon_skinks_0"},
    {"Saurus Spears", "wh2_main_lzd_inf_saurus_spearmen_0"},
    {"Saurus Spears (Shields)", "wh2_main_lzd_inf_saurus_spearmen_1"},
    {"Saurus Warriors", "wh2_main_lzd_inf_saurus_warriors_0"},
    {"Saurus Warriors (Shields)", "wh2_main_lzd_inf_saurus_warriors_1"},
    {"Skink Cohort", "wh2_main_lzd_inf_skink_cohort_0"},
    {"Skink Cohort (Javelins)", "wh2_main_lzd_inf_skink_cohort_1"},
    {"Skink Skirmishers", "wh2_main_lzd_inf_skink_skirmishers_0"},
    {"Temple Guards", "wh2_main_lzd_inf_temple_guards"},
    {"Ancient Stegadon", "wh2_main_lzd_mon_ancient_stegadon"},
    {"Feral Bastiladon", "wh2_main_lzd_mon_bastiladon_0"},
    {"Bastiladon (Revivification Crystal)", "wh2_main_lzd_mon_bastiladon_1"},
    {"Bastiladon (Solar Engine)", "wh2_main_lzd_mon_bastiladon_2"},
    {"Feral Carnosaur", "wh2_main_lzd_mon_carnosaur_0"},
    {"Kroxigor", "wh2_main_lzd_mon_kroxigors"},
    {"Feral Stegadon", "wh2_main_lzd_mon_stegadon_0"},
    {"Stegadon", "wh2_main_lzd_mon_stegadon_1"},
    {"Plagueclaw Catapults", "wh2_main_skv_art_plagueclaw_catapult"},
    {"Warp Lightning Cannons", "wh2_main_skv_art_warp_lightning_cannon"},
    {"Clanrat Spears", "wh2_main_skv_inf_clanrat_spearmen_0"},
    {"Clanrat Spears (Shields)", "wh2_main_skv_inf_clanrat_spearmen_1"},
    {"Clanrats", "wh2_main_skv_inf_clanrats_0"},
    {"Clanrats (Shields)", "wh2_main_skv_inf_clanrats_1"},
    {"Death Globe Bombardiers", "wh2_main_skv_inf_death_globe_bombardiers"},
    {"Death Runners", "wh2_main_skv_inf_death_runners_0"},
    {"Gutter Runner Slingers", "wh2_main_skv_inf_gutter_runner_slingers_0"},
    {"Gutter Runner Slingers (Poison)", "wh2_main_skv_inf_gutter_runner_slingers_1"},
    {"Gutter Runners", "wh2_main_skv_inf_gutter_runners_0"},
    {"Gutter Runners (Poison)", "wh2_main_skv_inf_gutter_runners_1"},
    {"Night Runners", "wh2_main_skv_inf_night_runners_0"},
    {"Night Runners (Slings)", "wh2_main_skv_inf_night_runners_1"},
    {"Plague Monk Censer Bearers", "wh2_main_skv_inf_plague_monk_censer_bearer"},
    {"Plague Monks", "wh2_main_skv_inf_plague_monks"},
    {"Poisoned Wind Globadiers", "wh2_main_skv_inf_poison_wind_globadiers"},
    {"Skavenslave Slingers", "wh2_main_skv_inf_skavenslave_slingers_0"},
    {"Skavenslave Spears", "wh2_main_skv_inf_skavenslave_spearmen_0"},
    {"Skavenslaves", "wh2_main_skv_inf_skavenslaves_0"},
    {"Stormvermin (Halberds)", "wh2_main_skv_inf_stormvermin_0"},
    {"Stormvermin (Sword & Shield)", "wh2_main_skv_inf_stormvermin_1"},
    {"Warpfire Throwers", "wh2_main_skv_inf_warpfire_thrower"},
    {"Hell Pit Abomination", "wh2_main_skv_mon_hell_pit_abomination"},
    {"Rat Ogres", "wh2_main_skv_mon_rat_ogres"},
    {"Doomwheel", "wh2_main_skv_veh_doomwheel"},
    {"Bone Giant", "wh2_pro06_tmb_mon_bone_giant_0"},
    {"Feral Mammoth", "wh2_twa03_def_mon_war_mammoth_0"},
    {"Giant Wolves", "wh2_twa03_def_mon_wolves_0"},
    {"Feral Wyvern", "wh2_twa03_grn_mon_wyvern_0"},
    {"Chaos Chariots of Khorne", "wh3_dlc20_chs_cav_chaos_chariot_mkho"},
    {"Chaos Chariots of Nurgle", "wh3_dlc20_chs_cav_chaos_chariot_mnur"},
    {"Chaos Chariots of Slaanesh", "wh3_dlc20_chs_cav_chaos_chariot_msla"},
    {"Chaos Chariots of Tzeentch", "wh3_dlc20_chs_cav_chaos_chariot_mtze"},
    {"Chaos Knights of Khorne", "wh3_dlc20_chs_cav_chaos_knights_mkho"},
    {"Chaos Knights of Khorne (Lances)", "wh3_dlc20_chs_cav_chaos_knights_mkho_lances"},
    {"Chaos Knights of Nurgle", "wh3_dlc20_chs_cav_chaos_knights_mnur"},
    {"Chaos Knights of Nurgle (Lances)", "wh3_dlc20_chs_cav_chaos_knights_mnur_lances"},
    {"Chaos Knights of Slaanesh", "wh3_dlc20_chs_cav_chaos_knights_msla"},
    {"Chaos Knights of Slaanesh (Lances)", "wh3_dlc20_chs_cav_chaos_knights_msla_lances"},
    {"Chaos Knights of Tzeentch (Lances)", "wh3_dlc20_chs_cav_chaos_knights_mtze_lances"},
    {"Marauder Horsemen of Khorne (Throwing Axes)", "wh3_dlc20_chs_cav_marauder_horsemen_mkho_throwing_axes"},
    {"Marauder Horsemen of Nurgle (Throwing Axes)", "wh3_dlc20_chs_cav_marauder_horsemen_mnur_throwing_axes"},
    {"Marauder Horsemen of Slaanesh", "wh3_dlc20_chs_cav_marauder_horsemen_msla_javelins"},
    {"Marauder Horsemen of Tzeentch", "wh3_dlc20_chs_cav_marauder_horsemen_mtze_javelins"},
    {"Marauders of Khorne", "wh3_dlc20_chs_inf_chaos_marauders_mkho"},
    {"Marauders of Khorne (Dual Weapons)", "wh3_dlc20_chs_inf_chaos_marauders_mkho_dualweapons"},
    {"Marauders of Nurgle", "wh3_dlc20_chs_inf_chaos_marauders_mnur"},
    {"Marauders of Nurgle (Great Weapons)", "wh3_dlc20_chs_inf_chaos_marauders_mnur_greatweapons"},
    {"Marauders of Slaanesh", "wh3_dlc20_chs_inf_chaos_marauders_msla"},
    {"Marauders of Slaanesh (Hellscourges)", "wh3_dlc20_chs_inf_chaos_marauders_msla_hellscourges"},
    {"Marauders of Tzeentch", "wh3_dlc20_chs_inf_chaos_marauders_mtze"},
    {"Marauders of Tzeentch (Spears)", "wh3_dlc20_chs_inf_chaos_marauders_mtze_spears"},
    {"Chaos Warriors of Nurgle", "wh3_dlc20_chs_inf_chaos_warriors_mnur"},
    {"Chaos Warriors of Nurgle (Great Weapons)", "wh3_dlc20_chs_inf_chaos_warriors_mnur_greatweapons"},
    {"Chaos Warriors of Slaanesh", "wh3_dlc20_chs_inf_chaos_warriors_msla"},
    {"Chaos Warriors of Slaanesh (Hellscourges)", "wh3_dlc20_chs_inf_chaos_warriors_msla_hellscourges"},
    {"Chaos Warriors of Tzeentch", "wh3_dlc20_chs_inf_chaos_warriors_mtze"},
    {"Chaos Warriors of Tzeentch (Halberds)", "wh3_dlc20_chs_inf_chaos_warriors_mtze_halberds"},
    {"Chosen of Khorne", "wh3_dlc20_chs_inf_chosen_mkho"},
    {"Chosen of Khorne (Dual Weapons)", "wh3_dlc20_chs_inf_chosen_mkho_dualweapons"},
    {"Chosen of Nurgle", "wh3_dlc20_chs_inf_chosen_mnur"},
    {"Chosen of Nurgle (Great Weapons)", "wh3_dlc20_chs_inf_chosen_mnur_greatweapons"},
    {"Chosen of Slaanesh", "wh3_dlc20_chs_inf_chosen_msla"},
    {"Chosen of Slaanesh (Hellscourges)", "wh3_dlc20_chs_inf_chosen_msla_hellscourges"},
    {"Chosen of Tzeentch", "wh3_dlc20_chs_inf_chosen_mtze"},
    {"Chosen of Tzeentch (Halberds)", "wh3_dlc20_chs_inf_chosen_mtze_halberds"},
    {"Forsaken of Khorne", "wh3_dlc20_chs_inf_forsaken_mkho"},
    {"Forsaken of Slaanesh", "wh3_dlc20_chs_inf_forsaken_msla"},
    {"Chaos Warshrine", "wh3_dlc20_chs_mon_warshrine"},
    {"Chaos Warshrine of Khorne", "wh3_dlc20_chs_mon_warshrine_mkho"},
    {"Chaos Warshrine of Nurgle", "wh3_dlc20_chs_mon_warshrine_mnur"},
    {"Chaos Warshrine of Slaanesh", "wh3_dlc20_chs_mon_warshrine_msla"},
    {"Chaos Warshrine of Tzeentch", "wh3_dlc20_chs_mon_warshrine_mtze"},
    {"Bull Centaur Renders", "wh3_dlc23_chd_cav_bull_centaurs_axe"},
    {"Bull Centaur Renders (Dual Axes)", "wh3_dlc23_chd_cav_bull_centaurs_dual_axe"},
    {"Bull Centaur Renders (Great Weapons)", "wh3_dlc23_chd_cav_bull_centaurs_greatweapons"},
    {"Hobgoblin Wolf Raiders (Bows)", "wh3_dlc23_chd_cav_hobgoblin_wolf_raiders_bows"},
    {"Hobgoblin Wolf Raiders (Spears)", "wh3_dlc23_chd_cav_hobgoblin_wolf_raiders_spears"},
    {"Chaos Dwarf Blunderbusses", "wh3_dlc23_chd_inf_chaos_dwarf_blunderbusses"},
    {"Chaos Dwarf Warriors", "wh3_dlc23_chd_inf_chaos_dwarf_warriors"},
    {"Chaos Dwarf Warriors (Great Weapons)", "wh3_dlc23_chd_inf_chaos_dwarf_warriors_great_weapons"},
    {"Goblin Labourers", "wh3_dlc23_chd_inf_goblin_labourers"},
    {"Hobgoblin Archers", "wh3_dlc23_chd_inf_hobgoblin_archers"},
    {"Hobgoblin Cutthroats", "wh3_dlc23_chd_inf_hobgoblin_cutthroats"},
    {"Hobgoblin Sneaky Gits", "wh3_dlc23_chd_inf_hobgoblin_sneaky_gits"},
    {"Infernal Guard", "wh3_dlc23_chd_inf_infernal_guard"},
    {"Infernal Guard (Fireglaives)", "wh3_dlc23_chd_inf_infernal_guard_fireglaives"},
    {"Infernal Guard (Great Weapons)", "wh3_dlc23_chd_inf_infernal_guard_great_weapons"},
    {"Infernal Ironsworn", "wh3_dlc23_chd_inf_infernal_ironsworn"},
    {"Orc Labourers", "wh3_dlc23_chd_inf_orc_labourers"},
    {"Bale Taurus", "wh3_dlc23_chd_mon_bale_taurus"},
    {"Great Taurus", "wh3_dlc23_chd_mon_great_taurus"},
    {"K'daai Destroyer", "wh3_dlc23_chd_mon_kdaai_destroyer"},
    {"K'daai Fireborn", "wh3_dlc23_chd_mon_kdaai_fireborn"},
    {"Lammasu", "wh3_dlc23_chd_mon_lammasu"},
    {"Deathshrieker Rocket Launcher", "wh3_dlc23_chd_veh_deathshrieker_rocket_launcher"},
    {"Dreadquake Mortar", "wh3_dlc23_chd_veh_dreadquake_mortar"},
    {"Iron Daemon", "wh3_dlc23_chd_veh_iron_daemon"},
    {"Iron Daemon – Dreadquake Mortar", "wh3_dlc23_chd_veh_iron_daemon_1dreadquake"},
    {"Magma Cannon", "wh3_dlc23_chd_veh_magma_cannon"},
    {"Skullcracker", "wh3_dlc23_chd_veh_skullcracker"},
    {"Skullcracker – Dreadquake Mortar", "wh3_dlc23_chd_veh_skullcracker_1dreadquake"},
    {"Centigors of Tzeentch", "wh3_dlc24_bst_inf_centigors_great_weapons_mtze"},
    {"Tzaangors", "wh3_dlc24_bst_inf_tzaangors"},
    {"Incarnate Elemental of Beasts", "wh3_dlc24_bst_mon_incarnate_elemental_of_beasts"},
    {"Onyx Crowmen", "wh3_dlc24_cth_inf_onyx_crowmen"},
    {"Celestial Lion", "wh3_dlc24_cth_mon_celestial_lion"},
    {"Great Moon Bird", "wh3_dlc24_cth_mon_great_moon_bird"},
    {"Jade Lion", "wh3_dlc24_cth_mon_jade_lion"},
    {"Jet Lion", "wh3_dlc24_cth_mon_jet_lion"},
    {"Zhangu War Drum", "wh3_dlc24_cth_veh_zhangu_war_drum"},
    {"Akshina Ambushers", "wh3_dlc24_ksl_inf_akshina_ambushers"},
    {"Kislevite Warriors", "wh3_dlc24_ksl_inf_kislevite_warriors"},
    {"Frost Wyrm", "wh3_dlc24_ksl_mon_frost_wyrm"},
    {"Incarnate Elemental of Beasts", "wh3_dlc24_ksl_mon_incarnate_elemental_of_beasts"},
    {"The Things in the Woods", "wh3_dlc24_ksl_mon_the_things_in_the_woods"},
    {"Feral Carnosaur", "wh3_dlc24_lzd_mon_carnosaur_0"},
    {"Centigors of Tzeentch", "wh3_dlc24_tze_inf_centigors_great_weapons"},
    {"Tzaangors", "wh3_dlc24_tze_inf_tzaangors"},
    {"Cockatrice", "wh3_dlc24_tze_mon_cockatrice"},
    {"Changebringers", "wh3_dlc24_tze_mon_flamers_changebringers"},
    {"Mutalith Vortex Beast", "wh3_dlc24_tze_mon_mutalith_vortex_beast"},
    {"Hellcannon", "wh3_main_chs_art_hellcannon_prologue"},
    {"Fire Rain Rocket", "wh3_main_cth_art_fire_rain_rocket_battery_0"},
    {"Grand Cannon", "wh3_main_cth_art_grand_cannon_0"},
    {"Jade Lancers", "wh3_main_cth_cav_jade_lancers_0"},
    {"Great Longma Riders", "wh3_main_cth_cav_jade_longma_riders_0"},
    {"Peasant Horsemen", "wh3_main_cth_cav_peasant_horsemen_0"},
    {"Crane Gunners", "wh3_main_cth_inf_crane_gunners_0"},
    {"Celestial Dragon Guard", "wh3_main_cth_inf_dragon_guard_0"},
    {"Celestial Dragon Crossbows", "wh3_main_cth_inf_dragon_guard_crossbowmen_0"},
    {"Iron Hail Gunners", "wh3_main_cth_inf_iron_hail_gunners_0"},
    {"Jade Warrior Crossbowmen", "wh3_main_cth_inf_jade_warrior_crossbowmen_0"},
    {"Jade Warrior Crossbowmen (Shields)", "wh3_main_cth_inf_jade_warrior_crossbowmen_1"},
    {"Jade Warriors", "wh3_main_cth_inf_jade_warriors_0"},
    {"Jade Warriors (Halberds)", "wh3_main_cth_inf_jade_warriors_1"},
    {"Peasant Archers", "wh3_main_cth_inf_peasant_archers_0"},
    {"Peasant Long Spearmen", "wh3_main_cth_inf_peasant_spearmen_1"},
    {"Terracotta Sentinel", "wh3_main_cth_mon_terracotta_sentinel_0"},
    {"Sky-junk", "wh3_main_cth_veh_sky_junk_0"},
    {"Sky Lantern", "wh3_main_cth_veh_sky_lantern_0"},
    {"Wu Xing War Compass", "wh3_main_cth_veh_war_compass_0"},
    {"Chaos Furies", "wh3_main_dae_inf_chaos_furies_0"},
    {"Bloodcrushers of Khorne", "wh3_main_kho_cav_bloodcrushers_0"},
    {"Gorebeast Chariot of Khorne", "wh3_main_kho_cav_gorebeast_chariot"},
    {"Skullcrushers of Khorne", "wh3_main_kho_cav_skullcrushers_0"},
    {"Bloodletters of Khorne", "wh3_main_kho_inf_bloodletters_0"},
    {"Exalted Bloodletters of Khorne", "wh3_main_kho_inf_bloodletters_1"},
    {"Chaos Furies (Khorne)", "wh3_main_kho_inf_chaos_furies_0"},
    {"Chaos Warhounds of Khorne", "wh3_main_kho_inf_chaos_warhounds_0"},
    {"Chaos Warriors of Khorne", "wh3_main_kho_inf_chaos_warriors_0"},
    {"Chaos Warriors of Khorne (Halberds)", "wh3_main_kho_inf_chaos_warriors_1"},
    {"Chaos Warriors of Khorne (Dual Weapons)", "wh3_main_kho_inf_chaos_warriors_2"},
    {"Flesh Hounds of Khorne", "wh3_main_kho_inf_flesh_hounds_of_khorne_0"},
    {"Bloodthirster", "wh3_main_kho_mon_bloodthirster_0"},
    {"Minotaurs of Khorne", "wh3_main_kho_mon_khornataurs_0"},
    {"Minotaurs of Khorne (Great Weapons)", "wh3_main_kho_mon_khornataurs_1"},
    {"Soul Grinder (Khorne)", "wh3_main_kho_mon_soul_grinder_0"},
    {"Spawn of Khorne", "wh3_main_kho_mon_spawn_of_khorne_0"},
    {"Blood Shrine of Khorne", "wh3_main_kho_veh_blood_shrine_0"},
    {"Skullcannon", "wh3_main_kho_veh_skullcannon_0"},
    {"Gryphon Legion", "wh3_main_ksl_cav_gryphon_legion_0"},
    {"Horse Archers", "wh3_main_ksl_cav_horse_archers_0"},
    {"Kossovite Dervishes", "wh3_main_ksl_cav_horse_raiders_0"},
    {"War Bear Riders", "wh3_main_ksl_cav_war_bear_riders_1"},
    {"Winged Lancers", "wh3_main_ksl_cav_winged_lancers_0"},
    {"Armoured Kossars", "wh3_main_ksl_inf_armoured_kossars_0"},
    {"Armoured Kossars (Great Weapons)", "wh3_main_ksl_inf_armoured_kossars_1"},
    {"Ice Guard (Glaives)", "wh3_main_ksl_inf_ice_guard_0"},
    {"Ice Guard (Swords)", "wh3_main_ksl_inf_ice_guard_1"},
    {"Kossars", "wh3_main_ksl_inf_kossars_0"},
    {"Kossars (Spears)", "wh3_main_ksl_inf_kossars_1"},
    {"Kossars", "wh3_main_ksl_inf_kossars_tutorial_0"},
    {"Armoured Kossars (Spears)", "wh3_main_ksl_inf_kossars_tutorial_1"},
    {"Streltsi", "wh3_main_ksl_inf_streltsi_0"},
    {"Tzar Guard", "wh3_main_ksl_inf_tzar_guard_0"},
    {"Tzar Guard (Great Weapons)", "wh3_main_ksl_inf_tzar_guard_1"},
    {"Elemental Bear", "wh3_main_ksl_mon_elemental_bear_0"},
    {"Snow Leopard", "wh3_main_ksl_mon_snow_leopard_0"},
    {"Heavy War Sleds", "wh3_main_ksl_veh_heavy_war_sled_0"},
    {"Light War Sleds", "wh3_main_ksl_veh_light_war_sled_0"},
    {"Little Grom", "wh3_main_ksl_veh_little_grom_0"},
    {"Feral Bears", "wh3_main_monster_feral_bears"},
    {"Feral Ice Bears", "wh3_main_monster_feral_ice_bears"},
    {"Plague Drones of Nurgle", "wh3_main_nur_cav_plague_drones_0"},
    {"Plague Drones of Nurgle (Death's Heads)", "wh3_main_nur_cav_plague_drones_1"},
    {"Pox Riders of Nurgle", "wh3_main_nur_cav_pox_riders_of_nurgle_0"},
    {"Chaos Furies (Nurgle)", "wh3_main_nur_inf_chaos_furies_0"},
    {"Forsaken of Nurgle", "wh3_main_nur_inf_forsaken_0"},
    {"Forsaken of Nurgle", "wh3_main_nur_inf_forsaken_0_warriors"},
    {"Nurglings", "wh3_main_nur_inf_nurglings_0"},
    {"Plaguebearers of Nurgle", "wh3_main_nur_inf_plaguebearers_0"},
    {"Exalted Plaguebearers of Nurgle", "wh3_main_nur_inf_plaguebearers_1"},
    {"Beast of Nurgle", "wh3_main_nur_mon_beast_of_nurgle_0"},
    {"Great Unclean One", "wh3_main_nur_mon_great_unclean_one_0"},
    {"Plague Toads of Nurgle", "wh3_main_nur_mon_plague_toads_0"},
    {"Rot Flies", "wh3_main_nur_mon_rot_flies_0"},
    {"Soul Grinder (Nurgle)", "wh3_main_nur_mon_soul_grinder_0"},
    {"Spawn of Nurgle", "wh3_main_nur_mon_spawn_of_nurgle_0"},
    {"Spawn of Nurgle", "wh3_main_nur_mon_spawn_of_nurgle_0_warriors"},
    {"Crushers (Ironfist)", "wh3_main_ogr_cav_crushers_0"},
    {"Crushers (Great Weapons)", "wh3_main_ogr_cav_crushers_1"},
    {"Mournfang Cavalry", "wh3_main_ogr_cav_mournfang_cavalry_0"},
    {"Mournfang Cavalry (Ironfists)", "wh3_main_ogr_cav_mournfang_cavalry_1"},
    {"Mournfang Cavalry (Great Weapons)", "wh3_main_ogr_cav_mournfang_cavalry_2"},
    {"Gnoblars", "wh3_main_ogr_inf_gnoblars_0"},
    {"Gnoblar Trappers", "wh3_main_ogr_inf_gnoblars_1"},
    {"Ironguts", "wh3_main_ogr_inf_ironguts_0"},
    {"Leadbelchers", "wh3_main_ogr_inf_leadbelchers_0"},
    {"Maneaters", "wh3_main_ogr_inf_maneaters_0"},
    {"Maneaters (Ironfists)", "wh3_main_ogr_inf_maneaters_1"},
    {"Maneaters (Great Weapons)", "wh3_main_ogr_inf_maneaters_2"},
    {"Maneaters (Ogre Pistol)", "wh3_main_ogr_inf_maneaters_3"},
    {"Ogre Bulls", "wh3_main_ogr_inf_ogres_0"},
    {"Ogre Bulls (Dual Weapons)", "wh3_main_ogr_inf_ogres_1"},
    {"Ogre Bulls (Ironfists)", "wh3_main_ogr_inf_ogres_2"},
    {"Giant", "wh3_main_ogr_mon_giant_0"},
    {"Gorgers", "wh3_main_ogr_mon_gorgers_0"},
    {"Sabretusk Pack", "wh3_main_ogr_mon_sabretusk_pack_0"},
    {"Stonehorn", "wh3_main_ogr_mon_stonehorn_0"},
    {"Stonehorn (Harpoon Launcher)", "wh3_main_ogr_mon_stonehorn_1"},
    {"Gnoblar Scraplauncher", "wh3_main_ogr_veh_gnoblar_scraplauncher_0"},
    {"Ironblaster", "wh3_main_ogr_veh_ironblaster_0"},
    {"Heartseekers of Slaanesh", "wh3_main_sla_cav_heartseekers_of_slaanesh_0"},
    {"Hellstriders of Slaanesh", "wh3_main_sla_cav_hellstriders_0"},
    {"Hellstriders of Slaanesh (Hellscourges)", "wh3_main_sla_cav_hellstriders_1"},
    {"Seekers of Slaanesh", "wh3_main_sla_cav_seekers_of_slaanesh_0"},
    {"Chaos Furies (Slaanesh)", "wh3_main_sla_inf_chaos_furies_0"},
    {"Daemonettes of Slaanesh", "wh3_main_sla_inf_daemonette_0"},
    {"Exalted Daemonettes of Slaanesh", "wh3_main_sla_inf_daemonette_1"},
    {"Devoted Marauders of Slaanesh", "wh3_main_sla_inf_marauders_0"},
    {"Devoted Marauders of Slaanesh (Spears)", "wh3_main_sla_inf_marauders_1"},
    {"Devoted Marauders of Slaanesh (Hellscourges)", "wh3_main_sla_inf_marauders_2"},
    {"Fiends of Slaanesh", "wh3_main_sla_mon_fiends_of_slaanesh_0"},
    {"Keeper of Secrets", "wh3_main_sla_mon_keeper_of_secrets_0"},
    {"Soul Grinder (Slaanesh)", "wh3_main_sla_mon_soul_grinder_0"},
    {"Spawn of Slaanesh", "wh3_main_sla_mon_spawn_of_slaanesh_0"},
    {"Exalted Seeker Chariot", "wh3_main_sla_veh_exalted_seeker_chariot_0"},
    {"Hellflayers", "wh3_main_sla_veh_hellflayer_0"},
    {"Seeker Chariots", "wh3_main_sla_veh_seeker_chariot_0"},
    {"Chaos Knights of Tzeentch", "wh3_main_tze_cav_chaos_knights_0"},
    {"Doom Knights of Tzeentch", "wh3_main_tze_cav_doom_knights_0"},
    {"Chaos Furies (Tzeentch)", "wh3_main_tze_inf_chaos_furies_0"},
    {"Forsaken of Tzeentch", "wh3_main_tze_inf_forsaken_0"},
    {"Exalted Flamer of Tzeentch", "wh3_main_tze_mon_exalted_flamers_0"},
    {"Flamers of Tzeentch", "wh3_main_tze_mon_flamers_0"},
    {"Lord of Change", "wh3_main_tze_mon_lord_of_change_0"},
    {"Screamers of Tzeentch", "wh3_main_tze_mon_screamers_0"},
    {"Soul Grinder (Tzeentch)", "wh3_main_tze_mon_soul_grinder_0"},
    {"Spawn of Tzeentch", "wh3_main_tze_mon_spawn_of_tzeentch_0"},
    {"Burning Chariot of Tzeentch", "wh3_main_tze_veh_burning_chariot_0"},
    {"Gorebeast Chariots", "wh_dlc01_chs_cav_gorebeast_chariot"},
    {"Chaos Warriors (Great Weapons)", "wh_dlc01_chs_inf_chaos_warriors_2"},
    {"Chosen (Halberds)", "wh_dlc01_chs_inf_chosen_2"},
    {"Forsaken", "wh_dlc01_chs_inf_forsaken_0"},
    {"Dragon Ogres", "wh_dlc01_chs_mon_dragon_ogre"},
    {"Dragon Ogre Shaggoth", "wh_dlc01_chs_mon_dragon_ogre_shaggoth"},
    {"Chaos Trolls (Armoured)", "wh_dlc01_chs_mon_trolls_1"},
    {"Blood Knights", "wh_dlc02_vmp_cav_blood_knights_0"},
    {"Razorgor Chariots", "wh_dlc03_bst_cav_razorgor_chariot_0"},
    {"Feral Manticore", "wh_dlc03_bst_feral_manticore"},
    {"Bestigor Herd", "wh_dlc03_bst_inf_bestigor_herd_0"},
    {"Centigors", "wh_dlc03_bst_inf_centigors_0"},
    {"Centigors (Throwing Axes)", "wh_dlc03_bst_inf_centigors_1"},
    {"Centigors (Great Weapons)", "wh_dlc03_bst_inf_centigors_2"},
    {"Chaos Warhounds", "wh_dlc03_bst_inf_chaos_warhounds_0"},
    {"Chaos Warhounds (Poison)", "wh_dlc03_bst_inf_chaos_warhounds_1"},
    {"Cygor", "wh_dlc03_bst_inf_cygor_0"},
    {"Gor Herd", "wh_dlc03_bst_inf_gor_herd_0"},
    {"Gor Herd (Shields)", "wh_dlc03_bst_inf_gor_herd_1"},
    {"Minotaurs", "wh_dlc03_bst_inf_minotaurs_0"},
    {"Minotaurs (Shields)", "wh_dlc03_bst_inf_minotaurs_1"},
    {"Minotaurs (Great Weapons)", "wh_dlc03_bst_inf_minotaurs_2"},
    {"Razorgor Herd", "wh_dlc03_bst_inf_razorgor_herd_0"},
    {"Ungor Herd", "wh_dlc03_bst_inf_ungor_herd_1"},
    {"Ungor Raiders", "wh_dlc03_bst_inf_ungor_raiders_0"},
    {"Ungor Spearmen Herd", "wh_dlc03_bst_inf_ungor_spearmen_0"},
    {"Ungor Spearmen Herd (Shields)", "wh_dlc03_bst_inf_ungor_spearmen_1"},
    {"Chaos Spawn", "wh_dlc03_bst_mon_chaos_spawn_0"},
    {"Giant", "wh_dlc03_bst_mon_giant_0"},
    {"Knights of the Blazing Sun", "wh_dlc04_emp_cav_knights_blazing_sun_0"},
    {"Flagellants", "wh_dlc04_emp_inf_flagellants_0"},
    {"Free Company Militia", "wh_dlc04_emp_inf_free_company_militia_0"},
    {"Corpse Cart", "wh_dlc04_vmp_veh_corpse_cart_0"},
    {"Corpse Cart (Balefire)", "wh_dlc04_vmp_veh_corpse_cart_1"},
    {"Corpse Cart (Unholy Lodestone)", "wh_dlc04_vmp_veh_corpse_cart_2"},
    {"Mortis Engine", "wh_dlc04_vmp_veh_mortis_engine_0"},
    {"Harpies", "wh_dlc05_bst_mon_harpies_0"},
    {"Glade Riders", "wh_dlc05_wef_cav_glade_riders_0"},
    {"Glade Riders (Hagbane Tips)", "wh_dlc05_wef_cav_glade_riders_1"},
    {"Hawk Riders", "wh_dlc05_wef_cav_hawk_riders_0"},
    {"Sisters of the Thorn", "wh_dlc05_wef_cav_sisters_thorn_0"},
    {"Wild Riders", "wh_dlc05_wef_cav_wild_riders_0"},
    {"Wild Riders (Shields)", "wh_dlc05_wef_cav_wild_riders_1"},
    {"Forest Dragon", "wh_dlc05_wef_forest_dragon_0"},
    {"Deepwood Scouts", "wh_dlc05_wef_inf_deepwood_scouts_0"},
    {"Deepwood Scouts (Swiftshiver Shards)", "wh_dlc05_wef_inf_deepwood_scouts_1"},
    {"Dryads", "wh_dlc05_wef_inf_dryads_0"},
    {"Eternal Guard", "wh_dlc05_wef_inf_eternal_guard_0"},
    {"Eternal Guard (Shields)", "wh_dlc05_wef_inf_eternal_guard_1"},
    {"Glade Guard", "wh_dlc05_wef_inf_glade_guard_0"},
    {"Glade Guard (Starfire Shafts)", "wh_dlc05_wef_inf_glade_guard_1"},
    {"Glade Guard (Hagbane Tips)", "wh_dlc05_wef_inf_glade_guard_2"},
    {"Wardancers", "wh_dlc05_wef_inf_wardancers_0"},
    {"Wardancers (Asrai Spears)", "wh_dlc05_wef_inf_wardancers_1"},
    {"Waywatchers", "wh_dlc05_wef_inf_waywatchers_0"},
    {"Wildwood Rangers", "wh_dlc05_wef_inf_wildwood_rangers_0"},
    {"Great Eagle", "wh_dlc05_wef_mon_great_eagle_0"},
    {"Tree Kin", "wh_dlc05_wef_mon_treekin_0"},
    {"Treeman", "wh_dlc05_wef_mon_treeman_0"},
    {"Marauder Horsemasters", "wh_dlc06_chs_cav_marauder_horsemasters_0"},
    {"Chaos Feral Manticore", "wh_dlc06_chs_feral_manticore"},
    {"Aspiring Champions", "wh_dlc06_chs_inf_aspiring_champions_0"},
    {"Bolt Throwers", "wh_dlc06_dwf_art_bolt_thrower_0"},
    {"Bugman's Rangers", "wh_dlc06_dwf_inf_bugmans_rangers_0"},
    {"Rangers", "wh_dlc06_dwf_inf_rangers_0"},
    {"Rangers (Great Weapons)", "wh_dlc06_dwf_inf_rangers_1"},
    {"Night Goblin Squig Hoppers", "wh_dlc06_grn_cav_squig_hoppers_0"},
    {"Nasty Skulkers", "wh_dlc06_grn_inf_nasty_skulkers_0"},
    {"Soopa-Squig!", "wh_dlc06_grn_inf_squig_explosive_0"},
    {"Squig Herd", "wh_dlc06_grn_inf_squig_herd_0"},
    {"Spider Hatchlings", "wh_dlc06_grn_mon_spider_hatchlings_0"},
    {"Grail Guardians", "wh_dlc07_brt_cav_grail_guardians_0"},
    {"Knights Errant", "wh_dlc07_brt_cav_knights_errant_0"},
    {"Questing Knights", "wh_dlc07_brt_cav_questing_knights_0"},
    {"Royal Hippogryph Knights", "wh_dlc07_brt_cav_royal_hippogryph_knights_0"},
    {"Royal Pegasus Knights", "wh_dlc07_brt_cav_royal_pegasus_knights_0"},
    {"Battle Pilgrims", "wh_dlc07_brt_inf_battle_pilgrims_0"},
    {"Foot Squires", "wh_dlc07_brt_inf_foot_squires_0"},
    {"Grail Reliquae", "wh_dlc07_brt_inf_grail_reliquae_0"},
    {"Men-at-Arms", "wh_dlc07_brt_inf_men_at_arms_1"},
    {"Men-at-Arms (Shields)", "wh_dlc07_brt_inf_men_at_arms_2"},
    {"Peasant Bowmen (Fire Arrows)", "wh_dlc07_brt_inf_peasant_bowmen_1"},
    {"Peasant Bowmen (Pox Arrows)", "wh_dlc07_brt_inf_peasant_bowmen_2"},
    {"Spearmen-at-Arms", "wh_dlc07_brt_inf_spearmen_at_arms_1"},
    {"Peasant Mob", "wh_dlc07_brt_peasant_mob_0"},
    {"Marauder Horsemasters", "wh_dlc08_nor_cav_marauder_horsemasters_0"},
    {"Feral Manticore", "wh_dlc08_nor_feral_manticore"},
    {"Marauder Berserkers", "wh_dlc08_nor_inf_marauder_berserkers_0"},
    {"Marauder Champions", "wh_dlc08_nor_inf_marauder_champions_0"},
    {"Marauder Champions (Great Weapons)", "wh_dlc08_nor_inf_marauder_champions_1"},
    {"Marauder Hunters", "wh_dlc08_nor_inf_marauder_hunters_0"},
    {"Marauder Hunters (Javelins)", "wh_dlc08_nor_inf_marauder_hunters_1"},
    {"Marauder Spearmen", "wh_dlc08_nor_inf_marauder_spearman_0"},
    {"Fimir Warriors", "wh_dlc08_nor_mon_fimir_0"},
    {"Fimir Warriors (Great Weapons)", "wh_dlc08_nor_mon_fimir_1"},
    {"Chaos Frost Dragon", "wh_dlc08_nor_mon_frost_wyrm_0"},
    {"Norscan Giant", "wh_dlc08_nor_mon_norscan_giant_0"},
    {"Norscan Ice Trolls", "wh_dlc08_nor_mon_norscan_ice_trolls_0"},
    {"Skin Wolves", "wh_dlc08_nor_mon_skinwolves_0"},
    {"Skin Wolves (Armoured)", "wh_dlc08_nor_mon_skinwolves_1"},
    {"Feral Mammoth", "wh_dlc08_nor_mon_war_mammoth_0"},
    {"War Mammoth", "wh_dlc08_nor_mon_war_mammoth_1"},
    {"War Mammoth (Warshrine)", "wh_dlc08_nor_mon_war_mammoth_2"},
    {"Norscan Ice Wolves", "wh_dlc08_nor_mon_warwolves_0"},
    {"Marauder Ice Wolves Chariots", "wh_dlc08_nor_veh_marauder_warwolves_chariot_0"},
    {"Field Trebuchets", "wh_main_brt_art_field_trebuchet"},
    {"Grail Knights", "wh_main_brt_cav_grail_knights"},
    {"Knights of the Realm", "wh_main_brt_cav_knights_of_the_realm"},
    {"Mounted Yeomen", "wh_main_brt_cav_mounted_yeomen_0"},
    {"Mounted Yeomen Archers", "wh_main_brt_cav_mounted_yeomen_1"},
    {"Pegasus Knights", "wh_main_brt_cav_pegasus_knights"},
    {"Men-at-Arms (Polearm)", "wh_main_brt_inf_men_at_arms"},
    {"Peasant Bowmen", "wh_main_brt_inf_peasant_bowmen"},
    {"Spearmen-at-Arms (Shields)", "wh_main_brt_inf_spearmen_at_arms"},
    {"Hellcannon", "wh_main_chs_art_hellcannon"},
    {"Chaos Chariots", "wh_main_chs_cav_chaos_chariot"},
    {"Chaos Knights", "wh_main_chs_cav_chaos_knights_0"},
    {"Chaos Knights (Lances)", "wh_main_chs_cav_chaos_knights_1"},
    {"Marauder Horsemen", "wh_main_chs_cav_marauder_horsemen_0"},
    {"Marauder Horsemen (Throwing Axes)", "wh_main_chs_cav_marauder_horsemen_1"},
    {"Marauders", "wh_main_chs_inf_chaos_marauders_0"},
    {"Marauders (Great Weapons)", "wh_main_chs_inf_chaos_marauders_1"},
    {"Chaos Warriors", "wh_main_chs_inf_chaos_warriors_0"},
    {"Chaos Warriors (Halberds)", "wh_main_chs_inf_chaos_warriors_1"},
    {"Chosen", "wh_main_chs_inf_chosen_0"},
    {"Chosen (Great Weapons)", "wh_main_chs_inf_chosen_1"},
    {"Chaos Spawn", "wh_main_chs_mon_chaos_spawn"},
    {"Chaos Warhounds", "wh_main_chs_mon_chaos_warhounds_0"},
    {"Chaos Warhounds (Poison)", "wh_main_chs_mon_chaos_warhounds_1"},
    {"Chaos Giant", "wh_main_chs_mon_giant"},
    {"Chaos Trolls", "wh_main_chs_mon_trolls"},
    {"Cannons", "wh_main_dwf_art_cannon"},
    {"Flame Cannons", "wh_main_dwf_art_flame_cannon"},
    {"Grudge Throwers", "wh_main_dwf_art_grudge_thrower"},
    {"Organ Guns", "wh_main_dwf_art_organ_gun"},
    {"Dwarf Warriors", "wh_main_dwf_inf_dwarf_warrior_0"},
    {"Dwarf Warriors (Great Weapons)", "wh_main_dwf_inf_dwarf_warrior_1"},
    {"Hammerers", "wh_main_dwf_inf_hammerers"},
    {"Ironbreakers", "wh_main_dwf_inf_ironbreakers"},
    {"Irondrakes", "wh_main_dwf_inf_irondrakes_0"},
    {"Irondrakes (Trollhammer Torpedo)", "wh_main_dwf_inf_irondrakes_2"},
    {"Longbeards", "wh_main_dwf_inf_longbeards"},
    {"Longbeards (Great Weapons)", "wh_main_dwf_inf_longbeards_1"},
    {"Miners", "wh_main_dwf_inf_miners_0"},
    {"Miners (Blasting Charges)", "wh_main_dwf_inf_miners_1"},
    {"Quarrellers", "wh_main_dwf_inf_quarrellers_0"},
    {"Quarrellers (Great Weapons)", "wh_main_dwf_inf_quarrellers_1"},
    {"Slayers", "wh_main_dwf_inf_slayers"},
    {"Thunderers", "wh_main_dwf_inf_thunderers_0"},
    {"Gyrobomber", "wh_main_dwf_veh_gyrobomber"},
    {"Gyrocopter", "wh_main_dwf_veh_gyrocopter_0"},
    {"Gyrocopter (Brimstone Gun)", "wh_main_dwf_veh_gyrocopter_1"},
    {"Great Cannons", "wh_main_emp_art_great_cannon"},
    {"Helblaster Volley Guns", "wh_main_emp_art_helblaster_volley_gun"},
    {"Helstorm Rocket Battery", "wh_main_emp_art_helstorm_rocket_battery"},
    {"Mortars", "wh_main_emp_art_mortar"},
    {"Demigryph Knights", "wh_main_emp_cav_demigryph_knights_0"},
    {"Demigryph Knights (Halberds)", "wh_main_emp_cav_demigryph_knights_1"},
    {"Empire Knights", "wh_main_emp_cav_empire_knights"},
    {"Outriders", "wh_main_emp_cav_outriders_0"},
    {"Outriders (Grenade Launcher)", "wh_main_emp_cav_outriders_1"},
    {"Pistoliers", "wh_main_emp_cav_pistoliers_1"},
    {"Reiksguard", "wh_main_emp_cav_reiksguard"},
    {"Crossbowmen", "wh_main_emp_inf_crossbowmen"},
    {"Greatswords", "wh_main_emp_inf_greatswords"},
    {"Halberdiers", "wh_main_emp_inf_halberdiers"},
    {"Handgunners", "wh_main_emp_inf_handgunners"},
    {"Spearmen", "wh_main_emp_inf_spearmen_0"},
    {"Spearmen (Shields)", "wh_main_emp_inf_spearmen_1"},
    {"Swordsmen", "wh_main_emp_inf_swordsmen"},
    {"Luminark of Hysh", "wh_main_emp_veh_luminark_of_hysh_0"},
    {"Steam Tank", "wh_main_emp_veh_steam_tank"},
    {"Doom Diver Catapults", "wh_main_grn_art_doom_diver_catapult"},
    {"Goblin Rock Lobbers", "wh_main_grn_art_goblin_rock_lobber"},
    {"Forest Goblin Spider Riders", "wh_main_grn_cav_forest_goblin_spider_riders_0"},
    {"Forest Goblin Spider Rider Archers", "wh_main_grn_cav_forest_goblin_spider_riders_1"},
    {"Goblin Wolf Chariots", "wh_main_grn_cav_goblin_wolf_chariot"},
    {"Goblin Wolf Riders", "wh_main_grn_cav_goblin_wolf_riders_0"},
    {"Goblin Wolf Rider Archers", "wh_main_grn_cav_goblin_wolf_riders_1"},
    {"Orc Boar Boy Big 'Uns", "wh_main_grn_cav_orc_boar_boy_big_uns"},
    {"Orc Boar Boyz", "wh_main_grn_cav_orc_boar_boyz"},
    {"Orc Boar Chariots", "wh_main_grn_cav_orc_boar_chariot"},
    {"Savage Orc Boar Boy Big 'Uns", "wh_main_grn_cav_savage_orc_boar_boy_big_uns"},
    {"Savage Orc Boar Boyz", "wh_main_grn_cav_savage_orc_boar_boyz"},
    {"Black Orcs", "wh_main_grn_inf_black_orcs"},
    {"Goblin Archers", "wh_main_grn_inf_goblin_archers"},
    {"Goblins", "wh_main_grn_inf_goblin_spearmen"},
    {"Night Goblin Archers", "wh_main_grn_inf_night_goblin_archers"},
    {"Night Goblins (Fanatics)", "wh_main_grn_inf_night_goblin_fanatics"},
    {"Night Goblin Archers (Fanatics)", "wh_main_grn_inf_night_goblin_fanatics_1"},
    {"Night Goblins", "wh_main_grn_inf_night_goblins"},
    {"Orc Arrer Boyz", "wh_main_grn_inf_orc_arrer_boyz"},
    {"Orc Big 'Uns", "wh_main_grn_inf_orc_big_uns"},
    {"Orc Boyz", "wh_main_grn_inf_orc_boyz"},
    {"Savage Orc Arrer Boyz", "wh_main_grn_inf_savage_orc_arrer_boyz"},
    {"Savage Orc Big 'Uns", "wh_main_grn_inf_savage_orc_big_uns"},
    {"Savage Orcs", "wh_main_grn_inf_savage_orcs"},
    {"Arachnarok Spider", "wh_main_grn_mon_arachnarok_spider_0"},
    {"Giant", "wh_main_grn_mon_giant"},
    {"Trolls", "wh_main_grn_mon_trolls"},
    {"Marauder Chariots", "wh_main_nor_cav_chaos_chariot"},
    {"Marauder Horsemen", "wh_main_nor_cav_marauder_horsemen_0"},
    {"Marauder Horsemen (Throwing Axes)", "wh_main_nor_cav_marauder_horsemen_1"},
    {"Marauders", "wh_main_nor_inf_chaos_marauders_0"},
    {"Marauders (Great Weapons)", "wh_main_nor_inf_chaos_marauders_1"},
    {"Norscan Trolls", "wh_main_nor_mon_chaos_trolls"},
    {"Norscan Warhounds", "wh_main_nor_mon_chaos_warhounds_0"},
    {"Norscan Warhounds (Poison)", "wh_main_nor_mon_chaos_warhounds_1"},
    {"Black Knights", "wh_main_vmp_cav_black_knights_0"},
    {"Black Knights (Lances & Barding)", "wh_main_vmp_cav_black_knights_3"},
    {"Hexwraiths", "wh_main_vmp_cav_hexwraiths"},
    {"Cairn Wraiths", "wh_main_vmp_inf_cairn_wraiths"},
    {"Crypt Ghouls", "wh_main_vmp_inf_crypt_ghouls"},
    {"Grave Guard", "wh_main_vmp_inf_grave_guard_0"},
    {"Grave Guard (Great Weapons)", "wh_main_vmp_inf_grave_guard_1"},
    {"Skeleton Warriors", "wh_main_vmp_inf_skeleton_warriors_0"},
    {"Skeleton Spearmen", "wh_main_vmp_inf_skeleton_warriors_1"},
    {"Zombies", "wh_main_vmp_inf_zombie"},
    {"Dire Wolves", "wh_main_vmp_mon_dire_wolves"},
    {"Fell Bats", "wh_main_vmp_mon_fell_bats"},
    {"Vargheists", "wh_main_vmp_mon_vargheists"},
    {"Varghulf", "wh_main_vmp_mon_varghulf"},
    {"Black Coach", "wh_main_vmp_veh_black_coach"}
}

loc_to_units = {}

for _, pair in pairs(loc_to_unit) do
    if not loc_to_units[pair[1]] then
        loc_to_units[pair[1]] = {pair[2]}
    else
        table.insert(loc_to_units[pair[1]], pair[2])
    end
end

for key, value in pairs(loc_to_units) do
    if #value > 1 then
        -- print(key)
        for _, unit in pairs(value) do
            print(unit)
        end
    end
end