units_to_faction = {
    {"shadow_melee", "wh2_main_hef_nagarythe"},
    {"chrace_cav", "wh2_main_hef_chrace"},
    {"reaver", "wh_dlc08_nor_norsca"},
    {"grim_rangers", "wh2_main_hef_yvresse"},
    {"picks", "wh_main_dwf_karak_kadrin"},
    {"imperial_zombie", "wh_main_vmp_vampire_counts"},
    {"hunting_dogs", "wh2_dlc13_emp_the_huntmarshals_expedition"},
    {"red_host", "wh2_dlc12_lzd_cult_of_sotek"},
    {"dead_squires", "wh2_dlc11_vmp_the_barrow_legion"},
    {"doomed_legion", "wh2_dlc11_vmp_the_barrow_legion"},
    {"unholy_pilgrims", "wh2_dlc11_vmp_the_barrow_legion"},
    {"brtzombie", "wh2_dlc11_vmp_the_barrow_legion"},
    {"ogre_dead", "wh2_dlc11_cst_vampire_coast"},
    {"ogre_dead", "wh2_dlc11_cst_noctilus"},
    {"ogre_dead", "wh2_dlc11_cst_the_drowned"},
    {"wh2_dlc11_cst_cav_knights_errant_0", "wh2_dlc11_cst_the_drowned"},
    {"damned_knights", "wh2_dlc11_cst_the_drowned"},
    {"brtzombieknight", "wh2_dlc11_vmp_the_barrow_legion"},
    {"sylvanian_levy", "wh_main_vmp_schwartzhafen"},
    {"imperial_zombie", "wh_main_vmp_schwartzhafen"},
    {"dead_squires", "wh_main_vmp_mousillon"},
    {"unholy_pilgrims", "wh_main_vmp_mousillon"},
    {"brtzombie", "wh_main_vmp_mousillon"},
    {"brtzombieknight", "wh_main_vmp_mousillon"},
    {"eshin_hand", "wh2_main_skv_clan_eshin"},
    {"w_boyz", "wh_main_grn_orcs_of_the_bloody_hand"},
    {"hand_eshin", "wh2_main_skv_clan_eshin"},
    {"slaanesh_marauders", "wh2_main_def_cult_of_pleasure"},
    {"wh3_main_sla_inf_daemonette_0", "wh2_main_def_cult_of_pleasure"},
    {"wh3_main_sla_inf_daemonette_1", "wh2_main_def_cult_of_pleasure"},
    {"slaanesh_warriors", "wh2_main_def_cult_of_pleasure"},
    {"skryre_rat", "wh2_main_skv_clan_skryre"},
    {"poxvermin", "wh2_main_skv_clan_pestilens"},
    {"fervid_fang", "wh2_main_skv_clan_pestilens"},
    {"crows_nest_zombie", "wh2_dlc11_cst_noctilus"},
    {"crows_nest_zombie", "wh2_dlc11_cst_the_drowned"},
    {"deck_clearers", "wh2_dlc11_cst_pirates_of_sartosa"},
    {"elf_pirates", "wh2_dlc11_cst_pirates_of_sartosa"},
    {"boarders", "wh2_dlc11_cst_pirates_of_sartosa"},
    {"wh2_twa05_ogr_inf_maneaters_sartosa", "wh2_dlc11_cst_pirates_of_sartosa"},
    {"crows_nest", "wh2_dlc11_cst_pirates_of_sartosa"},
    {"crows_nest_zombie", "wh2_dlc11_cst_vampire_coast"},
    {"creeping_dread", "wh2_dlc11_def_the_blessed_dread"},
    {"white_wolf", "wh_main_emp_middenland"},
    {"nordlander", "wh_main_emp_nordland"},
    {"engineers_imp", "wh_main_emp_empire"},
    {"templars", "wh_main_emp_middenland"},
    {"cold_riders", "wh2_main_def_hag_graef"},
    {"scholars", "wh2_main_hef_order_of_loremasters"},
    {"tyrant_blades", "wh2_main_def_hag_graef"},
    {"sotek_shield", "wh2_main_dwf_spine_of_sotek_dwarfs"},
    {"sotek_picks", "wh2_main_dwf_spine_of_sotek_dwarfs"},
    {"khaine_spears", "wh2_main_def_har_ganeth"},
    {"marines", "wh_main_brt_bordeleaux"},
    {"trident_pegasus", "wh_main_brt_bordeleaux"},
    {"trident_knight", "wh_main_brt_bordeleaux"},
    {"couronne_knights", "wh_main_brt_bretonnia"},
    {"grail_pilgrims", "wh_main_brt_carcassonne"},
    {"chevaliers", "wh2_dlc14_brt_chevaliers_de_lyonesse"},
    {"chevalier_cavalry", "wh2_dlc14_brt_chevaliers_de_lyonesse"},
    {"sailors", "wh_main_brt_bordeleaux"},
    {"talsyn_hawks", "wh_dlc05_wef_wood_elves"},
    {"talsyn_hawks", "wh2_main_hef_avelorn"},
    {"steelbeards", "wh2_dlc17_dwf_thorek_ironbrow"},
    {"storm_wardens", "wh_main_dwf_barak_varr"},
    {"storm_wardens", "wh_main_dwf_dwarfs"},
    {"true_king", "wh_main_dwf_karak_izor"},
    {"knights_caledor", "wh2_dlc15_hef_imrik"},
    {"heavy_goblins", "wh2_dlc15_grn_broken_axe"},
    {"heavy_goblins", "wh_main_grn_crooked_moon"},
    {"colossal_squig", "wh_main_grn_crooked_moon"},
    {"nag_guard", "wh2_dlc09_tmb_followers_of_nagash"},
    {"wh_dlc01_chs_inf_forsaken_0", "wh_dlc08_nor_wintertooth"},
    {"wh2_dlc15_grn_mon_river_trolls_0", "wh_dlc08_nor_wintertooth"},
    {"wh2_dlc15_grn_mon_stone_trolls_0", "wh_dlc08_nor_wintertooth"},
    {"wh2_dlc12_lzd_mon_ancient_stegadon_1_nakai", "wh2_dlc13_lzd_spirits_of_the_jungle"},
    {"wh2_dlc12_lzd_mon_bastiladon_3_nakai", "wh2_dlc13_lzd_spirits_of_the_jungle"},
    {"wh2_dlc13_lzd_mon_sacred_kroxigors_0_nakai", "wh2_dlc13_lzd_spirits_of_the_jungle"},
    {"wh2_main_lzd_cav_horned_ones_0_nakai", "wh2_dlc13_lzd_spirits_of_the_jungle"},
    {"wh2_main_lzd_inf_temple_guards_nakai", "wh2_dlc13_lzd_spirits_of_the_jungle"},
    {"wh2_main_lzd_mon_kroxigors_nakai", "wh2_dlc13_lzd_spirits_of_the_jungle"}
}

local mercenaries = {
	{
        key = "forest_goblins",
        military_groupings = {"wh_main_group_savage_orcs","wh_main_group_greenskins"},
        category = "inf_melee",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 1,
        ritual = {
            key = "forest_goblins",
            glory_cost = 20,
        },
    },
	{
        key = "wyvern",
        military_groupings = {"wh_main_group_savage_orcs","wh_main_group_greenskins"},
        category = "war_beast",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "wyvern",
            glory_cost = 80,
        },
    },
	{
        key = "chaos_dragon",
        military_groupings = {"wh_main_group_chaos"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "chaos_dragon",
            glory_cost = 120,
        },
    },
	{
        key = "red_guard",
        military_groupings = {"wh2_main_skv"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "red_guard",
            glory_cost = 120,
        },
    },
	{
        key = "deathvermin",
        military_groupings = {"wh2_main_skv"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "deathvermin",
            glory_cost = 120,
        },
    },
	{
        key = "forest_goblins_bow",
        military_groupings = {"wh_main_group_savage_orcs","wh_main_group_greenskins"},
        category = "inf_ranged",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 1,
        ritual = {
            key = "forest_goblins_bow",
            glory_cost = 20,
        },
    },
	{
        key = "shieldbreakers_human",
        military_groupings = {"wh_main_group_dwarfs"},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "shieldbreakers_human",
            glory_cost = 80,
        },
    },
	{
        key = "imperial_foot",
        military_groupings = {"wh_main_group_empire","wh_main_group_empire_reikland"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "imperial_foot",
            glory_cost = 120,
        },
    },
	{
        key = "imperial_zombie",
        military_groupings = {},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "imperial_zombie",
            glory_cost = 120,
        },
    },
	{
        key = "trident_knight",
        military_groupings = {nil},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "trident_knight",
            glory_cost = 120,
        },
    },
	{
        key = "reiksguard_foot",
        military_groupings = {"wh_main_group_empire","wh_main_group_empire_reikland"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "reiksguard_foot",
            glory_cost = 120,
        },
    },
	{
        key = "bonebreaker",
        military_groupings = {"wh2_main_skv"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "bonebreaker",
            glory_cost = 120,
        },
    },
	{
        key = "spear_boyz",
        military_groupings = {"wh_main_group_greenskins"},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "spear_boyz",
            glory_cost = 20,
        },
    },
	{
        key = "billmen",
        military_groupings = {"wh_main_group_bretonnia"},
        category = "inf_melee",
        group = "core",
        weight = 3,
        tier = nil,
        cost = 2,
        ritual = {
            key = "billmen",
            glory_cost = 20,
        },
    },
	{
        key = "sergeants",
        military_groupings = {"wh_main_group_bretonnia"},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "sergeants",
            glory_cost = 65,
        },
    },
	{
        key = "squires",
        military_groupings = {"wh_main_group_bretonnia"},
        category = "inf_melee",
        group = "core",
        weight = 3,
        tier = nil,
        cost = 2,
        ritual = {
            key = "squires",
            glory_cost = 20,
        },
    },
	{
        key = "rangers_shotgun",
        military_groupings = {"wh_main_group_dwarfs"},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "rangers_shotgun",
            glory_cost = 65,
        },
    },
	{
        key = "rangers",
        military_groupings = {"wh_main_group_dwarfs"},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "rangers",
            glory_cost = 65,
        },
    },
	{
        key = "mounted_squires",
        military_groupings = {"wh_main_group_bretonnia"},
        category = "cavalry",
        group = "core",
        weight = 3,
        tier = nil,
        cost = 2,
        ritual = {
            key = "mounted_squires",
            glory_cost = 20,
        },
    },
	{
        key = "dead_squires",
        military_groupings = {"wh2_dlc11_vmp_the_barrow_legion"},
        category = "cavalry",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "dead_squires",
            glory_cost = 65,
        },
    },
	{
        key = "shieldbreakers",
        military_groupings = {"wh_main_group_dwarfs"},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "shieldbreakers",
            glory_cost = 65,
        },
    },
	{
        key = "big_uns_spearz",
        military_groupings = {"wh_main_group_greenskins","wh_main_group_savage_orcs"},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "big_uns_spearz",
            glory_cost = 20,
        },
    },
	{
        key = "black_bear",
        military_groupings = {"wh_main_group_empire","wh_main_group_empire_reikland"},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "black_bear",
            glory_cost = 120,
        },
    },
	{
        key = "gigantic_spiders",
        military_groupings = {"wh_main_group_greenskins","wh_main_group_savage_orcs"},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "gigantic_spiders",
            glory_cost = 65,
        },
    },
	{
        key = "TKzombie",
        military_groupings = {"wh2_dlc09_tomb_kings_arkhan"},
        category = "nil",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 0,
        ritual = {
            key = "TKzombie",
            glory_cost = 20,
        },
    },
	{
        key = "pestigors",
        military_groupings = {"wh_dlc03_group_beastmen","chaos_servants"},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pestigors",
            glory_cost = 65,
        },
    },
	{
        key = "pestigors_mono",
        military_groupings = {"wh3_main_nur"},
        category = "nil",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pestigors_mono",
            glory_cost = 120,
        },
    },
	{
        key = "tzaangors",
        military_groupings = {"wh_dlc03_group_beastmen","chaos_servants"},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "tzaangors",
            glory_cost = 65,
        },
    },
	{
        key = "tzaangors_mono",
        military_groupings = {"wh3_main_pro_tze","wh3_main_tze"},
        category = "nil",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "tzaangors_mono",
            glory_cost = 120,
        },
    },
	{
        key = "slaangors",
        military_groupings = {"wh_dlc03_group_beastmen","chaos_servants","decadent_host"},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "slaangors",
            glory_cost = 65,
        },
    },
	{
        key = "slaangors_mono",
        military_groupings = {"wh3_main_sla"},
        category = "nil",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "slaangors_mono",
            glory_cost = 120,
        },
    },
	{
        key = "khorngors",
        military_groupings = {"wh_dlc03_group_beastmen","chaos_servants"},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "khorngors",
            glory_cost = 65,
        },
    },
	{
        key = "khorngors_mono",
        military_groupings = {"wh3_main_pro_kho","wh3_main_kho"},
        category = "nil",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "khorngors_mono",
            glory_cost = 120,
        },
    },
	{
        key = "glade_riders",
        military_groupings = {"wh_dlc05_group_wood_elves"},
        category = "cavalry",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "glade_riders",
            glory_cost = 20,
        },
    },
	{
        key = "grave_spears",
        military_groupings = {"wh_main_group_vampire_counts"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "grave_spears",
            glory_cost = 120,
        },
    },
	{
        key = "elven_warriors",
        military_groupings = {"wh2_main_hef"},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "elven_warriors",
            glory_cost = 20,
        },
    },
	{
        key = "elf_pirates",
        military_groupings = {nil},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "elf_pirates",
            glory_cost = 80,
        },
    },
	{
        key = "warriors",
        military_groupings = {"wh_dlc05_group_wood_elves"},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "warriors",
            glory_cost = 20,
        },
    },
	{
        key = "unholy_pilgrims",
        military_groupings = {"wh2_dlc11_vmp_the_barrow_legion"},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "unholy_pilgrims",
            glory_cost = 20,
        },
    },
	{
        key = "brtzombie",
        military_groupings = {"wh2_dlc11_vmp_the_barrow_legion"},
        category = "inf_melee",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 0,
        ritual = {
            key = "brtzombie",
            glory_cost = 20,
        },
    },
	{
        key = "brtzombieknight",
        military_groupings = {"wh2_dlc11_vmp_the_barrow_legion"},
        category = "inf_melee",
        group = "rare",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "brtzombieknight",
            glory_cost = 120,
        },
    },
	{
        key = "blackguard",
        military_groupings = {"wh2_main_def"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "blackguard",
            glory_cost = 120,
        },
    },
	{
        key = "huscarls",
        military_groupings = {"wh_main_group_norsca","chaos_servants","decadent_host"},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "huscarls",
            glory_cost = 80,
        },
    },
	{
        key = "reaver",
        military_groupings = {"wh_dlc08_nor_norsca"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "reaver",
            glory_cost = 120,
        },
    },
	{
        key = "bondsmen",
        military_groupings = {"wh_main_group_norsca","chaos_servants","decadent_host"},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "bondsmen",
            glory_cost = 65,
        },
    },
	{
        key = "bondsmen_spears",
        military_groupings = {"wh_main_group_norsca","chaos_servants","decadent_host"},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "bondsmen_spears",
            glory_cost = 65,
        },
    },
	{
        key = "arbalists",
        military_groupings = {"wh_main_group_bretonnia"},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "arbalists",
            glory_cost = 65,
        },
    },
	{
        key = "chevaliers",
        military_groupings = {nil},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "chevaliers",
            glory_cost = 80,
        },
    },
	{
        key = "dismounted_knights",
        military_groupings = {"wh_main_group_bretonnia"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "dismounted_knights",
            glory_cost = 120,
        },
    },
	{
        key = "cultists",
        military_groupings = {"wh_main_group_chaos","chaos_servants","decadent_host"},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "cultists",
            glory_cost = 65,
        },
    },
	{
        key = "hunters",
        military_groupings = {"wh_main_group_norsca","decadent_host"},
        category = "inf_ranged",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "hunters",
            glory_cost = 20,
        },
    },
	{
        key = "slaanesh_warriors",
        military_groupings = {nil},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "slaanesh_warriors",
            glory_cost = 80,
        },
    },
	{
        key = "daughters",
        military_groupings = {"wh_main_group_chaos","chaos_servants","decadent_host"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "daughters",
            glory_cost = 120,
        },
    },
	{
        key = "khaine_spears",
        military_groupings = {nil},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "khaine_spears",
            glory_cost = 80,
        },
    },
	{
        key = "creeping_dread",
        military_groupings = {"wh2_main_def"},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "creeping_dread",
            glory_cost = 120,
        },
    },
	{
        key = "fervid_fang",
        military_groupings = {"wh2_main_skv"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "fervid_fang",
            glory_cost = 120,
        },
    },
	{
        key = "scouts",
        military_groupings = {"wh_main_group_empire","wh_main_group_empire_reikland"},
        category = "inf_ranged",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "scouts",
            glory_cost = 80,
        },
    },
	{
        key = "templars",
        military_groupings = {nil},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "templars",
            glory_cost = 120,
        },
    },
	{
        key = "white_wolf",
        military_groupings = {nil},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "white_wolf",
            glory_cost = 120,
        },
    },
	{
        key = "colossal_squig",
        military_groupings = {nil},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "colossal_squig",
            glory_cost = 120,
        },
    },
	{
        key = "war_hawks",
        military_groupings = {"wh_dlc05_group_wood_elves"},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "war_hawks",
            glory_cost = 65,
        },
    },
	{
        key = "shield_merc",
        military_groupings = {"wh_main_group_dwarfs"},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "shield_merc",
            glory_cost = 120,
        },
    },
	{
        key = "out_scout",
        military_groupings = {"wh_main_group_empire","wh_main_group_empire_reikland"},
        category = "cavalry",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "out_scout",
            glory_cost = 65,
        },
    },
	{
        key = "steelbeards",
        military_groupings = {nil},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "steelbeards",
            glory_cost = 120,
        },
    },
	{
        key = "runic_guardian",
        military_groupings = {"wh_main_group_dwarfs"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "runic_guardian",
            glory_cost = 120,
        },
    },
	{
        key = "vengeance_copter",
        military_groupings = {"wh_main_group_dwarfs"},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "vengeance_copter",
            glory_cost = 80,
        },
    },
	{
        key = "w_boyz",
        military_groupings = {nil},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "w_boyz",
            glory_cost = 120,
        },
    },
	{
        key = "eshin_hand",
        military_groupings = {"wh2_main_skv"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "eshin_hand",
            glory_cost = 120,
        },
    },
	{
        key = "nag_guard",
        military_groupings = {nil},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "nag_guard",
            glory_cost = 120,
        },
    },
	{
        key = "nuln_ironsides",
        military_groupings = {"wh_main_group_empire","wh_main_group_empire_reikland"},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "nuln_ironsides",
            glory_cost = 120,
        },
    },
	{
        key = "talsyn_hawks",
        military_groupings = {nil},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "talsyn_hawks",
            glory_cost = 120,
        },
    },
	{
        key = "wildkin",
        military_groupings = {"wh_main_group_norsca","decadent_host"},
        category = "war_beast",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "wildkin",
            glory_cost = 65,
        },
    },
	{
        key = "crows_nest_zombie",
        military_groupings = {nil},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "crows_nest_zombie",
            glory_cost = 120,
        },
    },
	{
        key = "crows_nest",
        military_groupings = {nil},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "crows_nest",
            glory_cost = 120,
        },
    },
	{
        key = "picks",
        military_groupings = {"wh_main_dwf_karak_kadrin"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "picks",
            glory_cost = 120,
        },
    },
	{
        key = "true_king",
        military_groupings = {nil},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "true_king",
            glory_cost = 120,
        },
    },
	{
        key = "sailors",
        military_groupings = {nil},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "sailors",
            glory_cost = 65,
        },
    },
	{
        key = "trident_pegasus",
        military_groupings = {nil},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "trident_pegasus",
            glory_cost = 120,
        },
    },
	{
        key = "marines",
        military_groupings = {nil},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "marines",
            glory_cost = 65,
        },
    },
	{
        key = "boarders",
        military_groupings = {nil},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "boarders",
            glory_cost = 65,
        },
    },
	{
        key = "deck_clearers",
        military_groupings = {nil},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "deck_clearers",
            glory_cost = 120,
        },
    },
	{
        key = "grail_pilgrims",
        military_groupings = {nil},
        category = "inf_melee",
        group = "core",
        weight = 3,
        tier = nil,
        cost = 2,
        ritual = {
            key = "grail_pilgrims",
            glory_cost = 20,
        },
    },
	{
        key = "chevalier_cavalry",
        military_groupings = {nil},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "chevalier_cavalry",
            glory_cost = 120,
        },
    },
	{
        key = "couronne_knights",
        military_groupings = {nil},
        category = "cavalry",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "couronne_knights",
            glory_cost = 80,
        },
    },
	{
        key = "free_company_axemen",
        military_groupings = {"wh_main_group_empire","wh_main_group_empire_reikland"},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "free_company_axemen",
            glory_cost = 20,
        },
    },
	{
        key = "free_company_spears",
        military_groupings = {"wh_main_group_empire","wh_main_group_empire_reikland"},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "free_company_spears",
            glory_cost = 20,
        },
    },
	{
        key = "heavy_goblins",
        military_groupings = {nil},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "heavy_goblins",
            glory_cost = 80,
        },
    },
	{
        key = "slaanesh_marauders",
        military_groupings = {nil},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "slaanesh_marauders",
            glory_cost = 65,
        },
    },
	{
        key = "storm_wardens",
        military_groupings = {nil},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "storm_wardens",
            glory_cost = 120,
        },
    },
	{
        key = "grim_rangers",
        military_groupings = {"wh2_main_hef_yvresse"},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "grim_rangers",
            glory_cost = 65,
        },
    },
	{
        key = "damned_knights",
        military_groupings = {"wh2_dlc11_cst_the_drowned"},
        category = "inf_melee",
        group = "special",
        weight = 3,
        tier = nil,
        cost = 2,
        ritual = {
            key = "damned_knights",
            glory_cost = 95,
        },
    },
	{
        key = "sylvanian_levy",
        military_groupings = {"wh_main_vmp_schwartzhafen"},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "sylvanian_levy",
            glory_cost = 20,
        },
    },
	{
        key = "poxvermin",
        military_groupings = {nil},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "poxvermin",
            glory_cost = 80,
        },
    },
	{
        key = "cold_riders",
        military_groupings = {nil},
        category = "cavalry",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "cold_riders",
            glory_cost = 65,
        },
    },
	{
        key = "tyrant_blades",
        military_groupings = {nil},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "tyrant_blades",
            glory_cost = 120,
        },
    },
	{
        key = "longshanks",
        military_groupings = {"wh_main_group_empire"},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "longshanks",
            glory_cost = 120,
        },
    },
	{
        key = "kulmen",
        military_groupings = {"skeggi"},
        category = "inf_melee",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "kulmen",
            glory_cost = 20,
        },
    },
	{
        key = "slavers",
        military_groupings = {"skeggi"},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "slavers",
            glory_cost = 65,
        },
    },
	{
        key = "kulspearmen",
        military_groupings = {"skeggi"},
        category = "inf_melee",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "kulspearmen",
            glory_cost = 20,
        },
    },
	{
        key = "carnosaur",
        military_groupings = {"skeggi"},
        category = "inf_melee",
        group = "rare",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "carnosaur",
            glory_cost = 140,
        },
    },
	{
        key = "skeggi_coldones",
        military_groupings = {"skeggi"},
        category = "nil",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "skeggi_coldones",
            glory_cost = 65,
        },
    },
	{
        key = "skink_thralls",
        military_groupings = {"skeggi"},
        category = "inf_ranged",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 1,
        ritual = {
            key = "skink_thralls",
            glory_cost = 20,
        },
    },
	{
        key = "warmbloods",
        military_groupings = {"skeggi"},
        category = "inf_ranged",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "warmbloods",
            glory_cost = 20,
        },
    },
	{
        key = "frontiersmen",
        military_groupings = {"skeggi"},
        category = "inf_ranged",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "frontiersmen",
            glory_cost = 80,
        },
    },
	{
        key = "karls",
        military_groupings = {"skeggi"},
        category = "cavalry",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "karls",
            glory_cost = 20,
        },
    },
	{
        key = "spear_karls",
        military_groupings = {"skeggi"},
        category = "inf_melee",
        group = "core",
        weight = nil,
        tier = nil,
        cost = 2,
        ritual = {
            key = "spear_karls",
            glory_cost = 20,
        },
    },
	{
        key = "hofkarls",
        military_groupings = {"skeggi"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "hofkarls",
            glory_cost = 120,
        },
    },
	{
        key = "second_sons",
        military_groupings = {"skeggi"},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "second_sons",
            glory_cost = 80,
        },
    },
	{
        key = "hunting_dogs",
        military_groupings = {"wh2_dlc13_emp_the_huntmarshals_expedition"},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "hunting_dogs",
            glory_cost = 65,
        },
    },
	{
        key = "skeggi_dogs",
        military_groupings = {"skeggi"},
        category = "inf_melee",
        group = "core",
        weight = 3,
        tier = nil,
        cost = 2,
        ritual = {
            key = "skeggi_dogs",
            glory_cost = 20,
        },
    },
	{
        key = "skeggi_hounds",
        military_groupings = {"skeggi"},
        category = "inf_melee",
        group = "core",
        weight = nil,
        tier = nil,
        cost = 2,
        ritual = {
            key = "skeggi_hounds",
            glory_cost = 20,
        },
    },
	{
        key = "vanguard",
        military_groupings = {"skeggi"},
        category = "inf_ranged",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "vanguard",
            glory_cost = 80,
        },
    },
	{
        key = "trappers",
        military_groupings = {"skeggi"},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "trappers",
            glory_cost = 65,
        },
    },
	{
        key = "kroxigor_thralls",
        military_groupings = {"skeggi"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "kroxigor_thralls",
            glory_cost = 120,
        },
    },
	{
        key = "terradon_horde",
        military_groupings = {"skeggi"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "terradon_horde",
            glory_cost = 120,
        },
    },
	{
        key = "engineers_imp",
        military_groupings = {nil},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "engineers_imp",
            glory_cost = 120,
        },
    },
	{
        key = "red_host",
        military_groupings = {"wh2_dlc12_lzd_cult_of_sotek"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "red_host",
            glory_cost = 120,
        },
    },
	{
        key = "hofkarl_mounted",
        military_groupings = {"skeggi"},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "hofkarl_mounted",
            glory_cost = 120,
        },
    },
	{
        key = "skg_war_wagon",
        military_groupings = {"skeggi"},
        category = "war_machine",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "skg_war_wagon",
            glory_cost = 80,
        },
    },
	{
        key = "skeleton_horsemen",
        military_groupings = {"wh_main_group_vampire_counts"},
        category = "cavalry",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "skeleton_horsemen",
            glory_cost = 20,
        },
    },
	{
        key = "sotek_picks",
        military_groupings = {"skeggi"},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "sotek_picks",
            glory_cost = 65,
        },
    },
	{
        key = "sotek_shield",
        military_groupings = {"skeggi"},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "sotek_shield",
            glory_cost = 65,
        },
    },
	{
        key = "necromancer_group",
        military_groupings = {"wh_main_group_vampire_counts"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "necromancer_group",
            glory_cost = 120,
        },
    },
	{
        key = "scholars",
        military_groupings = {nil},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "scholars",
            glory_cost = 120,
        },
    },
	{
        key = "nordlander",
        military_groupings = {nil},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "nordlander",
            glory_cost = 20,
        },
    },
	{
        key = "knights_caledor",
        military_groupings = {nil},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "knights_caledor",
            glory_cost = 120,
        },
    },
	{
        key = "skryre_rat",
        military_groupings = {nil},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "skryre_rat",
            glory_cost = 120,
        },
    },
	{
        key = "chrace_cav",
        military_groupings = {"wh2_main_hef_chrace"},
        category = "cavalry",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "chrace_cav",
            glory_cost = 65,
        },
    },
	{
        key = "shadow_melee",
        military_groupings = {"wh2_main_hef_nagarythe"},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "shadow_melee",
            glory_cost = 80,
        },
    },
	{
        key = "skeggi_bret",
        military_groupings = {"skeggi"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "skeggi_bret",
            glory_cost = 120,
        },
    },
	{
        key = "ogre_dead",
        military_groupings = {"wh2_dlc11_cst_vampire_coast", "wh2_dlc11_cst_noctilus", "wh2_dlc11_cst_the_drowned"},
        category = "inf_ranged",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "ogre_dead",
            glory_cost = 80,
        },
    },
	{
        key = "skeggi_ogre",
        military_groupings = {"skeggi"},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "skeggi_ogre",
            glory_cost = 120,
        },
    },
	{
        key = "captains_altdorf",
        military_groupings = {"wh_main_group_empire_reikland","wh_main_group_empire"},
        category = "war_beast",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "captains_altdorf",
            glory_cost = 120,
        },
    },
	{
        key = "doomed_legion",
        military_groupings = {"wh2_dlc11_vmp_the_barrow_legion"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "doomed_legion",
            glory_cost = 120,
        },
    },
	{
        key = "zombo_dragon",
        military_groupings = {"wh_main_group_vampire_counts"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "zombo_dragon",
            glory_cost = 120,
        },
    },
	{
        key = "skegadon",
        military_groupings = {"skeggi"},
        category = "war_beast",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "skegadon",
            glory_cost = 120,
        },
    },
	{
        key = "marauder_halberds",
        military_groupings = {"wh_main_group_chaos"},
        category = "inf_melee",
        group = "core",
        weight = nil,
        tier = nil,
        cost = 2,
        ritual = {
            key = "marauder_halberds",
            glory_cost = 20,
        },
    },
	{
        key = "smiths",
        military_groupings = {"wh_main_group_bretonnia"},
        category = "inf_melee",
        group = "core",
        weight = nil,
        tier = nil,
        cost = 2,
        ritual = {
            key = "smiths",
            glory_cost = 20,
        },
    },
	{
        key = "kul_bows",
        military_groupings = {"skeggi"},
        category = "cavalry",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "kul_bows",
            glory_cost = 80,
        },
    },
	{
        key = "skg_knights",
        military_groupings = {"skeggi"},
        category = "cavalry",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "skg_knights",
            glory_cost = 80,
        },
    },
	{
        key = "bonepickers",
        military_groupings = {"wh3_main_ogr"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "bonepickers",
            glory_cost = 120,
        },
    },
	{
        key = "caravan_guard",
        military_groupings = {"skeggi"},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "caravan_guard",
            glory_cost = 65,
        },
    },
	{
        key = "celestial_riders",
        military_groupings = {"wh3_main_cth"},
        category = "war_beast",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "celestial_riders",
            glory_cost = 80,
        },
    },
	{
        key = "cathay_mace_peasant",
        military_groupings = {"wh3_main_cth"},
        category = "inf_melee",
        group = "core",
        weight = nil,
        tier = nil,
        cost = 2,
        ritual = {
            key = "cathay_mace_peasant",
            glory_cost = 20,
        },
    },
	{
        key = "dismounted_gryphon",
        military_groupings = {"wh3_main_pro_ksl","wh3_main_ksl"},
        category = "inf_ranged",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "dismounted_gryphon",
            glory_cost = 80,
        },
    },
	{
        key = "druzhina",
        military_groupings = {"wh3_main_pro_ksl","wh3_main_ksl"},
        category = "war_beast",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "druzhina",
            glory_cost = 80,
        },
    },
	{
        key = "fire_hail",
        military_groupings = {"wh3_main_cth"},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "fire_hail",
            glory_cost = 120,
        },
    },
	{
        key = "fireglaive_warriors",
        military_groupings = {"wh3_dlc23_group_chaos_dwarfs"},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "fireglaive_warriors",
            glory_cost = 65,
        },
    },
	{
        key = "firelancers",
        military_groupings = {"wh3_main_cth"},
        category = "war_beast",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "firelancers",
            glory_cost = 120,
        },
    },
	{
        key = "gnoblar_archers",
        military_groupings = {"wh3_main_ogr"},
        category = "inf_ranged",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 1,
        ritual = {
            key = "gnoblar_archers",
            glory_cost = 20,
        },
    },
	{
        key = "gnoblar_swords",
        military_groupings = {"wh3_main_ogr"},
        category = "inf_melee",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 1,
        ritual = {
            key = "gnoblar_swords",
            glory_cost = 20,
        },
    },
	{
        key = "gnoblar_wolves",
        military_groupings = {"wh3_main_ogr"},
        category = "cavalry",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "gnoblar_wolves",
            glory_cost = 65,
        },
    },
	{
        key = "jade_archers",
        military_groupings = {"wh3_main_cth"},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "jade_archers",
            glory_cost = 65,
        },
    },
	{
        key = "jade_axemen",
        military_groupings = {"wh3_main_cth"},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "jade_axemen",
            glory_cost = 20,
        },
    },
	{
        key = "kossack_scout",
        military_groupings = {"skeggi"},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "kossack_scout",
            glory_cost = 120,
        },
    },
	{
        key = "kossar_bardiche",
        military_groupings = {"wh3_main_pro_ksl","wh3_main_ksl"},
        category = "inf_melee",
        group = "core",
        weight = 3,
        tier = nil,
        cost = 2,
        ritual = {
            key = "kossar_bardiche",
            glory_cost = 20,
        },
    },
	{
        key = "kossar_sword",
        military_groupings = {"wh3_main_pro_ksl","wh3_main_ksl"},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "kossar_sword",
            glory_cost = 20,
        },
    },
	{
        key = "marauder_archers",
        military_groupings = {"wh3_main_sla"},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "marauder_archers",
            glory_cost = 65,
        },
    },
	{
        key = "nehek_axe",
        military_groupings = {"wh2_dlc09_tomb_kings_arkhan","wh2_dlc09_tomb_kings"},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "nehek_axe",
            glory_cost = 80,
        },
    },
	{
        key = "nehek_bowmen",
        military_groupings = {"wh2_dlc09_tomb_kings_arkhan","wh2_dlc09_tomb_kings"},
        category = "inf_ranged",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "nehek_bowmen",
            glory_cost = 80,
        },
    },
	{
        key = "red_crested_cohort",
        military_groupings = {"wh2_main_lzd"},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "red_crested_cohort",
            glory_cost = 65,
        },
    },
	{
        key = "repeater_crossbows",
        military_groupings = {"wh3_main_cth"},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "repeater_crossbows",
            glory_cost = 120,
        },
    },
	{
        key = "yuan_dao",
        military_groupings = {"wh3_main_cth"},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "yuan_dao",
            glory_cost = 120,
        },
    },
	{
        key = "swiftwings",
        military_groupings = {"wh3_main_pro_ksl","wh3_main_ksl"},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "swiftwings",
            glory_cost = 120,
        },
    },
	{
        key = "tomb_horsemen",
        military_groupings = {"wh2_dlc09_tomb_kings_arkhan","wh2_dlc09_tomb_kings"},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "tomb_horsemen",
            glory_cost = 120,
        },
    },
	{
        key = "woodsmen",
        military_groupings = {"wh3_main_pro_ksl","wh3_main_ksl"},
        category = "inf_melee",
        group = "core",
        weight = nil,
        tier = nil,
        cost = 2,
        ritual = {
            key = "woodsmen",
            glory_cost = 20,
        },
    },
	{
        key = "yin_spears",
        military_groupings = {"wh3_main_cth"},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "yin_spears",
            glory_cost = 80,
        },
    },
	{
        key = "cr_ksl_inf_streltsi_bardiche",
        military_groupings = {"wh3_main_ksl"},
        category = "inf_melee",
        group = "core",
        weight = nil,
        tier = nil,
        cost = 2,
        ritual = {
            key = "cr_ksl_inf_streltsi_bardiche",
            glory_cost = 20,
        },
    },
	{
        key = "champions_khorne",
        military_groupings = {"wh_main_group_norsca","wh3_main_pro_kho","wh3_main_kho"},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "champions_khorne",
            glory_cost = 80,
        },
    },
	{
        key = "champions_tzeentch",
        military_groupings = {"wh_main_group_norsca","wh3_main_pro_tze","wh3_main_tze"},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "champions_tzeentch",
            glory_cost = 80,
        },
    },
	{
        key = "champions_slaanesh",
        military_groupings = {"wh_main_group_norsca","wh3_main_sla"},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "champions_slaanesh",
            glory_cost = 80,
        },
    },
	{
        key = "champions_nurgle",
        military_groupings = {"wh_main_group_norsca","wh3_main_nur"},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "champions_nurgle",
            glory_cost = 80,
        },
    },
	{
        key = "zombie_horde",
        military_groupings = {"wh_main_group_vampire_counts"},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "zombie_horde",
            glory_cost = 20,
        },
    },
}

unit_to_factions = {}
for _, unit in pairs(units_to_faction) do
    print("Adding: "..tostring(unit[1])..':'..tostring(unit[2]))
    if not unit_to_factions[unit[1]] then
        unit_to_factions[unit[1]] = {unit[2]}
    else
        table.insert(unit_to_factions[unit[1]], unit[2])
    end
end

for _, merc in pairs(mercenaries) do
    if #merc.military_groupings == 0 then
        for _, val in pairs(unit_to_factions[merc.key]) do
            table.insert(merc.military_groupings, val)
        end
    end
    local groups = ""
    for _, group in pairs(merc.military_groupings) do
        groups = groups..'"'..group..'",'
    end
    merc.military_groupings = groups
end

file = io.open("output/modded_mercs_input_fixed.lua", "w")
io.output(file)

io.write("\n# Add the mercenary to pttg in your script: \n")
io.write("local mercenaries = {\n")
for _, mercenary in pairs(mercenaries) do
    print("Processing: "..mercenary.key)

    io.write(string.format('\t{\
        key = "%s",\
        military_groupings = {%s},\
        category = "%s",\
        group = "%s",\
        weight = %s,\
        tier = nil,\
        cost = %s,\
        ritual = {\
            key = "pttg_ritual_%s",\
            glory_cost = %s,\
        },\
    },\n', mercenary.key, mercenary.military_groupings, mercenary.category, mercenary.group, mercenary.weight, mercenary.cost, mercenary.ritual.key, mercenary.ritual.glory_cost
))
end
io.write("}\n")