local modded_units = {
        {"forest_goblins", "core"},
        {"wyvern", "special", 2},
        {"chaos_dragon", "rare", 1},
        {"red_guard", "rare", 1},
        {"deathvermin", "rare", 1},
        {"forest_goblins_bow", "core" },
        {"shieldbreakers_human", "special", 2},
        {"imperial_foot", "rare", 1},
        {"imperial_zombie", "rare", 1},
        {"trident_knight", "rare", 1},
        {"reiksguard_foot", "rare", 1},
        {"bonebreaker", "rare", 1},
        {"spear_boyz", "core"},
        {"billmen", "core"},
        {"sergeants", "special", 1},
        {"squires", "core"},
        {"rangers_shotgun", "special", 1},
        {"rangers", "special", 1},
        {"mounted_squires", "core"},
        {"dead_squires", "special", 1},
        {"shieldbreakers", "special", 1},
        {"big_uns_spearz", "core" },
        {"black_bear", "rare", 1},
        {"gigantic_spiders", "special", 1},
        {"TKzombie", "core"},
        {"pestigors", "special", 1},
        {"pestigors_mono", "rare", 1},
        {"tzaangors", "special", 1},
        {"tzaangors_mono", "rare", 1},
        {"slaangors", "special", 1},
        {"slaangors_mono", "rare", 1},
        {"khorngors", "special", 1},
        {"khorngors_mono", "rare", 1},
        {"glade_riders", "core" },
        {"grave_spears", "rare", 1},
        {"elven_warriors", "core" },
        {"elf_pirates", "special", 2},
        {"warriors", "core"},
        {"unholy_pilgrims", "core"},
        {"z_flag", "core"},
        {"brtzombie", "core"},
        {"brtzombieknight", "rare", 1},
        {"blackguard", "rare", 1},
        {"huscarls", "special", 2},
        {"reaver", "rare", 1},
        {"bondsmen", "special", 1},
        {"bondsmen_spears", "special", 1},
        {"arbalists", "special", 1},
        {"chevaliers", "special", 2},
        {"dismounted_knights", "rare", 1},
        {"cultists", "special", 1},
        {"hunters", "core"},
        {"slaanesh_warriors", "special", 2},
        {"daughters", "rare", 1},
        {"khaine_spears", "special", 2},
        {"creeping_dread", "rare", 1},
        {"fervid_fang", "rare", 1},
        {"scouts", "special", 2},
        {"templars", "rare", 1},
        {"white_wolf", "rare", 1},
        {"colossal_squig", "rare", 1},
        {"war_hawks", "special", 1},
        {"shield_merc", "rare", 1},
        {"out_scout", "special", 1},
        {"steelbeards", "rare", 1},
        {"runic_guardian", "rare", 1},
        {"vengeance_copter", "special", 2},
        {"w_boyz", "rare", 1},
        {"eshin_hand", "rare", 1},
        {"nag_guard", "rare", 1},
        {"nuln_ironsides", "rare", 1},
        {"talsyn_hawks", "rare", 1},
        {"wildkin", "special", 1},
        {"crows_nest_zombie", "rare", 1},
        {"crows_nest", "rare", 1},
        {"picks", "rare", 1},
        {"true_king", "rare", 1},
        {"sailors", "special", 1},
        {"trident_pegasus", "rare", 1},
        {"marines", "special", 1},
        {"boarders", "special", 1},
        {"deck_clearers", "rare", 1},
        {"grail_pilgrims", "core"},
        {"chevalier_cavalry", "rare", 1},
        {"couronne_knights", "special", 2},
        {"free_company_axemen", "core"},
        {"free_company_spears", "core"},
        {"heavy_goblins", "special", 2},
        {"slaanesh_marauders", "special", 1},
        {"storm_wardens", "rare", 1},
        {"grim_rangers", "special", 1},
        {"damned_knights", "special", 3},
        {"sylvanian_levy", "core"},
        {"poxvermin", "special", 2},
        {"cold_riders", "special", 1},
        {"tyrant_blades", "rare", 1},
        {"longshanks", "rare", 1},
        {"kulmen", "core"},
        {"slavers", "special", 1},
        {"kulspearmen", "core"},
        {"carnosaur", "rare", 2},
        {"skeggi_coldones", "special", 1},
        {"skink_thralls", "core"},
        {"warmbloods", "core"},
        {"frontiersmen", "special", 2},
        {"karls", "core"},
        {"spear_karls", "core"},
        {"hofkarls", "rare", 1},
        {"second_sons", "special", 2},
        {"hunting_dogs", "special", 1},
        {"skeggi_dogs", "core"},
        {"skeggi_hounds", "core"},
        {"vanguard", "special", 2},
        {"trappers", "special", 1},
        {"kroxigor_thralls", "rare", 1},
        {"terradon_horde", "rare", 1},
        {"engineers_imp", "rare", 1},
        {"red_host", "rare", 1},
        {"hofkarl_mounted", "rare", 1},
        {"skg_war_wagon", "special", 2},
        {"skeleton_horsemen", "core"},
        {"sotek_picks", "special", 1},
        {"sotek_shield", "special", 1},
        {"necromancer_group", "rare", 1},
        {"scholars", "rare", 1},
        {"nordlander", "core"},
        {"knights_caledor", "rare", 1},
        {"skryre_rat", "rare", 1},
        {"chrace_cav", "special", 1},
        {"shadow_melee", "special", 2},
        {"skeggi_bret", "rare", 1},
        {"ogre_dead", "special", 2},
        {"skeggi_ogre", "rare", 1},
        {"captains_altdorf", "rare", 1},
        {"doomed_legion", "rare", 1},
        {"zombo_dragon", "rare", 1},
        {"skegadon", "rare", 1},
        {"marauder_halberds", "core"},
        {"smiths", "core"},
        {"kul_bows", "special", 2},
        {"skg_knights", "special", 2},
        {"bonepickers", "rare", 1},
        {"caravan_guard", "special", 1},
        {"celestial_riders", "special", 2},
        {"cathay_mace_peasant", "core"},
        {"dismounted_gryphon", "special", 2},
        {"druzhina", "special", 2},
        {"fire_hail", "rare", 1},
        {"fireglaive_warriors", "special", 1},
        {"firelancers", "rare", 1},
        {"gnoblar_archers", "core"},
        {"gnoblar_swords", "core"},
        {"gnoblar_wolves", "special", 1},
        {"jade_archers", "special", 1},
        {"jade_axemen", "core"},
        {"kossack_scout", "rare", 1},
        {"kossar_bardiche", "core"},
        {"kossar_sword", "core"},
        {"marauder_archers", "special", 1},
        {"nehek_axe", "special", 2},
        {"nehek_bowmen", "special", 2},
        {"red_crested_cohort", "special", 1},
        {"repeater_crossbows", "rare", 1},
        {"yuan_dao", "rare", 1},
        {"swiftwings", "rare", 1},
        {"tomb_horsemen", "rare", 1},
        {"woodsmen", "core"},
        {"yin_spears", "special", 2},
        {"rangers_grenades", "special", 2},
        {"cr_ksl_inf_streltsi_bardiche", "core"},
        {"wh3_main_ksl_inf_kossars_tutorial_1", "core"},
        {"champions_khorne",  "special", 2},
        {"champions_tzeentch", "special", 2},
        {"champions_slaanesh",  "special", 2},
        {"champions_nurgle", "special", 2},
        {"zombie_horde", "core"}
}

modded_units_to_military_group ={
    {"zombo_dragon", "wh_main_group_vampire_counts"},
    {"zombie_horde", "wh_main_group_vampire_counts"},
    {"wyvern", "wh_main_group_savage_orcs"},
    {"wyvern", "wh_main_group_greenskins"},
    {"wildkin", "wh_main_group_norsca"},
    {"wh_main_vmp_inf_zombie_summoned", "wh_main_group_vampire_counts"},
    {"wh_dlc06_dwf_inf_rangers_1", "wh_main_group_dwarfs"},
    {"wh3_dlc24_ksl_mon_frost_wyrm", "wh_main_group_norsca"},
    {"warriors", "wh_dlc05_group_wood_elves"},
    {"war_hawks", "wh_dlc05_group_wood_elves"},
    {"vengeance_copter", "wh_main_group_dwarfs"},
    {"tzaangors", "wh_dlc03_group_beastmen"},
    {"tomb_horsemen", "wh2_dlc09_tomb_kings_arkhan"},
    {"tomb_horsemen", "wh2_dlc09_tomb_kings"},
    {"squires", "wh_main_group_bretonnia"},
    {"spear_boyz", "wh_main_group_greenskins"},
    {"sons_of_bretonnia", "wh_main_group_bretonnia"},
    {"smiths", "wh_main_group_bretonnia"},
    {"slaangors", "wh_dlc03_group_beastmen"},
    {"skeleton_horsemen", "wh_main_group_vampire_counts"},
    {"skele_coast_cst", "wh2_dlc11_group_vampire_coast"},
    {"skele_coast_cst", "wh2_dlc11_group_vampire_coast_sartosa"},
    {"shieldbreakers_human", "wh_main_group_dwarfs"},
    {"shieldbreakers", "wh_main_group_dwarfs"},
    {"shield_merc", "wh_main_group_dwarfs"},
    {"sergeants", "wh_main_group_bretonnia"},
    {"scouts", "wh_main_group_empire"},
    {"scouts", "wh_main_group_empire_reikland"},
    {"runic_guardian", "wh_main_group_dwarfs"},
    {"reiksguard_foot", "wh_main_group_empire"},
    {"reiksguard_foot", "wh_main_group_empire_reikland"},
    {"red_guard", "wh2_main_skv"},
    {"red_crested_cohort", "wh2_main_lzd"},
    {"rangers_shotgun", "wh_main_group_dwarfs"},
    {"rangers", "wh_main_group_dwarfs"},
    {"pestigors", "wh_dlc03_group_beastmen"},
    {"out_scout", "wh_main_group_empire"},
    {"out_scout", "wh_main_group_empire_reikland"},
    {"nuln_ironsides", "wh_main_group_empire"},
    {"nuln_ironsides", "wh_main_group_empire_reikland"},
    {"nehek_bowmen", "wh2_dlc09_tomb_kings_arkhan"},
    {"nehek_bowmen", "wh2_dlc09_tomb_kings"},
    {"nehek_axe", "wh2_dlc09_tomb_kings_arkhan"},
    {"nehek_axe", "wh2_dlc09_tomb_kings"},
    {"necromancer_group", "wh_main_group_vampire_counts"},
    {"mounted_squires", "wh_main_group_bretonnia"},
    {"marauder_halberds", "wh_main_group_chaos"},
    {"lord_of_change", "wh_main_group_chaos"},
    {"longshanks", "wh_main_group_empire"},
    {"khorngors", "wh_dlc03_group_beastmen"},
    {"imperial_foot", "wh_main_group_empire"},
    {"imperial_foot", "wh_main_group_empire_reikland"},
    {"huscarls", "wh_main_group_norsca"},
    {"hunters", "wh_main_group_norsca"},
    {"hand_eshin", "wh2_main_skv"},
    {"grave_spears", "wh_main_group_vampire_counts"},
    {"glade_riders", "wh_dlc05_group_wood_elves"},
    {"gigantic_spiders", "wh_main_group_greenskins"},
    {"gigantic_spiders", "wh_main_group_savage_orcs"},
    {"freed_monster", "wh2_main_def"},
    {"free_company_spears", "wh_main_group_empire"},
    {"free_company_spears", "wh_main_group_empire_reikland"},
    {"free_company_axemen", "wh_main_group_empire"},
    {"free_company_axemen", "wh_main_group_empire_reikland"},
    {"forest_goblins_bow", "wh_main_group_savage_orcs"},
    {"forest_goblins_bow", "wh_main_group_greenskins"},
    {"forest_goblins", "wh_main_group_savage_orcs"},
    {"forest_goblins", "wh_main_group_greenskins"},
    {"fireglaive_warriors", "wh3_dlc23_group_chaos_dwarfs"},
    {"fervid_fang", "wh2_main_skv"},
    {"eshin_hand", "wh2_main_skv"},
    {"elven_warriors", "wh2_main_hef"},
    {"dismounted_knights", "wh_main_group_bretonnia"},
    {"deathvermin", "wh2_main_skv"},
    {"daughters", "wh_main_group_chaos"},
    {"cultists_spawn", "wh_main_group_chaos"},
    {"cultists", "wh_main_group_chaos"},
    {"cst_skele", "wh2_dlc11_group_vampire_coast"},
    {"cst_skele", "wh2_dlc11_group_vampire_coast_sartosa"},
    {"cst_ghoul", "wh2_dlc11_group_vampire_coast"},
    {"cst_ghoul", "wh2_dlc11_group_vampire_coast_sartosa"},
    {"creeping_dread", "wh2_main_def"},
    {"chaos_dragon", "wh_main_group_chaos"},
    {"champions_tzeentch", "wh_main_group_norsca"},
    {"champions_slaanesh", "wh_main_group_norsca"},
    {"champions_nurgle", "wh_main_group_norsca"},
    {"champions_khorne", "wh_main_group_norsca"},
    {"captains_altdorf", "wh_main_group_empire_reikland"},
    {"captains_altdorf", "wh_main_group_empire"},
    {"bonebreaker", "wh2_main_skv"},
    {"bondsmen_spears", "wh_main_group_norsca"},
    {"bondsmen", "wh_main_group_norsca"},
    {"blackguard", "wh2_main_def"},
    {"black_bear", "wh_main_group_empire"},
    {"black_bear", "wh_main_group_empire_reikland"},
    {"billmen", "wh_main_group_bretonnia"},
    {"big_uns_spearz", "wh_main_group_greenskins"},
    {"big_uns_spearz", "wh_main_group_savage_orcs"},
    {"arbalists", "wh_main_group_bretonnia"},
    {"TKzombie", "wh2_dlc09_tomb_kings_arkhan"},
    {"cr_ksl_inf_streltsi_bardiche", "wh3_main_ksl"},
    {"wh3_main_ksl_inf_kossars_tutorial_1", "wh3_main_ksl"},
    {"yuan_dao", "wh3_main_cth"},
    {"cathay_mace_peasant", "wh3_main_cth"},
    {"yin_spears", "wh3_main_cth"},
    {"repeater_crossbows", "wh3_main_cth"},
    {"celestial_riders", "wh3_main_cth"},
    {"fire_hail", "wh3_main_cth"},
    {"jade_archers", "wh3_main_cth"},
    {"firelancers", "wh3_main_cth"},
    {"jade_axemen", "wh3_main_cth"},
    {"druzhina", "wh3_main_pro_ksl"},
    {"druzhina", "wh3_main_ksl"},
    {"swiftwings", "wh3_main_pro_ksl"},
    {"swiftwings", "wh3_main_ksl"},
    {"dismounted_gryphon", "wh3_main_pro_ksl"},
    {"dismounted_gryphon", "wh3_main_ksl"},
    {"kossar_sword", "wh3_main_pro_ksl"},
    {"kossar_sword", "wh3_main_ksl"},
    {"woodsmen", "wh3_main_pro_ksl"},
    {"woodsmen", "wh3_main_ksl"},
    {"kossar_bardiche", "wh3_main_pro_ksl"},
    {"kossar_bardiche", "wh3_main_ksl"},
    {"champions_khorne", "wh3_main_pro_kho"},
    {"champions_khorne", "wh3_main_kho"},
    {"khorngors_mono", "wh3_main_pro_kho"},
    {"khorngors_mono", "wh3_main_kho"},
    {"champions_slaanesh", "wh3_main_sla"},
    {"slaangors_mono", "wh3_main_sla"},
    {"champions_nurgle", "wh3_main_nur"},
    {"pestigors_mono", "wh3_main_nur"},
    {"champions_tzeentch", "wh3_main_pro_tze"},
    {"champions_tzeentch", "wh3_main_tze"},
    {"tzaangors_mono", "wh3_main_pro_tze"},
    {"tzaangors_mono", "wh3_main_tze"},
    {"marauder_archers", "wh3_main_sla"},
    {"gnoblar_archers", "wh3_main_ogr"},
    {"gnoblar_swords", "wh3_main_ogr"},
    {"gnoblar_wolves", "wh3_main_ogr"},
    {"bonepickers", "wh3_main_ogr"},
    {"wh3_main_ksl_cav_gryphon_legion_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cav_horse_archers_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cav_horse_raiders_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cav_war_bear_riders_1", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cav_winged_lancers_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_boris_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_boris_1", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_boris_2", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_boyar_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_boyar_1", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_boyar_2", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_frost_maiden_ice_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_frost_maiden_ice_1", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_frost_maiden_ice_2", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_frost_maiden_tempest_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_frost_maiden_tempest_1", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_frost_maiden_tempest_2", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_ice_witch_ice_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_ice_witch_ice_1", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_ice_witch_ice_2", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_ice_witch_tempest_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_ice_witch_tempest_1", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_ice_witch_tempest_2", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_katarin_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_katarin_1", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_katarin_2", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_kostaltyn_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_kostaltyn_1", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_kostaltyn_2", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_patriarch_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_patriarch_1", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_cha_patriarch_2", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_inf_armoured_kossars_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_inf_armoured_kossars_1", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_inf_ice_guard_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_inf_ice_guard_1", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_inf_kossars_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_inf_kossars_1", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_inf_streltsi_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_inf_tzar_guard_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_inf_tzar_guard_1", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_mon_elemental_bear_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_mon_snow_leopard_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_veh_heavy_war_sled_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_veh_light_war_sled_0", "wh3_main_pro_ksl"},
    {"wh3_main_ksl_veh_little_grom_0", "wh3_main_pro_ksl"},
    {"wh3_twa06_ksl_inf_tzar_guard_ror_0", "wh3_main_pro_ksl"},
    {"wh3_twa07_ksl_cav_war_bear_riders_ror_0", "wh3_main_pro_ksl"},
    {"wh3_twa08_ksl_mon_elemental_bear_0_ror", "wh3_main_pro_ksl"},
    {"wh3_twa10_ksl_inf_armoured_kossars_ror", "wh3_main_pro_ksl"},
    {"wh3_dlc20_chs_cav_chaos_chariot_mkho", "wh3_main_pro_kho"},
    {"wh3_dlc20_chs_cav_chaos_knights_mkho_lances", "wh3_main_pro_kho"},
    {"wh3_dlc20_chs_cav_chaos_knights_mkho", "wh3_main_pro_kho"},
    {"wh3_dlc20_chs_cav_marauder_horsemen_mkho_throwing_axes", "wh3_main_pro_kho"},
    {"wh3_dlc20_chs_inf_chaos_marauders_mkho_dualweapons", "wh3_main_pro_kho"},
    {"wh3_dlc20_chs_inf_chaos_marauders_mkho", "wh3_main_pro_kho"},
    {"wh3_dlc20_chs_inf_chosen_mkho_dualweapons", "wh3_main_pro_kho"},
    {"wh3_dlc20_chs_inf_chosen_mkho", "wh3_main_pro_kho"},
    {"wh3_dlc20_chs_inf_forsaken_mkho", "wh3_main_pro_kho"},
    {"wh3_dlc20_chs_mon_warshrine_mkho", "wh3_main_pro_kho"},
    {"wh3_main_kho_cav_bloodcrushers_0", "wh3_main_pro_kho"},
    {"wh3_main_kho_cav_gorebeast_chariot", "wh3_main_pro_kho"},
    {"wh3_main_kho_cav_skullcrushers_0", "wh3_main_pro_kho"},
    {"wh3_main_kho_cha_bloodreaper_0", "wh3_main_pro_kho"},
    {"wh3_main_kho_cha_cultist_0", "wh3_main_pro_kho"},
    {"wh3_main_kho_cha_cultist_1", "wh3_main_pro_kho"},
    {"wh3_main_kho_cha_herald_of_khorne_0", "wh3_main_pro_kho"},
    {"wh3_main_kho_inf_bloodletters_0", "wh3_main_pro_kho"},
    {"wh3_main_kho_inf_bloodletters_1", "wh3_main_pro_kho"},
    {"wh3_main_kho_inf_chaos_furies_0", "wh3_main_pro_kho"},
    {"wh3_main_kho_inf_chaos_warhounds_0", "wh3_main_pro_kho"},
    {"wh3_main_kho_inf_chaos_warriors_0", "wh3_main_pro_kho"},
    {"wh3_main_kho_inf_chaos_warriors_1", "wh3_main_pro_kho"},
    {"wh3_main_kho_inf_chaos_warriors_2", "wh3_main_pro_kho"},
    {"wh3_main_kho_inf_flesh_hounds_of_khorne_0", "wh3_main_pro_kho"},
    {"wh3_main_kho_mon_bloodthirster_0", "wh3_main_pro_kho"},
    {"wh3_main_kho_mon_khornataurs_0", "wh3_main_pro_kho"},
    {"wh3_main_kho_mon_khornataurs_1", "wh3_main_pro_kho"},
    {"wh3_main_kho_mon_soul_grinder_0", "wh3_main_pro_kho"},
    {"wh3_main_kho_mon_spawn_of_khorne_0", "wh3_main_pro_kho"},
    {"wh3_main_kho_veh_blood_shrine_0", "wh3_main_pro_kho"},
    {"wh3_main_kho_veh_skullcannon_0", "wh3_main_pro_kho"},
    {"wh3_twa06_kho_inf_bloodletters_ror_0", "wh3_main_pro_kho"},
    {"wh3_twa07_kho_cav_bloodcrushers_ror_0", "wh3_main_pro_kho"},
    {"wh3_twa08_kho_mon_bloodthirster_0_ror", "wh3_main_pro_kho"},
    {"wh3_twa10_kho_inf_flesh_hounds_of_khorne_ror", "wh3_main_pro_kho"},
    {"wh3_dlc20_chs_cav_chaos_chariot_mtze", "wh3_main_pro_tze"},
    {"wh3_dlc20_chs_cav_chaos_knights_mtze_lances", "wh3_main_pro_tze"},
    {"wh3_dlc20_chs_cav_marauder_horsemen_mtze_javelins", "wh3_main_pro_tze"},
    {"wh3_dlc20_chs_inf_chaos_marauders_mtze_spears", "wh3_main_pro_tze"},
    {"wh3_dlc20_chs_inf_chaos_marauders_mtze", "wh3_main_pro_tze"},
    {"wh3_dlc20_chs_inf_chaos_warriors_mtze_halberds", "wh3_main_pro_tze"},
    {"wh3_dlc20_chs_inf_chaos_warriors_mtze", "wh3_main_pro_tze"},
    {"wh3_dlc20_chs_inf_chosen_mtze_halberds", "wh3_main_pro_tze"},
    {"wh3_dlc20_chs_inf_chosen_mtze", "wh3_main_pro_tze"},
    {"wh3_dlc20_chs_mon_warshrine_mtze", "wh3_main_pro_tze"},
    {"wh3_main_tze_cav_chaos_knights_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_cav_doom_knights_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_cha_cultist_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_cha_cultist_1", "wh3_main_pro_tze"},
    {"wh3_main_tze_cha_exalted_lord_of_change_metal_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_cha_exalted_lord_of_change_tzeentch_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_cha_herald_of_tzeentch_metal_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_cha_herald_of_tzeentch_metal_1", "wh3_main_pro_tze"},
    {"wh3_main_tze_cha_herald_of_tzeentch_metal_2", "wh3_main_pro_tze"},
    {"wh3_main_tze_cha_herald_of_tzeentch_tzeentch_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_cha_herald_of_tzeentch_tzeentch_1", "wh3_main_pro_tze"},
    {"wh3_main_tze_cha_herald_of_tzeentch_tzeentch_2", "wh3_main_pro_tze"},
    {"wh3_main_tze_cha_iridescent_horror_metal_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_cha_iridescent_horror_metal_1", "wh3_main_pro_tze"},
    {"wh3_main_tze_cha_iridescent_horror_metal_2", "wh3_main_pro_tze"},
    {"wh3_main_tze_cha_iridescent_horror_tzeentch_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_cha_iridescent_horror_tzeentch_1", "wh3_main_pro_tze"},
    {"wh3_main_tze_cha_iridescent_horror_tzeentch_2", "wh3_main_pro_tze"},
    {"wh3_main_tze_cha_kairos_fateweaver_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_inf_blue_horrors_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_inf_chaos_furies_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_inf_forsaken_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_inf_pink_horrors_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_inf_pink_horrors_1", "wh3_main_pro_tze"},
    {"wh3_main_tze_mon_exalted_flamers_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_mon_flamers_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_mon_lord_of_change_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_mon_screamers_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_mon_soul_grinder_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_mon_spawn_of_tzeentch_0", "wh3_main_pro_tze"},
    {"wh3_main_tze_veh_burning_chariot_0", "wh3_main_pro_tze"},
    {"wh3_twa06_tze_inf_pink_horrors_ror_0", "wh3_main_pro_tze"},
    {"wh3_twa07_tze_cav_doom_knights_ror_0", "wh3_main_pro_tze"},
    {"wh3_twa08_tze_mon_lord_of_change_0_ror", "wh3_main_pro_tze"},
    {"wh3_twa10_tze_inf_blue_horrors_ror", "wh3_main_pro_tze"},
    {"skegadon", "skeggi"},
    {"kossack_scout", "skeggi"},
    {"caravan_guard", "skeggi"},
    {"skg_knights", "skeggi"},
    {"wh_main_brt_cha_lord_0", "skeggi"},
    {"wh_main_brt_cha_lord_2", "skeggi"},
    {"wh_dlc08_nor_mon_frost_wyrm_ror_0", "skeggi"},
    {"wh_dlc08_nor_mon_war_mammoth_ror_1", "skeggi"},
    {"wh_pro04_nor_inf_chaos_marauders_ror_0", "skeggi"},
    {"wh_pro04_nor_inf_marauder_berserkers_ror_0", "skeggi"},
    {"wh_pro04_nor_mon_fimir_ror_0", "skeggi"},
    {"wh_pro04_nor_mon_marauder_warwolves_ror_0", "skeggi"},
    {"wh_pro04_nor_mon_skinwolves_ror_0", "skeggi"},
    {"wh_pro04_nor_mon_war_mammoth_ror_0", "skeggi"},
    {"wh_dlc08_nor_inf_marauder_champions_0", "chaos_servants"},
    {"wh_dlc08_nor_inf_marauder_hunters_1", "chaos_servants"},
    {"wh_dlc08_nor_mon_fimir_1", "chaos_servants"},
    {"wh_dlc08_nor_mon_fimir_0", "chaos_servants"},
    {"wh_dlc08_nor_inf_marauder_spearman_0", "chaos_servants"},
    {"wh_dlc08_nor_inf_marauder_hunters_0", "chaos_servants"},
    {"wh_dlc08_nor_inf_marauder_champions_1", "chaos_servants"},
    {"wh_main_nor_cha_marauder_chieftan_0", "chaos_servants"},
    {"wh_main_nor_cha_marauder_chieftan_1", "chaos_servants"},
    {"wh_main_nor_cha_marauder_chieftan_2", "chaos_servants"},
    {"wh_main_nor_cha_marauder_chieftan_3", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_lord_10", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_lord_2", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_death_0", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_death_10", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_death_12", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_death_13", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_death_9", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_fire_0", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_fire_10", "chaos_servants"},
    {"bondsmen_spears", "chaos_servants"},
    {"bondsmen", "chaos_servants"},
    {"huscarls", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_fire_12", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_fire_13", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_fire_9", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_metal_0", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_metal_10", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_metal_12", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_metal_13", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_metal_9", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_shadows_0", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_shadows_1", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_shadows_2", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_shadows_3", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_shadows_4", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_shadows_0", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_shadows_1", "chaos_servants"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_shadows_2", "chaos_servants"},
    {"wh_dlc01_chs_cha_exalted_hero_10", "chaos_servants"},
    {"wh_dlc01_chs_inf_chaos_warriors_2", "chaos_servants"},
    {"wh_dlc01_chs_inf_chosen_2", "chaos_servants"},
    {"wh_main_chs_cav_chaos_knights_0", "chaos_servants"},
    {"wh_main_chs_cav_chaos_knights_1", "chaos_servants"},
    {"wh_main_chs_cav_marauder_horsemen_0", "chaos_servants"},
    {"wh_main_chs_cav_marauder_horsemen_1", "chaos_servants"},
    {"wh_main_chs_cha_chaos_lord_0", "chaos_servants"},
    {"wh_main_chs_cha_chaos_lord_11", "chaos_servants"},
    {"wh_main_chs_cha_chaos_lord_12", "chaos_servants"},
    {"wh_main_chs_cha_chaos_sorcerer_death_0", "chaos_servants"},
    {"wh_main_chs_cha_chaos_sorcerer_death_10", "chaos_servants"},
    {"wh_main_chs_cha_chaos_sorcerer_death_11", "chaos_servants"},
    {"wh_main_chs_cha_chaos_sorcerer_fire_0", "chaos_servants"},
    {"wh_main_chs_cha_chaos_sorcerer_fire_10", "chaos_servants"},
    {"wh_main_chs_cha_chaos_sorcerer_fire_11", "chaos_servants"},
    {"wh_main_chs_cha_chaos_sorcerer_metal_0", "chaos_servants"},
    {"wh_main_chs_cha_chaos_sorcerer_metal_10", "chaos_servants"},
    {"wh_main_chs_cha_chaos_sorcerer_metal_11", "chaos_servants"},
    {"wh_main_chs_cha_exalted_hero_0", "chaos_servants"},
    {"wh_main_chs_cha_exalted_hero_12", "chaos_servants"},
    {"wh_main_chs_cha_exalted_hero_13", "chaos_servants"},
    {"wh_main_chs_inf_chaos_marauders_1", "chaos_servants"},
    {"wh_main_chs_inf_chaos_warriors_1", "chaos_servants"},
    {"cultists", "chaos_servants"},
    {"wh_main_chs_inf_chosen_0", "chaos_servants"},
    {"daughters", "chaos_servants"},
    {"wh_main_chs_inf_chosen_1", "chaos_servants"},
    {"wh_dlc03_bst_cha_beastlord_0", "chaos_servants"},
    {"wh_dlc03_bst_cha_beastlord_1", "chaos_servants"},
    {"wh_dlc03_bst_inf_bestigor_herd_0", "chaos_servants"},
    {"wh_dlc03_bst_inf_centigors_0", "chaos_servants"},
    {"wh_dlc03_bst_inf_centigors_1", "chaos_servants"},
    {"wh_dlc03_bst_inf_gor_herd_0", "chaos_servants"},
    {"wh_dlc03_bst_inf_gor_herd_1", "chaos_servants"},
    {"wh_dlc03_bst_inf_minotaurs_0", "chaos_servants"},
    {"wh_dlc03_bst_inf_minotaurs_1", "chaos_servants"},
    {"wh_dlc03_bst_inf_minotaurs_2", "chaos_servants"},
    {"wh_dlc03_bst_inf_ungor_raiders_0", "chaos_servants"},
    {"wh_dlc03_bst_inf_ungor_spearmen_0", "chaos_servants"},
    {"wh_dlc03_bst_mon_chaos_spawn_0", "chaos_servants"},
    {"wh_dlc05_bst_mon_harpies_0", "chaos_servants"},
    {"pestigors", "chaos_servants"},
    {"tzaangors", "chaos_servants"},
    {"slaangors", "chaos_servants"},
    {"khorngors", "chaos_servants"},
    {"wh_dlc01_nor_cha_chaos_sorcerer_lord_0", "chaos_servants"},
    {"wh_dlc01_nor_cha_chaos_sorcerer_lord_1", "chaos_servants"},
    {"wh_dlc08_nor_cav_marauder_horsemasters_0", "chaos_servants"},
    {"wh_dlc08_nor_cha_fimir_balefiend_fire_0", "chaos_servants"},
    {"wh_dlc08_nor_cha_fimir_balefiend_shadow_0", "chaos_servants"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_death_0", "chaos_servants"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_death_1", "chaos_servants"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_death_2", "chaos_servants"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_fire_0", "chaos_servants"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_fire_1", "chaos_servants"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_fire_2", "chaos_servants"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_metal_0", "chaos_servants"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_metal_1", "chaos_servants"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_metal_2", "chaos_servants"},
    {"wh_dlc08_nor_cha_skin_wolf_werekin_0", "chaos_servants"},
    {"wh_dlc08_nor_cha_throgg_0", "chaos_servants"},
    {"wh_dlc08_nor_cha_wulfrik_0", "chaos_servants"},
    {"wh_dlc08_nor_cha_wulfrik_1", "chaos_servants"},
    {"wh_dlc08_nor_cha_wulfrik_2", "chaos_servants"},
    {"wh_dlc08_nor_cha_wulfrik_3", "chaos_servants"},
    {"wh_dlc08_nor_feral_manticore", "chaos_servants"},
    {"wh_dlc08_nor_inf_marauder_berserkers_0", "chaos_servants"},
    {"wh_dlc08_nor_mon_frost_wyrm_0", "chaos_servants"},
    {"wh_dlc08_nor_mon_frost_wyrm_boss", "chaos_servants"},
    {"wh_dlc08_nor_mon_frost_wyrm_ror_0", "chaos_servants"},
    {"wh_dlc08_nor_mon_norscan_giant_0", "chaos_servants"},
    {"wh_dlc08_nor_mon_norscan_ice_trolls_0", "chaos_servants"},
    {"wh_dlc08_nor_mon_skinwolves_0", "chaos_servants"},
    {"wh_dlc08_nor_mon_skinwolves_1", "chaos_servants"},
    {"wh_dlc08_nor_mon_war_mammoth_0", "chaos_servants"},
    {"wh_dlc08_nor_mon_war_mammoth_1", "chaos_servants"},
    {"wh_dlc08_nor_mon_war_mammoth_2", "chaos_servants"},
    {"wh_dlc08_nor_mon_war_mammoth_boss", "chaos_servants"},
    {"wh_dlc08_nor_mon_war_mammoth_ror_1", "chaos_servants"},
    {"wh_dlc08_nor_mon_warwolves_0", "chaos_servants"},
    {"wh_dlc08_nor_veh_marauder_warwolves_chariot_0", "chaos_servants"},
    {"wh_main_nor_cav_chaos_chariot", "chaos_servants"},
    {"wh_main_nor_cav_marauder_horsemen_0", "chaos_servants"},
    {"wh_main_nor_cav_marauder_horsemen_1", "chaos_servants"},
    {"wh_main_nor_cha_chaos_sorcerer_0", "chaos_servants"},
    {"wh_main_nor_cha_chaos_sorcerer_1", "chaos_servants"},
    {"wh_main_nor_inf_chaos_marauders_0", "chaos_servants"},
    {"wh_main_nor_inf_chaos_marauders_1", "chaos_servants"},
    {"wh_main_nor_mon_chaos_trolls", "chaos_servants"},
    {"wh_main_nor_mon_chaos_warhounds_0", "chaos_servants"},
    {"wh_main_nor_mon_chaos_warhounds_1", "chaos_servants"},
    {"wh_main_chs_inf_chaos_marauders_0", "chaos_servants"},
    {"wh_main_chs_inf_chaos_warriors_0", "chaos_servants"},
    {"slaangors", "decadent_host"},
    {"wh_dlc08_nor_cav_marauder_horsemasters_0", "decadent_host"},
    {"wh_dlc08_nor_inf_marauder_berserkers_0", "decadent_host"},
    {"wh_dlc08_nor_inf_marauder_champions_0", "decadent_host"},
    {"wh_dlc08_nor_inf_marauder_champions_1", "decadent_host"},
    {"wh_dlc08_nor_inf_marauder_hunters_0", "decadent_host"},
    {"wh_dlc08_nor_inf_marauder_hunters_1", "decadent_host"},
    {"wh_dlc08_nor_inf_marauder_spearman_0", "decadent_host"},
    {"wh_dlc08_nor_mon_war_mammoth_0", "decadent_host"},
    {"wh_dlc08_nor_mon_war_mammoth_1", "decadent_host"},
    {"wh_main_nor_cha_marauder_chieftan_0", "decadent_host"},
    {"wh_main_nor_cha_marauder_chieftan_1", "decadent_host"},
    {"wh_main_nor_cha_marauder_chieftan_2", "decadent_host"},
    {"wh_main_nor_cha_marauder_chieftan_3", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_lord_10", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_lord_2", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_death_0", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_death_10", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_death_12", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_death_13", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_death_9", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_fire_0", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_fire_10", "decadent_host"},
    {"hunters", "decadent_host"},
    {"bondsmen_spears", "decadent_host"},
    {"bondsmen", "decadent_host"},
    {"huscarls", "decadent_host"},
    {"wildkin", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_fire_12", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_fire_13", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_fire_9", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_metal_0", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_metal_10", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_metal_12", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_metal_13", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_metal_9", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_shadows_0", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_shadows_1", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_shadows_2", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_shadows_3", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_lord_shadows_4", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_shadows_0", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_shadows_1", "decadent_host"},
    {"wh_dlc01_chs_cha_chaos_sorcerer_shadows_2", "decadent_host"},
    {"wh_dlc01_chs_cha_exalted_hero_10", "decadent_host"},
    {"wh_dlc01_chs_cha_prince_sigvald_the_magnificent", "decadent_host"},
    {"wh_dlc01_chs_inf_chaos_warriors_2", "decadent_host"},
    {"wh_dlc01_chs_inf_chosen_2", "decadent_host"},
    {"wh_dlc01_chs_mon_dragon_ogre", "decadent_host"},
    {"wh_main_chs_cav_chaos_knights_0", "decadent_host"},
    {"wh_main_chs_cav_chaos_knights_1", "decadent_host"},
    {"wh_main_chs_cav_marauder_horsemen_0", "decadent_host"},
    {"wh_main_chs_cav_marauder_horsemen_1", "decadent_host"},
    {"wh_main_chs_cha_chaos_lord_0", "decadent_host"},
    {"wh_main_chs_cha_chaos_lord_11", "decadent_host"},
    {"wh_main_chs_cha_chaos_lord_12", "decadent_host"},
    {"wh_main_chs_cha_chaos_sorcerer_death_0", "decadent_host"},
    {"wh_main_chs_cha_chaos_sorcerer_death_10", "decadent_host"},
    {"wh_main_chs_cha_chaos_sorcerer_death_11", "decadent_host"},
    {"wh_main_chs_cha_chaos_sorcerer_fire_0", "decadent_host"},
    {"wh_main_chs_cha_chaos_sorcerer_fire_10", "decadent_host"},
    {"wh_main_chs_cha_chaos_sorcerer_fire_11", "decadent_host"},
    {"wh_main_chs_cha_chaos_sorcerer_metal_0", "decadent_host"},
    {"wh_main_chs_cha_chaos_sorcerer_metal_10", "decadent_host"},
    {"wh_main_chs_cha_chaos_sorcerer_metal_11", "decadent_host"},
    {"wh_main_chs_cha_exalted_hero_0", "decadent_host"},
    {"wh_main_chs_cha_exalted_hero_12", "decadent_host"},
    {"wh_main_chs_cha_exalted_hero_13", "decadent_host"},
    {"wh_main_chs_inf_chaos_marauders_0", "decadent_host"},
    {"wh_main_chs_inf_chaos_marauders_1", "decadent_host"},
    {"wh_main_chs_inf_chaos_warriors_1", "decadent_host"},
    {"cultists", "decadent_host"},
    {"wh_main_chs_inf_chosen_0", "decadent_host"},
    {"wh_pro04_chs_inf_chaos_warriors_ror_0", "decadent_host"},
    {"wh_dlc08_nor_veh_marauder_warwolves_chariot_0", "decadent_host"},
    {"wh_main_chs_art_hellcannon", "decadent_host"},
    {"daughters", "decadent_host"},
    {"wh_main_chs_inf_chosen_1", "decadent_host"},
    {"wh_main_chs_mon_chaos_warhounds_1", "decadent_host"},
    {"wh_main_chs_mon_chaos_warhounds_0", "decadent_host"},
    {"wh_dlc08_nor_mon_frost_wyrm_0", "decadent_host"},
    {"wh_dlc01_chs_mon_dragon_ogre_shaggoth", "decadent_host"},
    {"wh_main_chs_mon_giant", "decadent_host"},
    {"wh_main_chs_mon_trolls", "skeggi"},
    {"terradon_horde", "skeggi"},
    {"kroxigor_thralls", "skeggi"},
    {"skeggi_dogs", "skeggi"},
    {"spear_karls", "skeggi"},
    {"karls", "skeggi"},
    {"frontiersmen", "skeggi"},
    {"warmbloods", "skeggi"},
    {"skeggi_coldones", "skeggi"},
    {"carnosaur", "skeggi"},
    {"kulspearmen", "skeggi"},
    {"wh2_dlc12_lzd_mon_salamander_pack_0", "skeggi"},
    {"skeggi_hounds", "skeggi"},
    {"trappers", "skeggi"},
    {"second_sons", "skeggi"},
    {"skeggi_ogre", "skeggi"},
    {"vanguard", "skeggi"},
    {"hofkarls", "skeggi"},
    {"wh2_main_lzd_mon_stegadon_0", "skeggi"},
    {"wh2_main_lzd_mon_bastiladon_0", "skeggi"},
    {"wh2_dlc13_lzd_mon_razordon_pack_0", "skeggi"},
    {"wh_dlc08_nor_inf_marauder_hunters_1", "skeggi"},
    {"skink_thralls", "skeggi"},
    {"kulmen", "skeggi"},
    {"sotek_shield", "skeggi"},
    {"sotek_picks", "skeggi"},
    {"slavers", "skeggi"},
    {"losteriksson", "skeggi"},
    {"wh_main_nor_cha_marauder_chieftan_0", "skeggi"},
    {"wh_main_nor_cha_marauder_chieftan_1", "skeggi"},
    {"wh_main_nor_cha_marauder_chieftan_2", "skeggi"},
    {"wh_main_nor_cha_marauder_chieftan_3", "skeggi"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_death_0", "skeggi"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_death_1", "skeggi"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_death_2", "skeggi"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_fire_0", "skeggi"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_fire_1", "skeggi"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_fire_2", "skeggi"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_metal_0", "skeggi"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_metal_1", "skeggi"},
    {"wh_dlc08_nor_cha_shaman_sorcerer_metal_2", "skeggi"},
    {"wh_dlc08_nor_cha_skin_wolf_werekin_0", "skeggi"},
    {"wh_dlc08_nor_feral_manticore", "skeggi"},
    {"wh_dlc08_nor_mon_skinwolves_0", "skeggi"},
    {"wh_dlc03_emp_cha_wizard_beasts_0", "skeggi"},
    {"wh_dlc03_emp_cha_wizard_beasts_1", "skeggi"},
    {"wh_dlc03_emp_cha_wizard_beasts_2", "skeggi"},
    {"wh_dlc03_emp_cha_wizard_beasts_3", "skeggi"},
    {"wh_dlc03_emp_cha_wizard_beasts_4", "skeggi"},
    {"wh_dlc05_emp_cha_wizard_life_0", "skeggi"},
    {"wh_dlc05_emp_cha_wizard_life_1", "skeggi"},
    {"wh_dlc05_emp_cha_wizard_life_2", "skeggi"},
    {"wh_dlc05_emp_cha_wizard_life_3", "skeggi"},
    {"wh_main_emp_cha_captain_0", "skeggi"},
    {"wh_main_emp_cha_captain_1", "skeggi"},
    {"skeggi_bret", "skeggi"},
    {"wh_main_emp_cha_captain_2", "skeggi"},
    {"wh_main_emp_cha_captain_3", "skeggi"},
    {"skg_war_wagon", "skeggi"},
    {"hofkarl_mounted", "skeggi"}
}

modded_unit_to_category ={
    ["chaos_dragon"] = "inf_melee",
    ["lord_of_change"] = "inf_melee",
    ["wyvern"] = "war_beast",
    ["red_guard"] = "inf_melee",
    ["deathvermin"] = "inf_melee",
    ["forest_goblins"] = "inf_melee",
    ["forest_goblins_bow"] = "inf_ranged",
    ["imperial_foot"] = "inf_melee",
    ["imperial_zombie"] = "inf_melee",
    ["trident_knight"] = "inf_melee",
    ["reiksguard_foot"] = "inf_melee",
    ["bonebreaker"] = "inf_melee",
    ["spear_boyz"] = "inf_melee",
    ["billmen"] = "inf_melee",
    ["sergeants"] = "inf_melee",
    ["squires"] = "inf_melee",
    ["rangers_shotgun"] = "inf_ranged",
    ["rangers"] = "inf_ranged",
    ["mounted_squires"] = "cavalry",
    ["hofkarl_mounted"] = "cavalry",
    ["dead_squires"] = "cavalry",
    ["shieldbreakers_human"] = "inf_melee",
    ["sotek_shield"] = "inf_melee",
    ["shieldbreakers"] = "inf_melee",
    ["big_uns_spearz"] = "inf_melee",
    ["black_bear"] = "cavalry",
    ["gigantic_spiders"] = "inf_melee",
    ["tzaangors"] = "inf_melee",
    ["slaangors"] = "inf_melee",
    ["pestigors"] = "inf_melee",
    ["khorngors"] = "inf_melee",
    ["glade_riders"] = "cavalry",
    ["grave_spears"] = "inf_melee",
    ["elven_warriors"] = "inf_melee",
    ["elf_pirates"] = "inf_melee",
    ["warriors"] = "inf_melee",
    ["unholy_pilgrims"] = "inf_melee",
    ["z_flag"] = "inf_melee",
    ["brtzombie"] = "inf_melee",
    ["brtzombieknight"] = "inf_melee",
    ["blackguard"] = "inf_melee",
    ["sun_dragon_small"] = "inf_melee",
    ["huscarls_ghost"] = "inf_melee",
    ["huscarls"] = "inf_melee",
    ["reaver"] = "inf_melee",
    ["bondsmen"] = "inf_melee",
    ["arbalists"] = "inf_ranged",
    ["chevaliers"] = "inf_melee",
    ["dismounted_knights"] = "inf_melee",
    ["cultists"] = "inf_melee",
    ["cultists_spawn"] = "inf_melee",
    ["hunters"] = "inf_ranged",
    ["slaanesh_warriors"] = "inf_melee",
    ["daughters"] = "inf_melee",
    ["khaine_spears"] = "inf_melee",
    ["creeping_dread"] = "inf_ranged",
    ["freed_monster"] = "inf_melee",
    ["fervid_fang"] = "inf_melee",
    ["scouts"] = "inf_ranged",
    ["templars"] = "inf_melee",
    ["white_wolf"] = "cavalry",
    ["colossal_squig"] = "inf_melee",
    ["war_hawks"] = "inf_melee",
    ["shield_merc"] = "cavalry",
    ["out_scout"] = "cavalry",
    ["steelbeards"] = "inf_ranged",
    ["runic_guardian"] = "inf_melee",
    ["vengeance_copter"] = "inf_melee",
    ["w_boyz"] = "inf_melee",
    ["eshin_hand"] = "inf_melee",
    ["hand_eshin"] = "inf_melee",
    ["nag_guard"] = "inf_melee",
    ["nuln_ironsides"] = "inf_ranged",
    ["talsyn_hawks"] = "inf_ranged",
    ["wildkin"] = "war_beast",
    ["picks"] = "inf_melee",
    ["true_king"] = "inf_melee",
    ["crows_nest_zombie"] = "inf_ranged",
    ["crows_nest"] = "inf_ranged",
    ["sailors"] = "inf_melee",
    ["trident_pegasus"] = "cavalry",
    ["marines"] = "inf_ranged",
    ["boarders"] = "inf_ranged",
    ["deck_clearers"] = "inf_ranged",
    ["grail_pilgrims"] = "inf_melee",
    ["chevalier_cavalry"] = "cavalry",
    ["couronne_knights"] = "cavalry",
    ["free_company_axemen"] = "inf_melee",
    ["free_company_spears"] = "inf_melee",
    ["heavy_goblins"] = "inf_melee",
    ["kadon_eagle"] = "inf_melee",
    ["slaanesh_marauders"] = "inf_melee",
    ["storm_wardens"] = "inf_melee",
    ["grim_rangers"] = "inf_ranged",
    ["damned_knights"] = "inf_melee",
    ["sylvanian_levy"] = "inf_melee",
    ["poxvermin"] = "inf_melee",
    ["cold_riders"] = "cavalry",
    ["tyrant_blades"] = "cavalry",
    ["longshanks"] = "inf_ranged",
    ["slavers"] = "inf_melee",
    ["kulmen"] = "inf_melee",
    ["kulspearmen"] = "inf_melee",
    ["carnosaur"] = "inf_melee",
    ["skink_thralls"] = "inf_ranged",
    ["warmbloods"] = "inf_ranged",
    ["frontiersmen"] = "inf_ranged",
    ["karls"] = "cavalry",
    ["spear_karls"] = "inf_melee",
    ["hofkarls"] = "inf_melee",
    ["second_sons"] = "inf_melee",
    ["hunting_dogs"] = "inf_melee",
    ["skeggi_dogs"] = "inf_melee",
    ["skeggi_hounds"] = "inf_melee",
    ["vanguard"] = "inf_ranged",
    ["trappers"] = "inf_ranged",
    ["kroxigor_thralls"] = "inf_melee",
    ["terradon_horde"] = "inf_melee",
    ["skeggi_trolls"] = "inf_melee",
    ["losteriksson"] = "inf_melee",
    ["ghorst_corpse"] = "inf_melee",
    ["engineers_imp"] = "inf_ranged",
    ["red_host"] = "inf_melee",
    ["skeg_berserk"] = "inf_melee",
    ["bondsmen_spears"] = "inf_melee",
    ["skg_war_wagon"] = "war_machine",
    ["skeleton_horsemen"] = "cavalry",
    ["sotek_picks"] = "inf_melee",
    ["necromancer_group"] = "inf_melee",
    ["scholars"] = "inf_melee",
    ["nordlander"] = "inf_melee",
    ["knights_caledor"] = "inf_melee",
    ["skryre_rat"] = "inf_melee",
    ["chrace_cav"] = "cavalry",
    ["shadow_melee"] = "inf_melee",
    ["skeggi_bret"] = "inf_melee",
    ["ogre_dead"] = "inf_ranged",
    ["skeggi_ogre"] = "inf_ranged",
    ["doomed_legion"] = "inf_melee",
    ["zombo_dragon"] = "inf_melee",
    ["shriceratops"] = "war_beast",
    ["skegadon"] = "war_beast",
    ["marauder_halberds"] = "inf_melee",
    ["smiths"] = "inf_melee",
    ["huscarls_old"] = "inf_melee",
    ["skg_knights"] = "cavalry",
    ["kul_bows"] = "cavalry",
    ["captains_altdorf"] = "war_beast",
    ["cart_raise"] = "inf_melee",
    ["wh2_dlc16_wef_inf_malicious_dryads_0_dry"] = "inf_melee",
    ["wh2_twa05_ogr_inf_maneaters_sartosa"] = "inf_ranged",
    ["cst_skele"] = "inf_melee",
    ["skele_coast_cst"] = "inf_melee",
    ["kossar_bardiche"] = "inf_melee",
    ["jade_axemen"] = "inf_melee",
    ["marauder_archers"] = "inf_melee",
    ["nurglings_weasel"] = "inf_melee",
    ["bastion_guns"] = "inf_ranged",
    ["bonepickers"] = "inf_melee",
    ["gnoblar_archers"] = "inf_ranged",
    ["gnoblar_swords"] = "inf_melee",
    ["gnoblar_wolves"] = "cavalry",
    ["daemon_undivided"] = "inf_melee",
    ["woodsmen"] = "inf_melee",
    ["kossar_sword"] = "inf_melee",
    ["cathay_mace_peasant"] = "inf_melee",
    ["red_crested_cohort"] = "inf_ranged",
    ["repeater_crossbows"] = "inf_ranged",
    ["fire_hail"] = "inf_ranged",
    ["druzhina"] = "war_beast",
    ["celestial_riders"] = "war_beast",
    ["swiftwings"] = "cavalry",
    ["dismounted_gryphon"] = "inf_ranged",
    ["jade_archers"] = "inf_ranged",
    ["yin_spears"] = "inf_melee",
    ["tomb_horsemen"] = "cavalry",
    ["nehek_bowmen"] = "inf_ranged",
    ["nehek_axe"] = "inf_melee",
    ["zombie_horde"] = "inf_melee",
    ["fireglaive_warriors"] = "inf_ranged",
    ["firelancers"] = "war_beast",
    ["caravan_guard"] = "inf_ranged",
    ["kossack_scout"] = "cavalry",
    ["champions_slaanesh"] = "inf_melee",
    ["champions_tzeentch"] = "inf_melee",
    ["champions_nurgle"] = "inf_melee",
    ["champions_khorne"] = "inf_melee",
    ["yuan_dao"] = "inf_melee",
    ["sons_of_bretonnia"] = "cavalry",
    ["bill_zel"] = "inf_melee",
    ["cst_ghoul"] = "inf_melee",
    ["rangers_grenades"] = "inf_ranged",
}
modded_unit_to_military_groups = {}
for _, unit_to_group in pairs(modded_units_to_military_group) do
    print("Adding: "..tostring(unit_to_group[1])..':'..tostring(unit_to_group[2]))
    if not modded_unit_to_military_groups[unit_to_group[1]] then
        modded_unit_to_military_groups[unit_to_group[1]] = string.format('"%s"', unit_to_group[2])
    else
        modded_unit_to_military_groups[unit_to_group[1]] = string.format('%s,"%s"', 
        modded_unit_to_military_groups[unit_to_group[1]], unit_to_group[2])
    end
end

function get_cost(group, weight)
    if group == 'core' then
        return 10 * weight
    elseif group == 'special' then
        return 50 + (15 * weight)
    else
        return 100 + (20 * weight)
    end
end

file = io.open("output/modded_mercs_input.lua", "w")
io.output(file)

io.write("\n# Add the mercenary to pttg in your script: \n")
io.write("local mercenaries = {\n")
for _, mercenary in pairs(modded_units) do
    print("Processing: "..mercenary[1])
    io.write(string.format('\t{\
        key = "%s",\
        military_groupings = {%s},\
        category = "%s",\
        group = "%s",\
        weight = %s,\
        tier = nil,\
        cost = 2,\
        ritual = {\
            key = "pttg_ritual_%s",\
            glory_cost = %s,\
        },\
    },\n', mercenary[1], modded_unit_to_military_groups[mercenary[1]], modded_unit_to_category[mercenary[1]], mercenary[2], mercenary[3], mercenary[1], get_cost(mercenary[2], mercenary[3] or 2)
    ))
end
io.write("}\n")

