local mercenaries = {
	{
        key = "forest_goblins",
        military_groupings = {"wh_main_group_savage_orcs","wh_main_group_greenskins",},
        category = "inf_melee",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 1,
        ritual = {
            key = "pttg_ritual_forest_goblins",
            glory_cost = 20,
        },
    },
	{
        key = "wyvern",
        military_groupings = {"wh_main_group_savage_orcs","wh_main_group_greenskins",},
        category = "war_beast",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_wyvern",
            glory_cost = 80,
        },
    },
	{
        key = "chaos_dragon",
        military_groupings = {"wh_main_group_chaos",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_chaos_dragon",
            glory_cost = 120,
        },
    },
	{
        key = "red_guard",
        military_groupings = {"wh2_main_skv",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_red_guard",
            glory_cost = 120,
        },
    },
	{
        key = "deathvermin",
        military_groupings = {"wh2_main_skv",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_deathvermin",
            glory_cost = 120,
        },
    },
	{
        key = "forest_goblins_bow",
        military_groupings = {"wh_main_group_savage_orcs","wh_main_group_greenskins",},
        category = "inf_ranged",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 1,
        ritual = {
            key = "pttg_ritual_forest_goblins_bow",
            glory_cost = 20,
        },
    },
	{
        key = "shieldbreakers_human",
        military_groupings = {"wh_main_group_dwarfs",},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_shieldbreakers_human",
            glory_cost = 80,
        },
    },
	{
        key = "imperial_foot",
        military_groupings = {"wh_main_group_empire","wh_main_group_empire_reikland",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_imperial_foot",
            glory_cost = 120,
        },
    },
	{
        key = "imperial_zombie",
        military_groupings = {"wh_main_vmp_vampire_counts","wh_main_vmp_schwartzhafen",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_imperial_zombie",
            glory_cost = 120,
        },
    },
	{
        key = "trident_knight",
        military_groupings = {"wh_main_brt_bordeleaux",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_trident_knight",
            glory_cost = 120,
        },
    },
	{
        key = "reiksguard_foot",
        military_groupings = {"wh_main_group_empire","wh_main_group_empire_reikland",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_reiksguard_foot",
            glory_cost = 120,
        },
    },
	{
        key = "bonebreaker",
        military_groupings = {"wh2_main_skv",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_bonebreaker",
            glory_cost = 120,
        },
    },
	{
        key = "spear_boyz",
        military_groupings = {"wh_main_group_greenskins",},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_spear_boyz",
            glory_cost = 20,
        },
    },
	{
        key = "billmen",
        military_groupings = {"wh_main_group_bretonnia",},
        category = "inf_melee",
        group = "core",
        weight = 3,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_billmen",
            glory_cost = 20,
        },
    },
	{
        key = "sergeants",
        military_groupings = {"wh_main_group_bretonnia",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_sergeants",
            glory_cost = 65,
        },
    },
	{
        key = "squires",
        military_groupings = {"wh_main_group_bretonnia",},
        category = "inf_melee",
        group = "core",
        weight = 3,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_squires",
            glory_cost = 20,
        },
    },
	{
        key = "rangers_shotgun",
        military_groupings = {"wh_main_group_dwarfs",},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_rangers_shotgun",
            glory_cost = 65,
        },
    },
	{
        key = "rangers",
        military_groupings = {"wh_main_group_dwarfs",},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_rangers",
            glory_cost = 65,
        },
    },
	{
        key = "mounted_squires",
        military_groupings = {"wh_main_group_bretonnia",},
        category = "cavalry",
        group = "core",
        weight = 3,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_mounted_squires",
            glory_cost = 20,
        },
    },
	{
        key = "dead_squires",
        military_groupings = {"wh2_dlc11_vmp_the_barrow_legion",},
        category = "cavalry",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_dead_squires",
            glory_cost = 65,
        },
    },
	{
        key = "shieldbreakers",
        military_groupings = {"wh_main_group_dwarfs",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_shieldbreakers",
            glory_cost = 65,
        },
    },
	{
        key = "big_uns_spearz",
        military_groupings = {"wh_main_group_greenskins","wh_main_group_savage_orcs",},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_big_uns_spearz",
            glory_cost = 20,
        },
    },
	{
        key = "black_bear",
        military_groupings = {"wh_main_group_empire","wh_main_group_empire_reikland",},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_black_bear",
            glory_cost = 120,
        },
    },
	{
        key = "gigantic_spiders",
        military_groupings = {"wh_main_group_greenskins","wh_main_group_savage_orcs",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_gigantic_spiders",
            glory_cost = 65,
        },
    },
	{
        key = "TKzombie",
        military_groupings = {"wh2_dlc09_tomb_kings_arkhan",},
        category = "inf_melee",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 0,
        ritual = {
            key = "pttg_ritual_TKzombie",
            glory_cost = 20,
        },
    },
	{
        key = "pestigors",
        military_groupings = {"wh_dlc03_group_beastmen","chaos_servants",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_pestigors",
            glory_cost = 65,
        },
    },
	{
        key = "pestigors_mono",
        military_groupings = {"wh3_main_nur",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_pestigors_mono",
            glory_cost = 120,
        },
    },
	{
        key = "tzaangors",
        military_groupings = {"wh_dlc03_group_beastmen","chaos_servants",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_tzaangors",
            glory_cost = 65,
        },
    },
	{
        key = "tzaangors_mono",
        military_groupings = {"wh3_main_pro_tze","wh3_main_tze",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_tzaangors_mono",
            glory_cost = 120,
        },
    },
	{
        key = "slaangors",
        military_groupings = {"wh_dlc03_group_beastmen","chaos_servants","decadent_host",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_slaangors",
            glory_cost = 65,
        },
    },
	{
        key = "slaangors_mono",
        military_groupings = {"wh3_main_sla",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_slaangors_mono",
            glory_cost = 120,
        },
    },
	{
        key = "khorngors",
        military_groupings = {"wh_dlc03_group_beastmen","chaos_servants",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_khorngors",
            glory_cost = 65,
        },
    },
	{
        key = "khorngors_mono",
        military_groupings = {"wh3_main_pro_kho","wh3_main_kho",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_khorngors_mono",
            glory_cost = 120,
        },
    },
	{
        key = "glade_riders",
        military_groupings = {"wh_dlc05_group_wood_elves",},
        category = "cavalry",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_glade_riders",
            glory_cost = 20,
        },
    },
	{
        key = "grave_spears",
        military_groupings = {"wh_main_group_vampire_counts",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_grave_spears",
            glory_cost = 120,
        },
    },
	{
        key = "elven_warriors",
        military_groupings = {"wh2_main_hef",},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_elven_warriors",
            glory_cost = 20,
        },
    },
	{
        key = "elf_pirates",
        military_groupings = {"wh2_dlc11_cst_pirates_of_sartosa",},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_elf_pirates",
            glory_cost = 80,
        },
    },
	{
        key = "warriors",
        military_groupings = {"wh_dlc05_group_wood_elves",},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_warriors",
            glory_cost = 20,
        },
    },
	{
        key = "unholy_pilgrims",
        military_groupings = {"wh2_dlc11_vmp_the_barrow_legion",},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_unholy_pilgrims",
            glory_cost = 20,
        },
    },
	{
        key = "brtzombie",
        military_groupings = {"wh2_dlc11_vmp_the_barrow_legion",},
        category = "inf_melee",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 0,
        ritual = {
            key = "pttg_ritual_brtzombie",
            glory_cost = 20,
        },
    },
	{
        key = "brtzombieknight",
        military_groupings = {"wh2_dlc11_vmp_the_barrow_legion",},
        category = "inf_melee",
        group = "rare",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_brtzombieknight",
            glory_cost = 120,
        },
    },
	{
        key = "blackguard",
        military_groupings = {"wh2_main_def",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_blackguard",
            glory_cost = 120,
        },
    },
	{
        key = "huscarls",
        military_groupings = {"wh_main_group_norsca","chaos_servants","decadent_host",},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_huscarls",
            glory_cost = 80,
        },
    },
	{
        key = "reaver",
        military_groupings = {"wh_dlc08_nor_norsca",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_reaver",
            glory_cost = 120,
        },
    },
	{
        key = "bondsmen",
        military_groupings = {"wh_main_group_norsca","chaos_servants","decadent_host",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_bondsmen",
            glory_cost = 65,
        },
    },
	{
        key = "bondsmen_spears",
        military_groupings = {"wh_main_group_norsca","chaos_servants","decadent_host",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_bondsmen_spears",
            glory_cost = 65,
        },
    },
	{
        key = "arbalists",
        military_groupings = {"wh_main_group_bretonnia",},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_arbalists",
            glory_cost = 65,
        },
    },
	{
        key = "chevaliers",
        military_groupings = {"wh2_dlc14_brt_chevaliers_de_lyonesse",},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_chevaliers",
            glory_cost = 80,
        },
    },
	{
        key = "dismounted_knights",
        military_groupings = {"wh_main_group_bretonnia",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_dismounted_knights",
            glory_cost = 120,
        },
    },
	{
        key = "cultists",
        military_groupings = {"wh_main_group_chaos","chaos_servants","decadent_host",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_cultists",
            glory_cost = 65,
        },
    },
	{
        key = "hunters",
        military_groupings = {"wh_main_group_norsca","decadent_host",},
        category = "inf_ranged",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_hunters",
            glory_cost = 20,
        },
    },
	{
        key = "slaanesh_warriors",
        military_groupings = {"wh2_main_def_cult_of_pleasure",},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_slaanesh_warriors",
            glory_cost = 80,
        },
    },
	{
        key = "daughters",
        military_groupings = {"wh_main_group_chaos","chaos_servants","decadent_host",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_daughters",
            glory_cost = 120,
        },
    },
	{
        key = "khaine_spears",
        military_groupings = {"wh2_main_def_har_ganeth",},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_khaine_spears",
            glory_cost = 80,
        },
    },
	{
        key = "creeping_dread",
        military_groupings = {"wh2_main_def",},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_creeping_dread",
            glory_cost = 120,
        },
    },
	{
        key = "fervid_fang",
        military_groupings = {"wh2_main_skv",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_fervid_fang",
            glory_cost = 120,
        },
    },
	{
        key = "scouts",
        military_groupings = {"wh_main_group_empire","wh_main_group_empire_reikland",},
        category = "inf_ranged",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_scouts",
            glory_cost = 80,
        },
    },
	{
        key = "templars",
        military_groupings = {"wh_main_emp_middenland",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_templars",
            glory_cost = 120,
        },
    },
	{
        key = "white_wolf",
        military_groupings = {"wh_main_emp_middenland",},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_white_wolf",
            glory_cost = 120,
        },
    },
	{
        key = "colossal_squig",
        military_groupings = {"wh_main_grn_crooked_moon",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_colossal_squig",
            glory_cost = 120,
        },
    },
	{
        key = "war_hawks",
        military_groupings = {"wh_dlc05_group_wood_elves",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_war_hawks",
            glory_cost = 65,
        },
    },
	{
        key = "shield_merc",
        military_groupings = {"wh_main_group_dwarfs",},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_shield_merc",
            glory_cost = 120,
        },
    },
	{
        key = "out_scout",
        military_groupings = {"wh_main_group_empire","wh_main_group_empire_reikland",},
        category = "cavalry",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_out_scout",
            glory_cost = 65,
        },
    },
	{
        key = "steelbeards",
        military_groupings = {"wh2_dlc17_dwf_thorek_ironbrow",},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_steelbeards",
            glory_cost = 120,
        },
    },
	{
        key = "runic_guardian",
        military_groupings = {"wh_main_group_dwarfs",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_runic_guardian",
            glory_cost = 120,
        },
    },
	{
        key = "vengeance_copter",
        military_groupings = {"wh_main_group_dwarfs",},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_vengeance_copter",
            glory_cost = 80,
        },
    },
	{
        key = "w_boyz",
        military_groupings = {"wh_main_grn_orcs_of_the_bloody_hand",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_w_boyz",
            glory_cost = 120,
        },
    },
	{
        key = "eshin_hand",
        military_groupings = {"wh2_main_skv",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_eshin_hand",
            glory_cost = 120,
        },
    },
	{
        key = "nag_guard",
        military_groupings = {"wh2_dlc09_tmb_followers_of_nagash",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_nag_guard",
            glory_cost = 120,
        },
    },
	{
        key = "nuln_ironsides",
        military_groupings = {"wh_main_group_empire","wh_main_group_empire_reikland",},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_nuln_ironsides",
            glory_cost = 120,
        },
    },
	{
        key = "talsyn_hawks",
        military_groupings = {"wh_dlc05_wef_wood_elves","wh2_main_hef_avelorn",},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_talsyn_hawks",
            glory_cost = 120,
        },
    },
	{
        key = "wildkin",
        military_groupings = {"wh_main_group_norsca","decadent_host",},
        category = "war_beast",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_wildkin",
            glory_cost = 65,
        },
    },
	{
        key = "crows_nest_zombie",
        military_groupings = {"wh2_dlc11_cst_noctilus","wh2_dlc11_cst_the_drowned","wh2_dlc11_cst_vampire_coast",},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_crows_nest_zombie",
            glory_cost = 120,
        },
    },
	{
        key = "crows_nest",
        military_groupings = {"wh2_dlc11_cst_pirates_of_sartosa",},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_crows_nest",
            glory_cost = 120,
        },
    },
	{
        key = "picks",
        military_groupings = {"wh_main_dwf_karak_kadrin",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_picks",
            glory_cost = 120,
        },
    },
	{
        key = "true_king",
        military_groupings = {"wh_main_dwf_karak_izor",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_true_king",
            glory_cost = 120,
        },
    },
	{
        key = "sailors",
        military_groupings = {"wh_main_brt_bordeleaux",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_sailors",
            glory_cost = 65,
        },
    },
	{
        key = "trident_pegasus",
        military_groupings = {"wh_main_brt_bordeleaux",},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_trident_pegasus",
            glory_cost = 120,
        },
    },
	{
        key = "marines",
        military_groupings = {"wh_main_brt_bordeleaux",},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_marines",
            glory_cost = 65,
        },
    },
	{
        key = "boarders",
        military_groupings = {"wh2_dlc11_cst_pirates_of_sartosa",},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_boarders",
            glory_cost = 65,
        },
    },
	{
        key = "deck_clearers",
        military_groupings = {"wh2_dlc11_cst_pirates_of_sartosa",},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_deck_clearers",
            glory_cost = 120,
        },
    },
	{
        key = "grail_pilgrims",
        military_groupings = {"wh_main_brt_carcassonne",},
        category = "inf_melee",
        group = "core",
        weight = 3,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_grail_pilgrims",
            glory_cost = 20,
        },
    },
	{
        key = "chevalier_cavalry",
        military_groupings = {"wh2_dlc14_brt_chevaliers_de_lyonesse",},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_chevalier_cavalry",
            glory_cost = 120,
        },
    },
	{
        key = "couronne_knights",
        military_groupings = {"wh_main_brt_bretonnia",},
        category = "cavalry",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_couronne_knights",
            glory_cost = 80,
        },
    },
	{
        key = "free_company_axemen",
        military_groupings = {"wh_main_group_empire","wh_main_group_empire_reikland",},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_free_company_axemen",
            glory_cost = 20,
        },
    },
	{
        key = "free_company_spears",
        military_groupings = {"wh_main_group_empire","wh_main_group_empire_reikland",},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_free_company_spears",
            glory_cost = 20,
        },
    },
	{
        key = "heavy_goblins",
        military_groupings = {"wh2_dlc15_grn_broken_axe","wh_main_grn_crooked_moon",},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_heavy_goblins",
            glory_cost = 80,
        },
    },
	{
        key = "slaanesh_marauders",
        military_groupings = {"wh2_main_def_cult_of_pleasure",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_slaanesh_marauders",
            glory_cost = 65,
        },
    },
	{
        key = "storm_wardens",
        military_groupings = {"wh_main_dwf_barak_varr","wh_main_dwf_dwarfs",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_storm_wardens",
            glory_cost = 120,
        },
    },
	{
        key = "grim_rangers",
        military_groupings = {"wh2_main_hef_yvresse",},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_grim_rangers",
            glory_cost = 65,
        },
    },
	{
        key = "damned_knights",
        military_groupings = {"wh2_dlc11_cst_the_drowned",},
        category = "inf_melee",
        group = "special",
        weight = 3,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_damned_knights",
            glory_cost = 95,
        },
    },
	{
        key = "sylvanian_levy",
        military_groupings = {"wh_main_vmp_schwartzhafen",},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_sylvanian_levy",
            glory_cost = 20,
        },
    },
	{
        key = "poxvermin",
        military_groupings = {"wh2_main_skv_clan_pestilens",},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_poxvermin",
            glory_cost = 80,
        },
    },
	{
        key = "cold_riders",
        military_groupings = {"wh2_main_def_hag_graef",},
        category = "cavalry",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_cold_riders",
            glory_cost = 65,
        },
    },
	{
        key = "tyrant_blades",
        military_groupings = {"wh2_main_def_hag_graef",},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_tyrant_blades",
            glory_cost = 120,
        },
    },
	{
        key = "longshanks",
        military_groupings = {"wh_main_group_empire",},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_longshanks",
            glory_cost = 120,
        },
    },
	{
        key = "kulmen",
        military_groupings = {"skeggi",},
        category = "inf_melee",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_kulmen",
            glory_cost = 20,
        },
    },
	{
        key = "slavers",
        military_groupings = {"skeggi",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_slavers",
            glory_cost = 65,
        },
    },
	{
        key = "kulspearmen",
        military_groupings = {"skeggi",},
        category = "inf_melee",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_kulspearmen",
            glory_cost = 20,
        },
    },
	{
        key = "carnosaur",
        military_groupings = {"skeggi",},
        category = "inf_melee",
        group = "rare",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_carnosaur",
            glory_cost = 140,
        },
    },
	{
        key = "skeggi_coldones",
        military_groupings = {"skeggi",},
        category = "war_beast",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_skeggi_coldones",
            glory_cost = 65,
        },
    },
	{
        key = "skink_thralls",
        military_groupings = {"skeggi",},
        category = "inf_ranged",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 1,
        ritual = {
            key = "pttg_ritual_skink_thralls",
            glory_cost = 20,
        },
    },
	{
        key = "warmbloods",
        military_groupings = {"skeggi",},
        category = "inf_ranged",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_warmbloods",
            glory_cost = 20,
        },
    },
	{
        key = "frontiersmen",
        military_groupings = {"skeggi",},
        category = "inf_ranged",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_frontiersmen",
            glory_cost = 80,
        },
    },
	{
        key = "karls",
        military_groupings = {"skeggi",},
        category = "cavalry",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_karls",
            glory_cost = 20,
        },
    },
	{
        key = "spear_karls",
        military_groupings = {"skeggi",},
        category = "inf_melee",
        group = "core",
        weight = nil,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_spear_karls",
            glory_cost = 20,
        },
    },
	{
        key = "hofkarls",
        military_groupings = {"skeggi",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_hofkarls",
            glory_cost = 120,
        },
    },
	{
        key = "second_sons",
        military_groupings = {"skeggi",},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_second_sons",
            glory_cost = 80,
        },
    },
	{
        key = "hunting_dogs",
        military_groupings = {"wh2_dlc13_emp_the_huntmarshals_expedition",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_hunting_dogs",
            glory_cost = 65,
        },
    },
	{
        key = "skeggi_dogs",
        military_groupings = {"skeggi",},
        category = "inf_melee",
        group = "core",
        weight = 3,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_skeggi_dogs",
            glory_cost = 20,
        },
    },
	{
        key = "skeggi_hounds",
        military_groupings = {"skeggi",},
        category = "inf_melee",
        group = "core",
        weight = nil,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_skeggi_hounds",
            glory_cost = 20,
        },
    },
	{
        key = "vanguard",
        military_groupings = {"skeggi",},
        category = "inf_ranged",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_vanguard",
            glory_cost = 80,
        },
    },
	{
        key = "trappers",
        military_groupings = {"skeggi",},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_trappers",
            glory_cost = 65,
        },
    },
	{
        key = "kroxigor_thralls",
        military_groupings = {"skeggi",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_kroxigor_thralls",
            glory_cost = 120,
        },
    },
	{
        key = "terradon_horde",
        military_groupings = {"skeggi",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_terradon_horde",
            glory_cost = 120,
        },
    },
	{
        key = "engineers_imp",
        military_groupings = {"wh_main_emp_empire",},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_engineers_imp",
            glory_cost = 120,
        },
    },
	{
        key = "red_host",
        military_groupings = {"wh2_dlc12_lzd_cult_of_sotek",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_red_host",
            glory_cost = 120,
        },
    },
	{
        key = "hofkarl_mounted",
        military_groupings = {"skeggi",},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_hofkarl_mounted",
            glory_cost = 120,
        },
    },
	{
        key = "skg_war_wagon",
        military_groupings = {"skeggi",},
        category = "war_machine",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_skg_war_wagon",
            glory_cost = 80,
        },
    },
	{
        key = "skeleton_horsemen",
        military_groupings = {"wh_main_group_vampire_counts",},
        category = "cavalry",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_skeleton_horsemen",
            glory_cost = 20,
        },
    },
	{
        key = "sotek_picks",
        military_groupings = {"skeggi",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_sotek_picks",
            glory_cost = 65,
        },
    },
	{
        key = "sotek_shield",
        military_groupings = {"skeggi",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_sotek_shield",
            glory_cost = 65,
        },
    },
	{
        key = "necromancer_group",
        military_groupings = {"wh_main_group_vampire_counts",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_necromancer_group",
            glory_cost = 120,
        },
    },
	{
        key = "scholars",
        military_groupings = {"wh2_main_hef_order_of_loremasters",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_scholars",
            glory_cost = 120,
        },
    },
	{
        key = "nordlander",
        military_groupings = {"wh_main_emp_nordland",},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_nordlander",
            glory_cost = 20,
        },
    },
	{
        key = "knights_caledor",
        military_groupings = {"wh2_dlc15_hef_imrik",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_knights_caledor",
            glory_cost = 120,
        },
    },
	{
        key = "skryre_rat",
        military_groupings = {"wh2_main_skv_clan_skryre",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_skryre_rat",
            glory_cost = 120,
        },
    },
	{
        key = "chrace_cav",
        military_groupings = {"wh2_main_hef_chrace",},
        category = "cavalry",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_chrace_cav",
            glory_cost = 65,
        },
    },
	{
        key = "shadow_melee",
        military_groupings = {"wh2_main_hef_nagarythe",},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_shadow_melee",
            glory_cost = 80,
        },
    },
	{
        key = "skeggi_bret",
        military_groupings = {"skeggi",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_skeggi_bret",
            glory_cost = 120,
        },
    },
	{
        key = "ogre_dead",
        military_groupings = {"wh2_dlc11_cst_vampire_coast","wh2_dlc11_cst_noctilus","wh2_dlc11_cst_the_drowned",},
        category = "inf_ranged",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_ogre_dead",
            glory_cost = 80,
        },
    },
	{
        key = "skeggi_ogre",
        military_groupings = {"skeggi",},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_skeggi_ogre",
            glory_cost = 120,
        },
    },
	{
        key = "captains_altdorf",
        military_groupings = {"wh_main_group_empire_reikland","wh_main_group_empire",},
        category = "war_beast",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_captains_altdorf",
            glory_cost = 120,
        },
    },
	{
        key = "doomed_legion",
        military_groupings = {"wh2_dlc11_vmp_the_barrow_legion",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_doomed_legion",
            glory_cost = 120,
        },
    },
	{
        key = "zombo_dragon",
        military_groupings = {"wh_main_group_vampire_counts",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_zombo_dragon",
            glory_cost = 120,
        },
    },
	{
        key = "skegadon",
        military_groupings = {"skeggi",},
        category = "war_beast",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_skegadon",
            glory_cost = 120,
        },
    },
	{
        key = "marauder_halberds",
        military_groupings = {"wh_main_group_chaos",},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 1,
        ritual = {
            key = "pttg_ritual_marauder_halberds",
            glory_cost = 20,
        },
    },
	{
        key = "smiths",
        military_groupings = {"wh_main_group_bretonnia",},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_smiths",
            glory_cost = 20,
        },
    },
	{
        key = "kul_bows",
        military_groupings = {"skeggi",},
        category = "cavalry",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_kul_bows",
            glory_cost = 80,
        },
    },
	{
        key = "skg_knights",
        military_groupings = {"skeggi",},
        category = "cavalry",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_skg_knights",
            glory_cost = 80,
        },
    },
	{
        key = "bonepickers",
        military_groupings = {"wh3_main_ogr",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_bonepickers",
            glory_cost = 120,
        },
    },
	{
        key = "caravan_guard",
        military_groupings = {"skeggi",},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_caravan_guard",
            glory_cost = 65,
        },
    },
	{
        key = "celestial_riders",
        military_groupings = {"wh3_main_cth",},
        category = "war_beast",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_celestial_riders",
            glory_cost = 80,
        },
    },
	{
        key = "cathay_mace_peasant",
        military_groupings = {"wh3_main_cth",},
        category = "inf_melee",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 1,
        ritual = {
            key = "pttg_ritual_cathay_mace_peasant",
            glory_cost = 20,
        },
    },
	{
        key = "dismounted_gryphon",
        military_groupings = {"wh3_main_pro_ksl","wh3_main_ksl",},
        category = "inf_ranged",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_dismounted_gryphon",
            glory_cost = 80,
        },
    },
	{
        key = "druzhina",
        military_groupings = {"wh3_main_pro_ksl","wh3_main_ksl",},
        category = "war_beast",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_druzhina",
            glory_cost = 80,
        },
    },
	{
        key = "fire_hail",
        military_groupings = {"wh3_main_cth",},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_fire_hail",
            glory_cost = 120,
        },
    },
	{
        key = "fireglaive_warriors",
        military_groupings = {"wh3_dlc23_group_chaos_dwarfs",},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_fireglaive_warriors",
            glory_cost = 65,
        },
    },
	{
        key = "firelancers",
        military_groupings = {"wh3_main_cth",},
        category = "war_beast",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_firelancers",
            glory_cost = 120,
        },
    },
	{
        key = "gnoblar_archers",
        military_groupings = {"wh3_main_ogr",},
        category = "inf_ranged",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 1,
        ritual = {
            key = "pttg_ritual_gnoblar_archers",
            glory_cost = 20,
        },
    },
	{
        key = "gnoblar_swords",
        military_groupings = {"wh3_main_ogr",},
        category = "inf_melee",
        group = "core",
        weight = 1,
        tier = nil,
        cost = 1,
        ritual = {
            key = "pttg_ritual_gnoblar_swords",
            glory_cost = 20,
        },
    },
	{
        key = "gnoblar_wolves",
        military_groupings = {"wh3_main_ogr",},
        category = "cavalry",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_gnoblar_wolves",
            glory_cost = 65,
        },
    },
	{
        key = "jade_archers",
        military_groupings = {"wh3_main_cth",},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_jade_archers",
            glory_cost = 65,
        },
    },
	{
        key = "jade_axemen",
        military_groupings = {"wh3_main_cth",},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_jade_axemen",
            glory_cost = 20,
        },
    },
	{
        key = "kossack_scout",
        military_groupings = {"skeggi",},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_kossack_scout",
            glory_cost = 120,
        },
    },
	{
        key = "kossar_bardiche",
        military_groupings = {"wh3_main_pro_ksl","wh3_main_ksl",},
        category = "inf_melee",
        group = "core",
        weight = 3,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_kossar_bardiche",
            glory_cost = 20,
        },
    },
	{
        key = "kossar_sword",
        military_groupings = {"wh3_main_pro_ksl","wh3_main_ksl",},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 1,
        ritual = {
            key = "pttg_ritual_kossar_sword",
            glory_cost = 20,
        },
    },
	{
        key = "marauder_archers",
        military_groupings = {"wh3_main_sla",},
        category = "inf_melee",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 1,
        ritual = {
            key = "pttg_ritual_marauder_archers",
            glory_cost = 65,
        },
    },
	{
        key = "nehek_axe",
        military_groupings = {"wh2_dlc09_tomb_kings_arkhan","wh2_dlc09_tomb_kings",},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_nehek_axe",
            glory_cost = 80,
        },
    },
	{
        key = "nehek_bowmen",
        military_groupings = {"wh2_dlc09_tomb_kings_arkhan","wh2_dlc09_tomb_kings",},
        category = "inf_ranged",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_nehek_bowmen",
            glory_cost = 80,
        },
    },
	{
        key = "red_crested_cohort",
        military_groupings = {"wh2_main_lzd",},
        category = "inf_ranged",
        group = "special",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_red_crested_cohort",
            glory_cost = 65,
        },
    },
	{
        key = "repeater_crossbows",
        military_groupings = {"wh3_main_cth",},
        category = "inf_ranged",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_repeater_crossbows",
            glory_cost = 120,
        },
    },
	{
        key = "yuan_dao",
        military_groupings = {"wh3_main_cth",},
        category = "inf_melee",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_yuan_dao",
            glory_cost = 120,
        },
    },
	{
        key = "swiftwings",
        military_groupings = {"wh3_main_pro_ksl","wh3_main_ksl",},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_swiftwings",
            glory_cost = 120,
        },
    },
	{
        key = "tomb_horsemen",
        military_groupings = {"wh2_dlc09_tomb_kings_arkhan","wh2_dlc09_tomb_kings",},
        category = "cavalry",
        group = "rare",
        weight = 1,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_tomb_horsemen",
            glory_cost = 120,
        },
    },
	{
        key = "woodsmen",
        military_groupings = {"wh3_main_pro_ksl","wh3_main_ksl",},
        category = "inf_melee",
        group = "core",
        weight = nil,
        tier = nil,
        cost = 1,
        ritual = {
            key = "pttg_ritual_woodsmen",
            glory_cost = 20,
        },
    },
	{
        key = "yin_spears",
        military_groupings = {"wh3_main_cth",},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_yin_spears",
            glory_cost = 80,
        },
    },
	{
        key = "cr_ksl_inf_streltsi_bardiche",
        military_groupings = {"wh3_main_ksl",},
        category = "inf_melee",
        group = "core",
        weight = nil,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_cr_ksl_inf_streltsi_bardiche",
            glory_cost = 20,
        },
    },
	{
        key = "champions_khorne",
        military_groupings = {"wh_main_group_norsca","wh3_main_pro_kho","wh3_main_kho",},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_champions_khorne",
            glory_cost = 80,
        },
    },
	{
        key = "champions_tzeentch",
        military_groupings = {"wh_main_group_norsca","wh3_main_pro_tze","wh3_main_tze",},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_champions_tzeentch",
            glory_cost = 80,
        },
    },
	{
        key = "champions_slaanesh",
        military_groupings = {"wh_main_group_norsca","wh3_main_sla",},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_champions_slaanesh",
            glory_cost = 80,
        },
    },
	{
        key = "champions_nurgle",
        military_groupings = {"wh_main_group_norsca","wh3_main_nur",},
        category = "inf_melee",
        group = "special",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_champions_nurgle",
            glory_cost = 80,
        },
    },
	{
        key = "zombie_horde",
        military_groupings = {"wh_main_group_vampire_counts",},
        category = "inf_melee",
        group = "core",
        weight = 2,
        tier = nil,
        cost = 2,
        ritual = {
            key = "pttg_ritual_zombie_horde",
            glory_cost = 20,
        },
    },
}



file = io.open("output/submod_mercenaries.txt", "w")
io.output(file)
io.write("# campaign_group_rituals_tables\n")
for _, mercenary in pairs(mercenaries) do
    if mercenary.ritual.key then
        io.write(string.format("pttg_main_crafting_all	%s		0	false\n", 
            mercenary.ritual.key))
    end
end


io.write("\n# mercenary_pool_to_groups_junctions_tables\n")
for _, mercenary in pairs(mercenaries) do
    io.write(string.format("<unique_id>	pttg_%s	0	pttg_raise_dead_pool			\n", 
        mercenary.key))
end

io.write("\n# mercenary_unit_groups_tables\n")
for _, mercenary in pairs(mercenaries) do
    io.write(string.format("pttg_%s	0.0000	0	%s	false	0.0000\n", 
        mercenary.key, mercenary.key))
end
io.write("\n# mortuary_cult_categories_to_rituals_tables\n")
for _, mercenary in pairs(mercenaries) do
    if mercenary.ritual.key then
        io.write(string.format("pttg_crafting_units	%s\n", 
            mercenary.ritual.key))
    end
end
io.write("\n# resource_cost_pooled_resource_junctions_tables\n")
for _, mercenary in pairs(mercenaries) do
    if mercenary.ritual.key then
        io.write(string.format("pttg_glory_point_factor	%s	-%s	absolute	default\n", 
            mercenary.ritual.key, mercenary.ritual.glory_cost))
    end
end
io.write("\n# resource_costs_tables\n")
for _, mercenary in pairs(mercenaries) do
    if mercenary.ritual.key then
        io.write(string.format("%s	0	RITUAL	RITUAL	ARMY_UPKEEP	BACKGROUND_INCOME\n", 
            mercenary.ritual.key))
    end
end
io.write("\n# ritual_payload_spawn_mercenaries_tables\n")
for _, mercenary in pairs(mercenaries) do
    if mercenary.ritual.key then
        io.write(string.format("<unique_id>	%s	%s	false\n", 
            mercenary.ritual.key, mercenary.key))
    end
end
io.write("\n# ritual_payloads_tables\n")
for _, mercenary in pairs(mercenaries) do
    if mercenary.ritual.key then
        io.write(string.format("%s	false	\n", 
            mercenary.ritual.key))
    end
end
io.write("\n# rituals_tables\n")
for _, mercenary in pairs(mercenaries) do
    if mercenary.ritual.key then
        io.write(string.format("%s	0	%s	9999	CRAFTING_RITUAL	0	0			0		%s				0	0				default	\n", 
            mercenary.ritual.key, mercenary.ritual.key, mercenary.ritual.key))
    end
end

io.write("\n# unit_purchasable_effect_sets_tables\n")
for _, mercenary in pairs(mercenaries) do
    if mercenary.ritual.key then
        io.write(string.format("%s	pttg_rest_training	false\n", 
            mercenary.key))
    end
end


io.write("\n# Add the mercenary to pttg in your script: \n")
io.write("local pttg_merc_pool = core:get_static_object('pttg_merc_pool')\n\n")
io.write("local mercenaries = {\n")
for _, mercenary in pairs(mercenaries) do
    io.write(string.format('\t{"%s", "%s", %s, { military_groupings = {%s}, category = "%s", tier = %s, cost = %s }},\n', 
        mercenary.key, mercenary.group, mercenary.weight, '"'..table.concat(mercenary.military_groupings, '","')..'"', mercenary.category, mercenary.tier, mercenary.cost)
    )
end
io.write("}\n")
io.write("pttg_merc_pool:add_unit_list(mercenaries)\n")
