cultures = {
    "wh2_dlc09_tmb_tomb_kings",
    "wh2_dlc11_cst_vampire_coast",
    "wh2_main_def_dark_elves",
    "wh2_main_hef_high_elves",
    "wh2_main_lzd_lizardmen",
    "wh2_main_skv_skaven",
    "wh3_dlc23_chd_chaos_dwarfs",
    "wh3_main_cth_cathay",
    "wh3_main_dae_daemons",
    "wh3_main_kho_khorne",
    "wh3_main_ksl_kislev",
    "wh3_main_nur_nurgle",
    "wh3_main_ogr_ogre_kingdoms",
    "wh3_main_sla_slaanesh",
    "wh3_main_tze_tzeentch",
    "wh_dlc03_bst_beastmen",
    "wh_dlc05_wef_wood_elves",
    "wh_dlc08_nor_norsca",
    "wh_main_brt_bretonnia",
    "wh_main_chs_chaos",
    "wh_main_dwf_dwarfs",
    "wh_main_emp_empire",
    "wh_main_grn_greenskins",
    "wh_main_vmp_vampire_counts"
}

culture_keys = {
    "tmb_",
    "cst_",
    "def_",
    "hef_",
    "lzd_",
    "skv_",
    "chd_",
    "cth_",
    "dae_",
    "kho_",
    "ksl_",
    "nur_",
    "ogr_",
    "sla_",
    "tze_",
    "bst_",
    "wef_",
    "nor_",
    "brt_",
    "chs_",
    "dwf_",
    "emp_",
    "grn_",
    "vmp_"
}

units = {
    { main_unit = "wh2_dlc09_tmb_art_casket_of_souls_0", land_unit = 	"wh2_dlc09_tmb_art_casket_of_souls_0" },
    { main_unit = "wh2_dlc09_tmb_art_screaming_skull_catapult_0", land_unit = 	"wh2_dlc09_tmb_art_screaming_skull_catapult_0" },
    { main_unit = "wh2_dlc09_tmb_cav_hexwraiths", land_unit = 	"wh2_dlc09_tmb_cav_hexwraiths" },
    { main_unit = "wh2_dlc09_tmb_cav_necropolis_knights_0", land_unit = 	"wh2_dlc09_tmb_cav_necropolis_knights_0" },
    { main_unit = "wh2_dlc09_tmb_cav_necropolis_knights_1", land_unit = 	"wh2_dlc09_tmb_cav_necropolis_knights_1" },
    { main_unit = "wh2_dlc09_tmb_cav_nehekhara_horsemen_0", land_unit = 	"wh2_dlc09_tmb_cav_nehekhara_horsemen_0" },
    { main_unit = "wh2_dlc09_tmb_cav_skeleton_horsemen_0", land_unit = 	"wh2_dlc09_tmb_cav_skeleton_horsemen_0" },
    { main_unit = "wh2_dlc09_tmb_cav_skeleton_horsemen_archers_0", land_unit = 	"wh2_dlc09_tmb_cav_skeleton_horsemen_archers_0" },
    { main_unit = "wh2_dlc09_tmb_inf_crypt_ghouls", land_unit = 	"wh2_dlc09_tmb_inf_crypt_ghouls" },
    { main_unit = "wh2_dlc09_tmb_inf_nehekhara_warriors_0", land_unit = 	"wh2_dlc09_tmb_inf_nehekhara_warriors_0" },
    { main_unit = "wh2_dlc09_tmb_inf_skeleton_archers_0", land_unit = 	"wh2_dlc09_tmb_inf_skeleton_archers_0" },
    { main_unit = "wh2_dlc09_tmb_inf_skeleton_spearmen_0", land_unit = 	"wh2_dlc09_tmb_inf_skeleton_spearmen_0" },
    { main_unit = "wh2_dlc09_tmb_inf_skeleton_warriors_0", land_unit = 	"wh2_dlc09_tmb_inf_skeleton_warriors_0" },
    { main_unit = "wh2_dlc09_tmb_inf_tomb_guard_0", land_unit = 	"wh2_dlc09_tmb_inf_tomb_guard_0" },
    { main_unit = "wh2_dlc09_tmb_inf_tomb_guard_1", land_unit = 	"wh2_dlc09_tmb_inf_tomb_guard_1" },
    { main_unit = "wh2_dlc09_tmb_mon_carrion_0", land_unit = 	"wh2_dlc09_tmb_mon_carrion_0" },
    { main_unit = "wh2_dlc09_tmb_mon_dire_wolves", land_unit = 	"wh2_dlc09_tmb_mon_dire_wolves" },
    { main_unit = "wh2_dlc09_tmb_mon_fell_bats", land_unit = 	"wh2_dlc09_tmb_mon_fell_bats" },
    { main_unit = "wh2_dlc09_tmb_mon_heirotitan_0", land_unit = 	"wh2_dlc09_tmb_mon_heirotitan_0" },
    { main_unit = "wh2_dlc09_tmb_mon_necrosphinx_0", land_unit = 	"wh2_dlc09_tmb_mon_necrosphinx_0" },
    { main_unit = "wh2_dlc09_tmb_mon_sepulchral_stalkers_0", land_unit = 	"wh2_dlc09_tmb_mon_sepulchral_stalkers_0" },
    { main_unit = "wh2_dlc09_tmb_mon_tomb_scorpion_0", land_unit = 	"wh2_dlc09_tmb_mon_tomb_scorpion_0" },
    { main_unit = "wh2_dlc09_tmb_mon_ushabti_0", land_unit = 	"wh2_dlc09_tmb_mon_ushabti_0" },
    { main_unit = "wh2_dlc09_tmb_mon_ushabti_1", land_unit = 	"wh2_dlc09_tmb_mon_ushabti_1" },
    { main_unit = "wh2_dlc09_tmb_veh_khemrian_warsphinx_0", land_unit = 	"wh2_dlc09_tmb_mon_khemrian_warsphinx_0" },
    { main_unit = "wh2_dlc09_tmb_veh_skeleton_archer_chariot_0", land_unit = 	"wh2_dlc09_tmb_veh_skeleton_archer_chariot_0" },
    { main_unit = "wh2_dlc09_tmb_veh_skeleton_chariot_0", land_unit = 	"wh2_dlc09_tmb_veh_skeleton_chariot_0" },
    { main_unit = "wh2_dlc10_def_cav_doomfire_warlocks_0", land_unit = 	"wh2_dlc10_def_cav_doomfire_warlocks_0" },
    { main_unit = "wh2_dlc10_def_inf_sisters_of_slaughter", land_unit = 	"wh2_dlc10_def_inf_sisters_of_slaughter" },
    { main_unit = "wh2_dlc10_def_mon_feral_manticore_0", land_unit = 	"wh2_dlc10_def_mon_feral_manticore_0" },
    { main_unit = "wh2_dlc10_def_mon_kharibdyss_0", land_unit = 	"wh2_dlc10_def_mon_kharibdyss_0" },
    { main_unit = "wh2_dlc10_dwf_inf_giant_slayers", land_unit = 	"wh2_dlc10_dwf_inf_giant_slayers" },
    { main_unit = "wh2_dlc10_hef_inf_dryads_0", land_unit = 	"wh2_dlc10_hef_inf_dryads_0" },
    { main_unit = "wh2_dlc10_hef_inf_shadow_walkers_0", land_unit = 	"wh2_dlc10_hef_inf_shadow_walkers_0" },
    { main_unit = "wh2_dlc10_hef_inf_shadow_warriors_0", land_unit = 	"wh2_dlc10_hef_inf_shadow_warriors_0" },
    { main_unit = "wh2_dlc10_hef_inf_sisters_of_avelorn_0", land_unit = 	"wh2_dlc10_hef_inf_sisters_of_avelorn_0" },
    { main_unit = "wh2_dlc10_hef_mon_treekin_0", land_unit = 	"wh2_dlc10_hef_mon_treekin_0" },
    { main_unit = "wh2_dlc10_hef_mon_treeman_0", land_unit = 	"wh2_dlc10_hef_mon_treeman_0" },
    { main_unit = "wh2_dlc11_cst_art_carronade", land_unit = 	"wh2_dlc11_cst_art_carronade" },
    { main_unit = "wh2_dlc11_cst_art_mortar", land_unit = 	"wh2_dlc11_cst_art_mortar" },
    { main_unit = "wh2_dlc11_cst_cav_deck_droppers_0", land_unit = 	"wh2_dlc11_cst_cav_deck_droppers_0" },
    { main_unit = "wh2_dlc11_cst_cav_deck_droppers_1", land_unit = 	"wh2_dlc11_cst_cav_deck_droppers_1" },
    { main_unit = "wh2_dlc11_cst_cav_deck_droppers_2", land_unit = 	"wh2_dlc11_cst_cav_deck_droppers_2" },
    { main_unit = "wh2_dlc11_cst_cav_knights_errant_0", land_unit = 	"wh2_dlc11_cst_cav_knights_errant_0" },
    { main_unit = "wh2_dlc11_cst_cav_knights_errant_1", land_unit = 	"wh2_dlc11_cst_cav_knights_errant_1" },
    { main_unit = "wh2_dlc11_cst_cav_knights_errant_2", land_unit = 	"wh2_dlc11_cst_cav_knights_errant_2" },
    { main_unit = "wh2_dlc11_cst_cav_knights_of_the_realm", land_unit = 	"wh2_dlc11_cst_cav_knights_of_the_realm" },
    { main_unit = "wh2_dlc11_cst_cav_questing_knights_0", land_unit = 	"wh2_dlc11_cst_cav_questing_knights_0" },
    { main_unit = "wh2_dlc11_cst_inf_deck_gunners_0", land_unit = 	"wh2_dlc11_cst_inf_deck_gunners_0" },
    { main_unit = "wh2_dlc11_cst_inf_depth_guard_0", land_unit = 	"wh2_dlc11_cst_inf_depth_guard_0" },
    { main_unit = "wh2_dlc11_cst_inf_depth_guard_1", land_unit = 	"wh2_dlc11_cst_inf_depth_guard_1" },
    { main_unit = "wh2_dlc11_cst_inf_sartosa_free_company_0", land_unit = 	"wh2_dlc11_cst_inf_sartosa_free_company_0" },
    { main_unit = "wh2_dlc11_cst_inf_sartosa_militia_0", land_unit = 	"wh2_dlc11_cst_inf_sartosa_militia_0" },
    { main_unit = "wh2_dlc11_cst_inf_syreens", land_unit = 	"wh2_dlc11_cst_inf_syreens" },
    { main_unit = "wh2_dlc11_cst_inf_zombie_deckhands_mob_0", land_unit = 	"wh2_dlc11_cst_inf_zombie_deckhands_mob_0" },
    { main_unit = "wh2_dlc11_cst_inf_zombie_deckhands_mob_1", land_unit = 	"wh2_dlc11_cst_inf_zombie_deckhands_mob_1" },
    { main_unit = "wh2_dlc11_cst_inf_zombie_gunnery_mob_0", land_unit = 	"wh2_dlc11_cst_inf_zombie_gunnery_mob_0" },
    { main_unit = "wh2_dlc11_cst_inf_zombie_gunnery_mob_1", land_unit = 	"wh2_dlc11_cst_inf_zombie_gunnery_mob_1" },
    { main_unit = "wh2_dlc11_cst_inf_zombie_gunnery_mob_2", land_unit = 	"wh2_dlc11_cst_inf_zombie_gunnery_mob_2" },
    { main_unit = "wh2_dlc11_cst_inf_zombie_gunnery_mob_3", land_unit = 	"wh2_dlc11_cst_inf_zombie_gunnery_mob_3" },
    { main_unit = "wh2_dlc11_cst_mon_animated_hulks_0", land_unit = 	"wh2_dlc11_cst_mon_animated_hulks_0" },
    { main_unit = "wh2_dlc11_cst_mon_bloated_corpse_0", land_unit = 	"wh2_dlc11_cst_mon_bloated_corpse_0" },
    { main_unit = "wh2_dlc11_cst_mon_fell_bats", land_unit = 	"wh2_dlc11_cst_mon_fell_bats" },
    { main_unit = "wh2_dlc11_cst_mon_mournguls_0", land_unit = 	"wh2_dlc11_cst_mon_mournguls_0" },
    { main_unit = "wh2_dlc11_cst_mon_necrofex_colossus_0", land_unit = 	"wh2_dlc11_cst_mon_necrofex_colossus_0" },
    { main_unit = "wh2_dlc11_cst_mon_rotting_leviathan_0", land_unit = 	"wh2_dlc11_cst_mon_rotting_leviathan_0" },
    { main_unit = "wh2_dlc11_cst_mon_rotting_prometheans_0", land_unit = 	"wh2_dlc11_cst_mon_rotting_prometheans_0" },
    { main_unit = "wh2_dlc11_cst_mon_rotting_prometheans_gunnery_mob_0", land_unit = 	"wh2_dlc11_cst_mon_rotting_prometheans_gunnery_mob_0" },
    { main_unit = "wh2_dlc11_cst_mon_scurvy_dogs", land_unit = 	"wh2_dlc11_cst_mon_scurvy_dogs" },
    { main_unit = "wh2_dlc11_vmp_inf_crossbowmen", land_unit = 	"wh2_dlc11_vmp_inf_crossbowmen" },
    { main_unit = "wh2_dlc11_vmp_inf_handgunners", land_unit = 	"wh2_dlc11_vmp_inf_handgunners" },
    { main_unit = "wh2_dlc12_lzd_cav_ripperdactyl_riders_0", land_unit = 	"wh2_dlc12_lzd_cav_ripperdactyl_riders_0" },
    { main_unit = "wh2_dlc12_lzd_inf_skink_red_crested_0", land_unit = 	"wh2_dlc12_lzd_inf_skink_red_crested_0" },
    { main_unit = "wh2_dlc12_lzd_mon_ancient_salamander_0", land_unit = 	"wh2_dlc12_lzd_mon_ancient_salamander_0" },
    { main_unit = "wh2_dlc12_lzd_mon_ancient_stegadon_1", land_unit = 	"wh2_dlc12_lzd_mon_ancient_stegadon_1" },
    { main_unit = "wh2_dlc12_lzd_mon_bastiladon_3", land_unit = 	"wh2_dlc12_lzd_mon_bastiladon_3" },
    { main_unit = "wh2_dlc12_lzd_mon_salamander_pack_0", land_unit = 	"wh2_dlc12_lzd_mon_salamander_pack_0" },
    { main_unit = "wh2_dlc12_skv_inf_ratling_gun_0", land_unit = 	"wh2_dlc12_skv_inf_ratling_gun_0" },
    { main_unit = "wh2_dlc12_skv_inf_warplock_jezzails_0", land_unit = 	"wh2_dlc12_skv_inf_warplock_jezzails_0" },
    { main_unit = "wh2_dlc12_skv_veh_doom_flayer_0", land_unit = 	"wh2_dlc12_skv_veh_doom_flayer_0" },
    { main_unit = "wh2_dlc13_emp_inf_archers_0", land_unit = 	"wh2_dlc13_emp_inf_archers_0" },
    { main_unit = "wh2_dlc13_emp_inf_huntsmen_0", land_unit = 	"wh2_dlc13_emp_inf_huntsmen_0" },
    { main_unit = "wh2_dlc13_emp_veh_war_wagon_0", land_unit = 	"wh2_dlc13_emp_veh_war_wagon_0" },
    { main_unit = "wh2_dlc13_emp_veh_war_wagon_1", land_unit = 	"wh2_dlc13_emp_veh_war_wagon_1" },
    { main_unit = "wh2_dlc13_huntmarshall_veh_obsinite_gyrocopter_0", land_unit = 	"wh2_dlc13_huntmarshall_veh_obsinite_gyrocopter_0" },
    { main_unit = "wh2_dlc13_lzd_mon_dread_saurian_0", land_unit = 	"wh2_dlc13_lzd_mon_dread_saurian_0" },
    { main_unit = "wh2_dlc13_lzd_mon_dread_saurian_1", land_unit = 	"wh2_dlc13_lzd_mon_dread_saurian_1" },
    { main_unit = "wh2_dlc13_lzd_mon_razordon_pack_0", land_unit = 	"wh2_dlc13_lzd_mon_razordon_pack_0" },
    { main_unit = "wh2_dlc13_lzd_mon_sacred_kroxigors_0", land_unit = 	"wh2_dlc13_lzd_mon_sacred_kroxigors_0" },
    { main_unit = "wh2_dlc14_def_cav_scourgerunner_chariot_0", land_unit = 	"wh2_dlc14_def_cav_scourgerunner_chariot_0" },
    { main_unit = "wh2_dlc14_def_mon_bloodwrack_medusa_0", land_unit = 	"wh2_dlc14_def_mon_bloodwrack_medusa_0" },
    { main_unit = "wh2_dlc14_def_veh_bloodwrack_shrine_0", land_unit = 	"wh2_dlc14_def_veh_bloodwrack_shrine_0" },
    { main_unit = "wh2_dlc14_skv_inf_eshin_triads_0", land_unit = 	"wh2_dlc14_skv_inf_eshin_triads_0" },
    { main_unit = "wh2_dlc14_skv_inf_poison_wind_mortar_0", land_unit = 	"wh2_dlc14_skv_inf_poison_wind_mortar_0" },
    { main_unit = "wh2_dlc14_skv_inf_warp_grinder_0", land_unit = 	"wh2_dlc14_skv_inf_warp_grinder_0" },
    { main_unit = "wh2_dlc15_grn_mon_river_trolls_0", land_unit = 	"wh2_dlc15_grn_mon_river_trolls_0" },
    { main_unit = "wh2_dlc15_grn_mon_rogue_idol_0", land_unit = 	"wh2_dlc15_grn_mon_rogue_idol_0" },
    { main_unit = "wh2_dlc15_grn_mon_stone_trolls_0", land_unit = 	"wh2_dlc15_grn_mon_stone_trolls_0" },
    { main_unit = "wh2_dlc15_grn_veh_snotling_pump_wagon_0", land_unit = 	"wh2_dlc15_grn_veh_snotling_pump_wagon_0" },
    { main_unit = "wh2_dlc15_grn_veh_snotling_pump_wagon_flappas_0", land_unit = 	"wh2_dlc15_grn_veh_snotling_pump_wagon_flappas_0" },
    { main_unit = "wh2_dlc15_grn_veh_snotling_pump_wagon_roller_0", land_unit = 	"wh2_dlc15_grn_veh_snotling_pump_wagon_roller_0" },
    { main_unit = "wh2_dlc15_hef_inf_mistwalkers_faithbearers_0", land_unit = 	"wh2_dlc15_hef_inf_mistwalkers_faithbearers_0" },
    { main_unit = "wh2_dlc15_hef_inf_mistwalkers_griffon_knights_0", land_unit = 	"wh2_dlc15_hef_inf_mistwalkers_griffon_knights_0" },
    { main_unit = "wh2_dlc15_hef_inf_mistwalkers_sentinels_0", land_unit = 	"wh2_dlc15_hef_inf_mistwalkers_sentinels_0" },
    { main_unit = "wh2_dlc15_hef_inf_mistwalkers_skyhawks_0", land_unit = 	"wh2_dlc15_hef_inf_mistwalkers_skyhawks_0" },
    { main_unit = "wh2_dlc15_hef_inf_mistwalkers_spireguard_0", land_unit = 	"wh2_dlc15_hef_inf_mistwalkers_spireguard_0" },
    { main_unit = "wh2_dlc15_hef_inf_rangers_0", land_unit = 	"wh2_dlc15_hef_inf_rangers_0" },
    { main_unit = "wh2_dlc15_hef_inf_silverin_guard_0", land_unit = 	"wh2_dlc15_hef_inf_silverin_guard_0" },
    { main_unit = "wh2_dlc15_hef_mon_arcane_phoenix_0", land_unit = 	"wh2_dlc15_hef_mon_arcane_phoenix_0" },
    { main_unit = "wh2_dlc15_hef_mon_forest_dragon_0", land_unit = 	"wh2_dlc15_hef_mon_forest_dragon_0" },
    { main_unit = "wh2_dlc15_hef_mon_war_lions_of_chrace_0", land_unit = 	"wh2_dlc15_hef_mon_war_lions_of_chrace_0" },
    { main_unit = "wh2_dlc15_hef_veh_lion_chariot_of_chrace_0", land_unit = 	"wh2_dlc15_hef_veh_lion_chariot_of_chrace_0" },
    { main_unit = "wh2_dlc16_skv_mon_rat_ogre_mutant", land_unit = 	"wh2_dlc16_skv_mon_rat_ogre_mutant" },
    { main_unit = "wh2_dlc16_skv_mon_wolf_rats_0", land_unit = 	"wh2_dlc16_skv_mon_wolf_rats_0" },
    { main_unit = "wh2_dlc16_skv_mon_wolf_rats_1", land_unit = 	"wh2_dlc16_skv_mon_wolf_rats_1" },
    { main_unit = "wh2_dlc16_wef_cav_glade_riders_2", land_unit = 	"wh2_dlc16_wef_cav_glade_riders_2" },
    { main_unit = "wh2_dlc16_wef_cav_great_stag_knights_0", land_unit = 	"wh2_dlc16_wef_cav_great_stag_knights_0" },
    { main_unit = "wh2_dlc16_wef_inf_bladesingers_0", land_unit = 	"wh2_dlc16_wef_inf_bladesingers_0" },
    { main_unit = "wh2_dlc16_wef_inf_malicious_dryads_0", land_unit = 	"wh2_dlc16_wef_inf_malicious_dryads_0" },
    { main_unit = "wh2_dlc16_wef_mon_cave_bats", land_unit = 	"wh2_dlc16_wef_mon_cave_bats" },
    { main_unit = "wh2_dlc16_wef_mon_feral_manticore", land_unit = 	"wh2_dlc16_wef_mon_feral_manticore" },
    { main_unit = "wh2_dlc16_wef_mon_giant_spiders_0", land_unit = 	"wh2_dlc16_wef_mon_giant_spiders_0" },
    { main_unit = "wh2_dlc16_wef_mon_harpies_0", land_unit = 	"wh2_dlc16_wef_mon_harpies_0" },
    { main_unit = "wh2_dlc16_wef_mon_hawks_0", land_unit = 	"wh2_dlc16_wef_mon_hawks_0" },
    { main_unit = "wh2_dlc16_wef_mon_malicious_treekin_0", land_unit = 	"wh2_dlc16_wef_mon_malicious_treekin_0" },
    { main_unit = "wh2_dlc16_wef_mon_malicious_treeman_0", land_unit = 	"wh2_dlc16_wef_mon_malicious_treeman_0" },
    { main_unit = "wh2_dlc16_wef_mon_spider_hatchlings_0", land_unit = 	"wh2_dlc16_wef_mon_spider_hatchlings_0" },
    { main_unit = "wh2_dlc16_wef_mon_wolves_0", land_unit = 	"wh2_dlc16_wef_mon_wolves_0" },
    { main_unit = "wh2_dlc16_wef_mon_zoats", land_unit = 	"wh2_dlc16_wef_mon_zoats" },
    { main_unit = "wh2_dlc17_bst_cav_tuskgor_chariot_0", land_unit = 	"wh2_dlc17_bst_cav_tuskgor_chariot_0" },
    { main_unit = "wh2_dlc17_bst_mon_ghorgon_0", land_unit = 	"wh2_dlc17_bst_mon_ghorgon_0" },
    { main_unit = "wh2_dlc17_bst_mon_jabberslythe_0", land_unit = 	"wh2_dlc17_bst_mon_jabberslythe_0" },
    { main_unit = "wh2_dlc17_emp_inf_prisoners_0", land_unit = 	"wh2_dlc17_emp_inf_prisoners_0" },
    { main_unit = "wh2_dlc17_lzd_inf_chameleon_stalkers_0", land_unit = 	"wh2_dlc17_lzd_inf_chameleon_stalkers_0" },
    { main_unit = "wh2_dlc17_lzd_mon_coatl_0", land_unit = 	"wh2_dlc17_lzd_mon_coatl_0" },
    { main_unit = "wh2_dlc17_lzd_mon_troglodon_0", land_unit = 	"wh2_dlc17_lzd_mon_troglodon_0" },
    { main_unit = "wh2_main_def_art_reaper_bolt_thrower", land_unit = 	"wh2_main_def_art_reaper_bolt_thrower" },
    { main_unit = "wh2_main_def_cav_cold_one_chariot", land_unit = 	"wh2_main_def_cav_cold_one_chariot" },
    { main_unit = "wh2_main_def_cav_cold_one_knights_0", land_unit = 	"wh2_main_def_cav_cold_one_knights_0" },
    { main_unit = "wh2_main_def_cav_cold_one_knights_1", land_unit = 	"wh2_main_def_cav_cold_one_knights_1" },
    { main_unit = "wh2_main_def_cav_dark_riders_0", land_unit = 	"wh2_main_def_cav_dark_riders_0" },
    { main_unit = "wh2_main_def_cav_dark_riders_1", land_unit = 	"wh2_main_def_cav_dark_riders_1" },
    { main_unit = "wh2_main_def_cav_dark_riders_2", land_unit = 	"wh2_main_def_cav_dark_riders_2" },
    { main_unit = "wh2_main_def_inf_black_ark_corsairs_0", land_unit = 	"wh2_main_def_inf_black_ark_corsairs_0" },
    { main_unit = "wh2_main_def_inf_black_ark_corsairs_1", land_unit = 	"wh2_main_def_inf_black_ark_corsairs_1" },
    { main_unit = "wh2_main_def_inf_black_guard_0", land_unit = 	"wh2_main_def_inf_black_guard_0" },
    { main_unit = "wh2_main_def_inf_bleakswords_0", land_unit = 	"wh2_main_def_inf_bleakswords_0" },
    { main_unit = "wh2_main_def_inf_darkshards_0", land_unit = 	"wh2_main_def_inf_darkshards_0" },
    { main_unit = "wh2_main_def_inf_darkshards_1", land_unit = 	"wh2_main_def_inf_darkshards_1" },
    { main_unit = "wh2_main_def_inf_dreadspears_0", land_unit = 	"wh2_main_def_inf_dreadspears_0" },
    { main_unit = "wh2_main_def_inf_har_ganeth_executioners_0", land_unit = 	"wh2_main_def_inf_har_ganeth_executioners_0" },
    { main_unit = "wh2_main_def_inf_harpies", land_unit = 	"wh2_main_def_inf_harpies" },
    { main_unit = "wh2_main_def_inf_shades_0", land_unit = 	"wh2_main_def_inf_shades_0" },
    { main_unit = "wh2_main_def_inf_shades_1", land_unit = 	"wh2_main_def_inf_shades_1" },
    { main_unit = "wh2_main_def_inf_shades_2", land_unit = 	"wh2_main_def_inf_shades_2" },
    { main_unit = "wh2_main_def_inf_witch_elves_0", land_unit = 	"wh2_main_def_inf_witch_elves_0" },
    { main_unit = "wh2_main_def_mon_black_dragon", land_unit = 	"wh2_main_def_mon_black_dragon" },
    { main_unit = "wh2_main_def_mon_war_hydra", land_unit = 	"wh2_main_def_mon_war_hydra_0" },
    { main_unit = "wh2_main_hef_art_eagle_claw_bolt_thrower", land_unit = 	"wh2_main_hef_art_eagle_claw_bolt_thrower" },
    { main_unit = "wh2_main_hef_cav_dragon_princes", land_unit = 	"wh2_main_hef_cav_dragon_princes" },
    { main_unit = "wh2_main_hef_cav_ellyrian_reavers_0", land_unit = 	"wh2_main_hef_cav_ellyrian_reavers_0" },
    { main_unit = "wh2_main_hef_cav_ellyrian_reavers_1", land_unit = 	"wh2_main_hef_cav_ellyrian_reavers_1" },
    { main_unit = "wh2_main_hef_cav_ithilmar_chariot", land_unit = 	"wh2_main_hef_cav_ithilmar_chariot" },
    { main_unit = "wh2_main_hef_cav_silver_helms_0", land_unit = 	"wh2_main_hef_cav_silver_helms_0" },
    { main_unit = "wh2_main_hef_cav_silver_helms_1", land_unit = 	"wh2_main_hef_cav_silver_helms_1" },
    { main_unit = "wh2_main_hef_cav_tiranoc_chariot", land_unit = 	"wh2_main_hef_cav_tiranoc_chariot" },
    { main_unit = "wh2_main_hef_inf_archers_0", land_unit = 	"wh2_main_hef_inf_archers_0" },
    { main_unit = "wh2_main_hef_inf_archers_1", land_unit = 	"wh2_main_hef_inf_archers_1" },
    { main_unit = "wh2_main_hef_inf_gate_guard", land_unit = 	"wh2_main_hef_inf_gate_guard" },
    { main_unit = "wh2_main_hef_inf_lothern_sea_guard_0", land_unit = 	"wh2_main_hef_inf_lothern_sea_guard_0" },
    { main_unit = "wh2_main_hef_inf_lothern_sea_guard_1", land_unit = 	"wh2_main_hef_inf_lothern_sea_guard_1" },
    { main_unit = "wh2_main_hef_inf_phoenix_guard", land_unit = 	"wh2_main_hef_inf_phoenix_guard" },
    { main_unit = "wh2_main_hef_inf_spearmen_0", land_unit = 	"wh2_main_hef_inf_spearmen_0" },
    { main_unit = "wh2_main_hef_inf_swordmasters_of_hoeth_0", land_unit = 	"wh2_main_hef_inf_swordmasters_of_hoeth_0" },
    { main_unit = "wh2_main_hef_inf_white_lions_of_chrace_0", land_unit = 	"wh2_main_hef_inf_white_lions_of_chrace_0" },
    { main_unit = "wh2_main_hef_mon_great_eagle", land_unit = 	"wh2_main_hef_mon_great_eagle" },
    { main_unit = "wh2_main_hef_mon_moon_dragon", land_unit = 	"wh2_main_hef_mon_moon_dragon" },
    { main_unit = "wh2_main_hef_mon_phoenix_flamespyre", land_unit = 	"wh2_main_hef_mon_phoenix_flamespyre" },
    { main_unit = "wh2_main_hef_mon_phoenix_frostheart", land_unit = 	"wh2_main_hef_mon_phoenix_frostheart" },
    { main_unit = "wh2_main_hef_mon_star_dragon", land_unit = 	"wh2_main_hef_mon_star_dragon" },
    { main_unit = "wh2_main_hef_mon_sun_dragon", land_unit = 	"wh2_main_hef_mon_sun_dragon" },
    { main_unit = "wh2_main_lzd_cav_cold_one_spearmen_1", land_unit = 	"wh2_main_lzd_cav_cold_one_spearriders_1" },
    { main_unit = "wh2_main_lzd_cav_cold_ones_1", land_unit = 	"wh2_main_lzd_cav_cold_ones_1" },
    { main_unit = "wh2_main_lzd_cav_cold_ones_feral_0", land_unit = 	"wh2_main_lzd_cav_cold_ones_feral_0" },
    { main_unit = "wh2_main_lzd_cav_horned_ones_0", land_unit = 	"wh2_main_lzd_cav_horned_ones_0" },
    { main_unit = "wh2_main_lzd_cav_terradon_riders_0", land_unit = 	"wh2_main_lzd_cav_terradon_riders_0" },
    { main_unit = "wh2_main_lzd_cav_terradon_riders_1", land_unit = 	"wh2_main_lzd_cav_terradon_riders_1" },
    { main_unit = "wh2_main_lzd_inf_chameleon_skinks_0", land_unit = 	"wh2_main_lzd_inf_chameleon_skinks_0" },
    { main_unit = "wh2_main_lzd_inf_saurus_spearmen_0", land_unit = 	"wh2_main_lzd_inf_saurus_spearmen_0" },
    { main_unit = "wh2_main_lzd_inf_saurus_spearmen_1", land_unit = 	"wh2_main_lzd_inf_saurus_spearmen_1" },
    { main_unit = "wh2_main_lzd_inf_saurus_warriors_0", land_unit = 	"wh2_main_lzd_inf_saurus_warriors_0" },
    { main_unit = "wh2_main_lzd_inf_saurus_warriors_1", land_unit = 	"wh2_main_lzd_inf_saurus_warriors_1" },
    { main_unit = "wh2_main_lzd_inf_skink_cohort_0", land_unit = 	"wh2_main_lzd_inf_skink_cohort_0" },
    { main_unit = "wh2_main_lzd_inf_skink_cohort_1", land_unit = 	"wh2_main_lzd_inf_skink_cohort_1" },
    { main_unit = "wh2_main_lzd_inf_skink_skirmishers_0", land_unit = 	"wh2_main_lzd_inf_skink_skirmishers_0" },
    { main_unit = "wh2_main_lzd_inf_temple_guards", land_unit = 	"wh2_main_lzd_inf_temple_guards" },
    { main_unit = "wh2_main_lzd_mon_ancient_stegadon", land_unit = 	"wh2_main_lzd_mon_ancient_stegadon" },
    { main_unit = "wh2_main_lzd_mon_bastiladon_0", land_unit = 	"wh2_main_lzd_mon_bastiladon_0" },
    { main_unit = "wh2_main_lzd_mon_bastiladon_1", land_unit = 	"wh2_main_lzd_mon_bastiladon_1" },
    { main_unit = "wh2_main_lzd_mon_bastiladon_2", land_unit = 	"wh2_main_lzd_mon_bastiladon_2" },
    { main_unit = "wh2_main_lzd_mon_carnosaur_0", land_unit = 	"wh2_main_lzd_mon_carnosaur_0" },
    { main_unit = "wh2_main_lzd_mon_kroxigors", land_unit = 	"wh2_main_lzd_mon_kroxigors" },
    { main_unit = "wh2_main_lzd_mon_stegadon_0", land_unit = 	"wh2_main_lzd_mon_stegadon_0" },
    { main_unit = "wh2_main_lzd_mon_stegadon_1", land_unit = 	"wh2_main_lzd_mon_stegadon_1" },
    { main_unit = "wh2_main_skv_art_plagueclaw_catapult", land_unit = 	"wh2_main_skv_art_plagueclaw_catapult" },
    { main_unit = "wh2_main_skv_art_warp_lightning_cannon", land_unit = 	"wh2_main_skv_art_warp_lightning_cannon" },
    { main_unit = "wh2_main_skv_inf_clanrat_spearmen_0", land_unit = 	"wh2_main_skv_inf_clanrat_spearmen_0" },
    { main_unit = "wh2_main_skv_inf_clanrat_spearmen_1", land_unit = 	"wh2_main_skv_inf_clanrat_spearmen_1" },
    { main_unit = "wh2_main_skv_inf_clanrats_0", land_unit = 	"wh2_main_skv_inf_clanrats_0" },
    { main_unit = "wh2_main_skv_inf_clanrats_1", land_unit = 	"wh2_main_skv_inf_clanrats_1" },
    { main_unit = "wh2_main_skv_inf_death_globe_bombardiers", land_unit = 	"wh2_main_skv_inf_death_globe_bombardiers" },
    { main_unit = "wh2_main_skv_inf_death_runners_0", land_unit = 	"wh2_main_skv_inf_death_runners_0" },
    { main_unit = "wh2_main_skv_inf_gutter_runner_slingers_0", land_unit = 	"wh2_main_skv_inf_gutter_runner_slingers_0" },
    { main_unit = "wh2_main_skv_inf_gutter_runner_slingers_1", land_unit = 	"wh2_main_skv_inf_gutter_runner_slingers_1" },
    { main_unit = "wh2_main_skv_inf_gutter_runners_0", land_unit = 	"wh2_main_skv_inf_gutter_runners_0" },
    { main_unit = "wh2_main_skv_inf_gutter_runners_1", land_unit = 	"wh2_main_skv_inf_gutter_runners_1" },
    { main_unit = "wh2_main_skv_inf_night_runners_0", land_unit = 	"wh2_main_skv_inf_night_runners_0" },
    { main_unit = "wh2_main_skv_inf_night_runners_1", land_unit = 	"wh2_main_skv_inf_night_runners_1" },
    { main_unit = "wh2_main_skv_inf_plague_monk_censer_bearer", land_unit = 	"wh2_main_skv_inf_plague_monk_censer_bearer" },
    { main_unit = "wh2_main_skv_inf_plague_monks", land_unit = 	"wh2_main_skv_inf_plague_monks" },
    { main_unit = "wh2_main_skv_inf_poison_wind_globadiers", land_unit = 	"wh2_main_skv_inf_poison_wind_globadiers" },
    { main_unit = "wh2_main_skv_inf_skavenslave_slingers_0", land_unit = 	"wh2_main_skv_inf_skavenslave_slingers_0" },
    { main_unit = "wh2_main_skv_inf_skavenslave_spearmen_0", land_unit = 	"wh2_main_skv_inf_skavenslave_spearmen_0" },
    { main_unit = "wh2_main_skv_inf_skavenslaves_0", land_unit = 	"wh2_main_skv_inf_skavenslaves_0" },
    { main_unit = "wh2_main_skv_inf_stormvermin_0", land_unit = 	"wh2_main_skv_inf_stormvermin_0" },
    { main_unit = "wh2_main_skv_inf_stormvermin_1", land_unit = 	"wh2_main_skv_inf_stormvermin_1" },
    { main_unit = "wh2_main_skv_inf_warpfire_thrower", land_unit = 	"wh2_main_skv_inf_warpfire_thrower" },
    { main_unit = "wh2_main_skv_mon_hell_pit_abomination", land_unit = 	"wh2_main_skv_mon_hell_pit_abomination" },
    { main_unit = "wh2_main_skv_mon_rat_ogres", land_unit = 	"wh2_main_skv_mon_rat_ogres" },
    { main_unit = "wh2_main_skv_veh_doomwheel", land_unit = 	"wh2_main_skv_veh_doomwheel" },
    { main_unit = "wh2_pro06_tmb_mon_bone_giant_0", land_unit = 	"wh2_pro06_tmb_mon_bone_giant_0" },
    { main_unit = "wh2_twa03_def_mon_war_mammoth_0", land_unit = 	"wh2_twa03_def_mon_war_mammoth_0" },
    { main_unit = "wh2_twa03_def_mon_wolves_0", land_unit = 	"wh2_twa03_def_mon_wolves_0" },
    { main_unit = "wh2_twa03_grn_mon_wyvern_0", land_unit = 	"wh2_dlc15_grn_mon_wyvern_waaagh_0" },
    { main_unit = "wh3_dlc20_chs_cav_chaos_chariot_mkho", land_unit = 	"wh3_dlc20_chs_cav_chaos_chariot_mkho" },
    { main_unit = "wh3_dlc20_chs_cav_chaos_chariot_mnur", land_unit = 	"wh3_dlc20_chs_cav_chaos_chariot_mnur" },
    { main_unit = "wh3_dlc20_chs_cav_chaos_chariot_msla", land_unit = 	"wh3_dlc20_chs_cav_chaos_chariot_msla" },
    { main_unit = "wh3_dlc20_chs_cav_chaos_chariot_mtze", land_unit = 	"wh3_dlc20_chs_cav_chaos_chariot_mtze" },
    { main_unit = "wh3_dlc20_chs_cav_chaos_knights_mkho", land_unit = 	"wh3_dlc20_chs_cav_chaos_knights_mkho" },
    { main_unit = "wh3_dlc20_chs_cav_chaos_knights_mkho_lances", land_unit = 	"wh3_dlc20_chs_cav_chaos_knights_mkho_lances" },
    { main_unit = "wh3_dlc20_chs_cav_chaos_knights_mnur", land_unit = 	"wh3_dlc20_chs_cav_chaos_knights_mnur" },
    { main_unit = "wh3_dlc20_chs_cav_chaos_knights_mnur_lances", land_unit = 	"wh3_dlc20_chs_cav_chaos_knights_mnur_lances" },
    { main_unit = "wh3_dlc20_chs_cav_chaos_knights_msla", land_unit = 	"wh3_dlc20_chs_cav_chaos_knights_msla" },
    { main_unit = "wh3_dlc20_chs_cav_chaos_knights_msla_lances", land_unit = 	"wh3_dlc20_chs_cav_chaos_knights_msla_lances" },
    { main_unit = "wh3_dlc20_chs_cav_chaos_knights_mtze_lances", land_unit = 	"wh3_dlc20_chs_cav_chaos_knights_mtze_lances" },
    { main_unit = "wh3_dlc20_chs_cav_marauder_horsemen_mkho_throwing_axes", land_unit = 	"wh3_dlc20_chs_cav_marauder_horsemen_mkho_throwing_axes" },
    { main_unit = "wh3_dlc20_chs_cav_marauder_horsemen_mnur_throwing_axes", land_unit = 	"wh3_dlc20_chs_cav_marauder_horsemen_mnur_throwing_axes" },
    { main_unit = "wh3_dlc20_chs_cav_marauder_horsemen_msla_javelins", land_unit = 	"wh3_dlc20_chs_cav_marauder_horsemen_msla_javelins" },
    { main_unit = "wh3_dlc20_chs_cav_marauder_horsemen_mtze_javelins", land_unit = 	"wh3_dlc20_chs_cav_marauder_horsemen_mtze_javelins" },
    { main_unit = "wh3_dlc20_chs_inf_chaos_marauders_mkho", land_unit = 	"wh3_dlc20_chs_inf_chaos_marauders_mkho" },
    { main_unit = "wh3_dlc20_chs_inf_chaos_marauders_mkho_dualweapons", land_unit = 	"wh3_dlc20_chs_inf_chaos_marauders_mkho_dualweapons" },
    { main_unit = "wh3_dlc20_chs_inf_chaos_marauders_mnur", land_unit = 	"wh3_dlc20_chs_inf_chaos_marauders_mnur" },
    { main_unit = "wh3_dlc20_chs_inf_chaos_marauders_mnur_greatweapons", land_unit = 	"wh3_dlc20_chs_inf_chaos_marauders_mnur_greatweapons" },
    { main_unit = "wh3_dlc20_chs_inf_chaos_marauders_msla", land_unit = 	"wh3_dlc20_chs_inf_chaos_marauders_msla" },
    { main_unit = "wh3_dlc20_chs_inf_chaos_marauders_msla_hellscourges", land_unit = 	"wh3_dlc20_chs_inf_chaos_marauders_msla_hellscourges" },
    { main_unit = "wh3_dlc20_chs_inf_chaos_marauders_mtze", land_unit = 	"wh3_dlc20_chs_inf_chaos_marauders_mtze" },
    { main_unit = "wh3_dlc20_chs_inf_chaos_marauders_mtze_spears", land_unit = 	"wh3_dlc20_chs_inf_chaos_marauders_mtze_spears" },
    { main_unit = "wh3_dlc20_chs_inf_chaos_warriors_mnur", land_unit = 	"wh3_dlc20_chs_inf_chaos_warriors_mnur" },
    { main_unit = "wh3_dlc20_chs_inf_chaos_warriors_mnur_greatweapons", land_unit = 	"wh3_dlc20_chs_inf_chaos_warriors_mnur_greatweapons" },
    { main_unit = "wh3_dlc20_chs_inf_chaos_warriors_msla", land_unit = 	"wh3_dlc20_chs_inf_chaos_warriors_msla" },
    { main_unit = "wh3_dlc20_chs_inf_chaos_warriors_msla_hellscourges", land_unit = 	"wh3_dlc20_chs_inf_chaos_warriors_msla_hellscourges" },
    { main_unit = "wh3_dlc20_chs_inf_chaos_warriors_mtze", land_unit = 	"wh3_dlc20_chs_inf_chaos_warriors_mtze" },
    { main_unit = "wh3_dlc20_chs_inf_chaos_warriors_mtze_halberds", land_unit = 	"wh3_dlc20_chs_inf_chaos_warriors_mtze_halberds" },
    { main_unit = "wh3_dlc20_chs_inf_chosen_mkho", land_unit = 	"wh3_dlc20_chs_inf_chosen_mkho" },
    { main_unit = "wh3_dlc20_chs_inf_chosen_mkho_dualweapons", land_unit = 	"wh3_dlc20_chs_inf_chosen_mkho_dualweapons" },
    { main_unit = "wh3_dlc20_chs_inf_chosen_mnur", land_unit = 	"wh3_dlc20_chs_inf_chosen_mnur" },
    { main_unit = "wh3_dlc20_chs_inf_chosen_mnur_greatweapons", land_unit = 	"wh3_dlc20_chs_inf_chosen_mnur_greatweapons" },
    { main_unit = "wh3_dlc20_chs_inf_chosen_msla", land_unit = 	"wh3_dlc20_chs_inf_chosen_msla" },
    { main_unit = "wh3_dlc20_chs_inf_chosen_msla_hellscourges", land_unit = 	"wh3_dlc20_chs_inf_chosen_msla_hellscourges" },
    { main_unit = "wh3_dlc20_chs_inf_chosen_mtze", land_unit = 	"wh3_dlc20_chs_inf_chosen_mtze" },
    { main_unit = "wh3_dlc20_chs_inf_chosen_mtze_halberds", land_unit = 	"wh3_dlc20_chs_inf_chosen_mtze_halberds" },
    { main_unit = "wh3_dlc20_chs_inf_forsaken_mkho", land_unit = 	"wh3_dlc20_chs_inf_forsaken_mkho" },
    { main_unit = "wh3_dlc20_chs_inf_forsaken_msla", land_unit = 	"wh3_dlc20_chs_inf_forsaken_msla" },
    { main_unit = "wh3_dlc20_chs_mon_warshrine", land_unit = 	"wh3_dlc20_chs_mon_warshrine" },
    { main_unit = "wh3_dlc20_chs_mon_warshrine_mkho", land_unit = 	"wh3_dlc20_chs_mon_warshrine_mkho" },
    { main_unit = "wh3_dlc20_chs_mon_warshrine_mnur", land_unit = 	"wh3_dlc20_chs_mon_warshrine_mnur" },
    { main_unit = "wh3_dlc20_chs_mon_warshrine_msla", land_unit = 	"wh3_dlc20_chs_mon_warshrine_msla" },
    { main_unit = "wh3_dlc20_chs_mon_warshrine_mtze", land_unit = 	"wh3_dlc20_chs_mon_warshrine_mtze" },
    { main_unit = "wh3_dlc23_chd_cav_bull_centaurs_axe", land_unit = 	"wh3_dlc23_chd_cav_bull_centaurs_axe" },
    { main_unit = "wh3_dlc23_chd_cav_bull_centaurs_dual_axe", land_unit = 	"wh3_dlc23_chd_cav_bull_centaurs_dual_axe" },
    { main_unit = "wh3_dlc23_chd_cav_bull_centaurs_greatweapons", land_unit = 	"wh3_dlc23_chd_cav_bull_centaurs_greatweapons" },
    { main_unit = "wh3_dlc23_chd_cav_hobgoblin_wolf_raiders_bows", land_unit = 	"wh3_dlc23_chd_cav_hobgoblin_wolf_raiders_bows" },
    { main_unit = "wh3_dlc23_chd_cav_hobgoblin_wolf_raiders_spears", land_unit = 	"wh3_dlc23_chd_cav_hobgoblin_wolf_raiders_spears" },
    { main_unit = "wh3_dlc23_chd_inf_chaos_dwarf_blunderbusses", land_unit = 	"wh3_dlc23_chd_inf_chaos_dwarf_blunderbusses" },
    { main_unit = "wh3_dlc23_chd_inf_chaos_dwarf_warriors", land_unit = 	"wh3_dlc23_chd_inf_chaos_dwarf_warriors" },
    { main_unit = "wh3_dlc23_chd_inf_chaos_dwarf_warriors_great_weapons", land_unit = 	"wh3_dlc23_chd_inf_chaos_dwarf_warriors_great_weapons" },
    { main_unit = "wh3_dlc23_chd_inf_goblin_labourers", land_unit = 	"wh3_dlc23_chd_inf_goblin_labourers" },
    { main_unit = "wh3_dlc23_chd_inf_hobgoblin_archers", land_unit = 	"wh3_dlc23_chd_inf_hobgoblin_archers" },
    { main_unit = "wh3_dlc23_chd_inf_hobgoblin_cutthroats", land_unit = 	"wh3_dlc23_chd_inf_hobgoblin_cutthroats" },
    { main_unit = "wh3_dlc23_chd_inf_hobgoblin_sneaky_gits", land_unit = 	"wh3_dlc23_chd_inf_hobgoblin_sneaky_gits" },
    { main_unit = "wh3_dlc23_chd_inf_infernal_guard", land_unit = 	"wh3_dlc23_chd_inf_infernal_guard" },
    { main_unit = "wh3_dlc23_chd_inf_infernal_guard_fireglaives", land_unit = 	"wh3_dlc23_chd_inf_infernal_guard_fireglaives" },
    { main_unit = "wh3_dlc23_chd_inf_infernal_guard_great_weapons", land_unit = 	"wh3_dlc23_chd_inf_infernal_guard_great_weapons" },
    { main_unit = "wh3_dlc23_chd_inf_infernal_ironsworn", land_unit = 	"wh3_dlc23_chd_inf_infernal_ironsworn" },
    { main_unit = "wh3_dlc23_chd_inf_orc_labourers", land_unit = 	"wh3_dlc23_chd_inf_orc_labourers" },
    { main_unit = "wh3_dlc23_chd_mon_bale_taurus", land_unit = 	"wh3_dlc23_chd_mon_bale_taurus" },
    { main_unit = "wh3_dlc23_chd_mon_great_taurus", land_unit = 	"wh3_dlc23_chd_mon_great_taurus" },
    { main_unit = "wh3_dlc23_chd_mon_kdaai_destroyer", land_unit = 	"wh3_dlc23_chd_mon_kdaai_destroyer" },
    { main_unit = "wh3_dlc23_chd_mon_kdaai_fireborn", land_unit = 	"wh3_dlc23_chd_mon_kdaai_fireborn" },
    { main_unit = "wh3_dlc23_chd_mon_lammasu", land_unit = 	"wh3_dlc23_chd_mon_lammasu" },
    { main_unit = "wh3_dlc23_chd_veh_deathshrieker_rocket_launcher", land_unit = 	"wh3_dlc23_chd_veh_deathshrieker_rocket_launcher" },
    { main_unit = "wh3_dlc23_chd_veh_dreadquake_mortar", land_unit = 	"wh3_dlc23_chd_veh_dreadquake_mortar" },
    { main_unit = "wh3_dlc23_chd_veh_iron_daemon", land_unit = 	"wh3_dlc23_chd_veh_iron_daemon" },
    { main_unit = "wh3_dlc23_chd_veh_iron_daemon_1dreadquake", land_unit = 	"wh3_dlc23_chd_veh_iron_daemon_1dreadquake" },
    { main_unit = "wh3_dlc23_chd_veh_magma_cannon", land_unit = 	"wh3_dlc23_chd_veh_magma_cannon" },
    { main_unit = "wh3_dlc23_chd_veh_skullcracker", land_unit = 	"wh3_dlc23_chd_veh_skullcracker" },
    { main_unit = "wh3_dlc23_chd_veh_skullcracker_1dreadquake", land_unit = 	"wh3_dlc23_chd_veh_skullcracker_1dreadquake" },
    { main_unit = "wh3_dlc24_bst_inf_centigors_great_weapons_mtze", land_unit = 	"wh3_dlc24_tze_inf_centigors_great_weapons" },
    { main_unit = "wh3_dlc24_bst_inf_tzaangors", land_unit = 	"wh3_dlc24_tze_inf_tzaangors" },
    { main_unit = "wh3_dlc24_bst_mon_incarnate_elemental_of_beasts", land_unit = 	"wh3_dlc24_ksl_mon_incarnate_elemental_of_beasts" },
    { main_unit = "wh3_dlc24_cth_inf_onyx_crowmen", land_unit = 	"wh3_dlc24_cth_inf_onyx_crowmen" },
    { main_unit = "wh3_dlc24_cth_mon_celestial_lion", land_unit = 	"wh3_dlc24_cth_mon_celestial_lion" },
    { main_unit = "wh3_dlc24_cth_mon_great_moon_bird", land_unit = 	"wh3_dlc24_cth_mon_great_moon_bird" },
    { main_unit = "wh3_dlc24_cth_mon_jade_lion", land_unit = 	"wh3_dlc24_cth_mon_jade_lion" },
    { main_unit = "wh3_dlc24_cth_mon_jet_lion", land_unit = 	"wh3_dlc24_cth_mon_jet_lion" },
    { main_unit = "wh3_dlc24_cth_veh_zhangu_war_drum", land_unit = 	"wh3_dlc24_cth_veh_zhangu_war_drum" },
    { main_unit = "wh3_dlc24_ksl_inf_akshina_ambushers", land_unit = 	"wh3_dlc24_ksl_inf_akshina_ambushers" },
    { main_unit = "wh3_dlc24_ksl_inf_kislevite_warriors", land_unit = 	"wh3_dlc24_ksl_inf_kislevite_warriors" },
    { main_unit = "wh3_dlc24_ksl_mon_frost_wyrm", land_unit = 	"wh3_dlc24_ksl_mon_frost_wyrm" },
    { main_unit = "wh3_dlc24_ksl_mon_incarnate_elemental_of_beasts", land_unit = 	"wh3_dlc24_ksl_mon_incarnate_elemental_of_beasts" },
    { main_unit = "wh3_dlc24_ksl_mon_the_things_in_the_woods", land_unit = 	"wh3_dlc24_ksl_mon_the_things_in_the_woods" },
    { main_unit = "wh3_dlc24_lzd_mon_carnosaur_0", land_unit = 	"wh2_main_lzd_mon_carnosaur_0" },
    { main_unit = "wh3_dlc24_tze_inf_centigors_great_weapons", land_unit = 	"wh3_dlc24_tze_inf_centigors_great_weapons" },
    { main_unit = "wh3_dlc24_tze_inf_tzaangors", land_unit = 	"wh3_dlc24_tze_inf_tzaangors" },
    { main_unit = "wh3_dlc24_tze_mon_cockatrice", land_unit = 	"wh3_dlc24_tze_mon_cockatrice" },
    { main_unit = "wh3_dlc24_tze_mon_flamers_changebringers", land_unit = 	"wh3_dlc24_tze_mon_flamers_changebringers" },
    { main_unit = "wh3_dlc24_tze_mon_mutalith_vortex_beast", land_unit = 	"wh3_dlc24_tze_mon_mutalith_vortex_beast" },
    { main_unit = "wh3_main_chs_art_hellcannon_prologue", land_unit = 	"wh3_main_chs_art_hellcannon_prologue" },
    { main_unit = "wh3_main_cth_art_fire_rain_rocket_battery_0", land_unit = 	"wh3_main_cth_art_fire_rain_rocket_battery_0" },
    { main_unit = "wh3_main_cth_art_grand_cannon_0", land_unit = 	"wh3_main_cth_art_grand_cannon_0" },
    { main_unit = "wh3_main_cth_cav_jade_lancers_0", land_unit = 	"wh3_main_cth_cav_jade_lancers_0" },
    { main_unit = "wh3_main_cth_cav_jade_longma_riders_0", land_unit = 	"wh3_main_cth_cav_jade_longma_riders_0" },
    { main_unit = "wh3_main_cth_cav_peasant_horsemen_0", land_unit = 	"wh3_main_cth_cav_peasant_horsemen_0" },
    { main_unit = "wh3_main_cth_inf_crane_gunners_0", land_unit = 	"wh3_main_cth_inf_crane_gunners_0" },
    { main_unit = "wh3_main_cth_inf_dragon_guard_0", land_unit = 	"wh3_main_cth_inf_dragon_guard_0" },
    { main_unit = "wh3_main_cth_inf_dragon_guard_crossbowmen_0", land_unit = 	"wh3_main_cth_inf_dragon_guard_crossbowmen_0" },
    { main_unit = "wh3_main_cth_inf_iron_hail_gunners_0", land_unit = 	"wh3_main_cth_inf_iron_hail_gunners_0" },
    { main_unit = "wh3_main_cth_inf_jade_warrior_crossbowmen_0", land_unit = 	"wh3_main_cth_inf_jade_warrior_crossbowmen_0" },
    { main_unit = "wh3_main_cth_inf_jade_warrior_crossbowmen_1", land_unit = 	"wh3_main_cth_inf_jade_warrior_crossbowmen_1" },
    { main_unit = "wh3_main_cth_inf_jade_warriors_0", land_unit = 	"wh3_main_cth_inf_jade_warriors_0" },
    { main_unit = "wh3_main_cth_inf_jade_warriors_1", land_unit = 	"wh3_main_cth_inf_jade_warriors_1" },
    { main_unit = "wh3_main_cth_inf_peasant_archers_0", land_unit = 	"wh3_main_cth_inf_peasant_archers_0" },
    { main_unit = "wh3_main_cth_inf_peasant_spearmen_1", land_unit = 	"wh3_main_cth_inf_peasant_spearmen_1" },
    { main_unit = "wh3_main_cth_mon_terracotta_sentinel_0", land_unit = 	"wh3_main_cth_mon_terracotta_sentinel_0" },
    { main_unit = "wh3_main_cth_veh_sky_junk_0", land_unit = 	"wh3_main_cth_veh_sky_junk_0" },
    { main_unit = "wh3_main_cth_veh_sky_lantern_0", land_unit = 	"wh3_main_cth_veh_sky_lantern_0" },
    { main_unit = "wh3_main_cth_veh_war_compass_0", land_unit = 	"wh3_main_cth_veh_war_compass_0" },
    { main_unit = "wh3_main_dae_inf_chaos_furies_0", land_unit = 	"wh3_main_dae_inf_chaos_furies_0" },
    { main_unit = "wh3_main_kho_cav_bloodcrushers_0", land_unit = 	"wh3_main_kho_cav_bloodcrushers_0" },
    { main_unit = "wh3_main_kho_cav_gorebeast_chariot", land_unit = 	"wh3_main_kho_cav_gorebeast_chariot" },
    { main_unit = "wh3_main_kho_cav_skullcrushers_0", land_unit = 	"wh3_main_kho_cav_skullcrushers_0" },
    { main_unit = "wh3_main_kho_inf_bloodletters_0", land_unit = 	"wh3_main_kho_inf_bloodletters_0" },
    { main_unit = "wh3_main_kho_inf_bloodletters_1", land_unit = 	"wh3_main_kho_inf_bloodletters_1" },
    { main_unit = "wh3_main_kho_inf_chaos_furies_0", land_unit = 	"wh3_main_kho_inf_chaos_furies_0" },
    { main_unit = "wh3_main_kho_inf_chaos_warhounds_0", land_unit = 	"wh3_main_kho_inf_chaos_warhounds_0" },
    { main_unit = "wh3_main_kho_inf_chaos_warriors_0", land_unit = 	"wh3_main_kho_inf_chaos_warriors_0" },
    { main_unit = "wh3_main_kho_inf_chaos_warriors_1", land_unit = 	"wh3_main_kho_inf_chaos_warriors_1" },
    { main_unit = "wh3_main_kho_inf_chaos_warriors_2", land_unit = 	"wh3_main_kho_inf_chaos_warriors_2" },
    { main_unit = "wh3_main_kho_inf_flesh_hounds_of_khorne_0", land_unit = 	"wh3_main_kho_inf_flesh_hounds_of_khorne_0" },
    { main_unit = "wh3_main_kho_mon_bloodthirster_0", land_unit = 	"wh3_main_kho_mon_bloodthirster_0" },
    { main_unit = "wh3_main_kho_mon_khornataurs_0", land_unit = 	"wh3_main_kho_mon_khornataurs_0" },
    { main_unit = "wh3_main_kho_mon_khornataurs_1", land_unit = 	"wh3_main_kho_mon_khornataurs_1" },
    { main_unit = "wh3_main_kho_mon_soul_grinder_0", land_unit = 	"wh3_main_kho_mon_soul_grinder_0" },
    { main_unit = "wh3_main_kho_mon_spawn_of_khorne_0", land_unit = 	"wh3_main_kho_mon_spawn_of_khorne_0" },
    { main_unit = "wh3_main_kho_veh_blood_shrine_0", land_unit = 	"wh3_main_kho_veh_blood_shrine_0" },
    { main_unit = "wh3_main_kho_veh_skullcannon_0", land_unit = 	"wh3_main_kho_veh_skullcannon_0" },
    { main_unit = "wh3_main_ksl_cav_gryphon_legion_0", land_unit = 	"wh3_main_ksl_cav_gryphon_legion_0" },
    { main_unit = "wh3_main_ksl_cav_horse_archers_0", land_unit = 	"wh3_main_ksl_cav_horse_archers_0" },
    { main_unit = "wh3_main_ksl_cav_horse_raiders_0", land_unit = 	"wh3_main_ksl_cav_kossovite_dervishes_0" },
    { main_unit = "wh3_main_ksl_cav_war_bear_riders_1", land_unit = 	"wh3_main_ksl_cav_war_bear_riders_1" },
    { main_unit = "wh3_main_ksl_cav_winged_lancers_0", land_unit = 	"wh3_main_ksl_cav_winged_lancers_0" },
    { main_unit = "wh3_main_ksl_inf_armoured_kossars_0", land_unit = 	"wh3_main_ksl_inf_armoured_kossars_0" },
    { main_unit = "wh3_main_ksl_inf_armoured_kossars_1", land_unit = 	"wh3_main_ksl_inf_armoured_kossars_1" },
    { main_unit = "wh3_main_ksl_inf_ice_guard_0", land_unit = 	"wh3_main_ksl_inf_ice_guard_0" },
    { main_unit = "wh3_main_ksl_inf_ice_guard_1", land_unit = 	"wh3_main_ksl_inf_ice_guard_1" },
    { main_unit = "wh3_main_ksl_inf_kossars_0", land_unit = 	"wh3_main_ksl_inf_kossars_0" },
    { main_unit = "wh3_main_ksl_inf_kossars_1", land_unit = 	"wh3_main_ksl_inf_kossars_1" },
    { main_unit = "wh3_main_ksl_inf_kossars_tutorial_0", land_unit = 	"wh3_main_ksl_inf_kossars_tutorial_0" },
    { main_unit = "wh3_main_ksl_inf_kossars_tutorial_1", land_unit = 	"wh3_main_ksl_inf_kossars_tutorial_1" },
    { main_unit = "wh3_main_ksl_inf_streltsi_0", land_unit = 	"wh3_main_ksl_inf_streltsi_0" },
    { main_unit = "wh3_main_ksl_inf_tzar_guard_0", land_unit = 	"wh3_main_ksl_inf_tzar_guard_0" },
    { main_unit = "wh3_main_ksl_inf_tzar_guard_1", land_unit = 	"wh3_main_ksl_inf_tzar_guard_1" },
    { main_unit = "wh3_main_ksl_mon_elemental_bear_0", land_unit = 	"wh3_main_ksl_mon_elemental_bear_0" },
    { main_unit = "wh3_main_ksl_mon_snow_leopard_0", land_unit = 	"wh3_main_ksl_mon_snow_leopard_0" },
    { main_unit = "wh3_main_ksl_veh_heavy_war_sled_0", land_unit = 	"wh3_main_ksl_veh_heavy_war_sled_0" },
    { main_unit = "wh3_main_ksl_veh_light_war_sled_0", land_unit = 	"wh3_main_ksl_veh_light_war_sled_0" },
    { main_unit = "wh3_main_ksl_veh_little_grom_0", land_unit = 	"wh3_main_ksl_veh_little_grom_0" },
    { main_unit = "wh3_main_monster_feral_bears", land_unit = 	"wh3_main_monster_feral_bears" },
    { main_unit = "wh3_main_monster_feral_ice_bears", land_unit = 	"wh3_main_monster_feral_ice_bears" },
    { main_unit = "wh3_main_nur_cav_plague_drones_0", land_unit = 	"wh3_main_nur_cav_plague_drones_0" },
    { main_unit = "wh3_main_nur_cav_plague_drones_1", land_unit = 	"wh3_main_nur_cav_plague_drones_1" },
    { main_unit = "wh3_main_nur_cav_pox_riders_of_nurgle_0", land_unit = 	"wh3_main_nur_cav_pox_riders_of_nurgle_0" },
    { main_unit = "wh3_main_nur_inf_chaos_furies_0", land_unit = 	"wh3_main_nur_inf_chaos_furies_0" },
    { main_unit = "wh3_main_nur_inf_forsaken_0", land_unit = 	"wh3_main_nur_inf_forsaken_0" },
    { main_unit = "wh3_main_nur_inf_forsaken_0_warriors", land_unit = 	"wh3_main_nur_inf_forsaken_0" },
    { main_unit = "wh3_main_nur_inf_nurglings_0", land_unit = 	"wh3_main_nur_inf_nurglings_0" },
    { main_unit = "wh3_main_nur_inf_plaguebearers_0", land_unit = 	"wh3_main_nur_inf_plaguebearers_0" },
    { main_unit = "wh3_main_nur_inf_plaguebearers_1", land_unit = 	"wh3_main_nur_inf_plaguebearers_1" },
    { main_unit = "wh3_main_nur_mon_beast_of_nurgle_0", land_unit = 	"wh3_main_nur_mon_beast_of_nurgle_0" },
    { main_unit = "wh3_main_nur_mon_great_unclean_one_0", land_unit = 	"wh3_main_nur_mon_great_unclean_one_0" },
    { main_unit = "wh3_main_nur_mon_plague_toads_0", land_unit = 	"wh3_main_nur_mon_plague_toads_0" },
    { main_unit = "wh3_main_nur_mon_rot_flies_0", land_unit = 	"wh3_main_nur_mon_rot_flies_0" },
    { main_unit = "wh3_main_nur_mon_soul_grinder_0", land_unit = 	"wh3_main_nur_mon_soul_grinder_0" },
    { main_unit = "wh3_main_nur_mon_spawn_of_nurgle_0", land_unit = 	"wh3_main_nur_mon_spawn_of_nurgle_0" },
    { main_unit = "wh3_main_nur_mon_spawn_of_nurgle_0_warriors", land_unit = 	"wh3_main_nur_mon_spawn_of_nurgle_0" },
    { main_unit = "wh3_main_ogr_cav_crushers_0", land_unit = 	"wh3_main_ogr_cav_crushers_0" },
    { main_unit = "wh3_main_ogr_cav_crushers_1", land_unit = 	"wh3_main_ogr_cav_crushers_1" },
    { main_unit = "wh3_main_ogr_cav_mournfang_cavalry_0", land_unit = 	"wh3_main_ogr_cav_mournfang_cavalry_0" },
    { main_unit = "wh3_main_ogr_cav_mournfang_cavalry_1", land_unit = 	"wh3_main_ogr_cav_mournfang_cavalry_1" },
    { main_unit = "wh3_main_ogr_cav_mournfang_cavalry_2", land_unit = 	"wh3_main_ogr_cav_mournfang_cavalry_2" },
    { main_unit = "wh3_main_ogr_inf_gnoblars_0", land_unit = 	"wh3_main_ogr_inf_gnoblars_0" },
    { main_unit = "wh3_main_ogr_inf_gnoblars_1", land_unit = 	"wh3_main_ogr_inf_gnoblars_1" },
    { main_unit = "wh3_main_ogr_inf_ironguts_0", land_unit = 	"wh3_main_ogr_inf_ironguts_0" },
    { main_unit = "wh3_main_ogr_inf_leadbelchers_0", land_unit = 	"wh3_main_ogr_inf_leadbelchers_0" },
    { main_unit = "wh3_main_ogr_inf_maneaters_0", land_unit = 	"wh3_main_ogr_inf_maneaters_0" },
    { main_unit = "wh3_main_ogr_inf_maneaters_1", land_unit = 	"wh3_main_ogr_inf_maneaters_1" },
    { main_unit = "wh3_main_ogr_inf_maneaters_2", land_unit = 	"wh3_main_ogr_inf_maneaters_2" },
    { main_unit = "wh3_main_ogr_inf_maneaters_3", land_unit = 	"wh3_main_ogr_inf_maneaters_3" },
    { main_unit = "wh3_main_ogr_inf_ogres_0", land_unit = 	"wh3_main_ogr_inf_ogres_0" },
    { main_unit = "wh3_main_ogr_inf_ogres_1", land_unit = 	"wh3_main_ogr_inf_ogres_1" },
    { main_unit = "wh3_main_ogr_inf_ogres_2", land_unit = 	"wh3_main_ogr_inf_ogres_2" },
    { main_unit = "wh3_main_ogr_mon_giant_0", land_unit = 	"wh3_main_ogr_mon_giant_0" },
    { main_unit = "wh3_main_ogr_mon_gorgers_0", land_unit = 	"wh3_main_ogr_mon_gorgers_0" },
    { main_unit = "wh3_main_ogr_mon_sabretusk_pack_0", land_unit = 	"wh3_main_ogr_mon_sabretusk_pack_0" },
    { main_unit = "wh3_main_ogr_mon_stonehorn_0", land_unit = 	"wh3_main_ogr_mon_stonehorn_0" },
    { main_unit = "wh3_main_ogr_mon_stonehorn_1", land_unit = 	"wh3_main_ogr_mon_stonehorn_1" },
    { main_unit = "wh3_main_ogr_veh_gnoblar_scraplauncher_0", land_unit = 	"wh3_main_ogr_veh_gnoblar_scraplauncher_0" },
    { main_unit = "wh3_main_ogr_veh_ironblaster_0", land_unit = 	"wh3_main_ogr_veh_ironblaster_0" },
    { main_unit = "wh3_main_pro_kho_inf_bloodletters_0", land_unit = 	"wh3_main_pro_kho_inf_bloodletters_0" },
    { main_unit = "wh3_main_pro_kho_inf_chaos_furies_0", land_unit = 	"wh3_main_pro_kho_inf_chaos_furies_0" },
    { main_unit = "wh3_main_pro_kho_inf_chaos_warhounds_0", land_unit = 	"wh3_main_pro_kho_inf_chaos_warhounds_0" },
    { main_unit = "wh3_main_pro_kho_inf_chaos_warriors_0", land_unit = 	"wh3_main_pro_kho_inf_chaos_warriors_0" },
    { main_unit = "wh3_main_pro_kho_inf_flesh_hounds_of_khorne_0", land_unit = 	"wh3_main_pro_kho_inf_flesh_hounds_of_khorne_0" },
    { main_unit = "wh3_main_pro_kho_inf_flesh_hounds_of_khorne_simaergul_0", land_unit = 	"wh3_main_pro_kho_inf_flesh_hounds_of_khorne_simaergul_0" },
    { main_unit = "wh3_main_pro_ksl_cav_horse_raiders_0", land_unit = 	"wh3_main_pro_ksl_cav_kossovite_dervishes_0" },
    { main_unit = "wh3_main_pro_ksl_cav_war_bear_riders_1", land_unit = 	"wh3_main_pro_ksl_cav_war_bear_riders_1" },
    { main_unit = "wh3_main_pro_ksl_cav_winged_lancers_0", land_unit = 	"wh3_main_pro_ksl_cav_winged_lancers_0" },
    { main_unit = "wh3_main_pro_ksl_inf_armoured_kossars_0", land_unit = 	"wh3_main_pro_ksl_inf_armoured_kossars_0" },
    { main_unit = "wh3_main_pro_ksl_inf_armoured_kossars_1", land_unit = 	"wh3_main_pro_ksl_inf_armoured_kossars_1" },
    { main_unit = "wh3_main_pro_ksl_inf_kossars_0", land_unit = 	"wh3_main_pro_ksl_inf_kossars_0" },
    { main_unit = "wh3_main_pro_ksl_inf_kossars_1", land_unit = 	"wh3_main_pro_ksl_inf_kossars_1" },
    { main_unit = "wh3_main_pro_ksl_inf_streltsi_0", land_unit = 	"wh3_main_pro_ksl_inf_streltsi_0" },
    { main_unit = "wh3_main_pro_ksl_inf_tzar_guard_0", land_unit = 	"wh3_main_pro_ksl_inf_tzar_guard_0" },
    { main_unit = "wh3_main_pro_ksl_veh_little_grom_0", land_unit = 	"wh3_main_pro_ksl_veh_little_grom_0" },
    { main_unit = "wh3_main_pro_tze_cav_chaos_knights_0", land_unit = 	"wh3_main_pro_tze_cav_chaos_knights_0" },
    { main_unit = "wh3_main_pro_tze_inf_forsaken_0", land_unit = 	"wh3_main_tze_inf_forsaken_0" },
    { main_unit = "wh3_main_pro_tze_mon_flamers_0", land_unit = 	"wh3_main_pro_tze_mon_flamers_0" },
    { main_unit = "wh3_main_pro_tze_mon_screamers_0", land_unit = 	"wh3_main_pro_tze_mon_screamers_0" },
    { main_unit = "wh3_main_sla_cav_heartseekers_of_slaanesh_0", land_unit = 	"wh3_main_sla_cav_heartseekers_of_slaanesh_0" },
    { main_unit = "wh3_main_sla_cav_hellstriders_0", land_unit = 	"wh3_main_sla_cav_hellstriders_0" },
    { main_unit = "wh3_main_sla_cav_hellstriders_1", land_unit = 	"wh3_main_sla_cav_hellstriders_1" },
    { main_unit = "wh3_main_sla_cav_seekers_of_slaanesh_0", land_unit = 	"wh3_main_sla_cav_seekers_of_slaanesh_0" },
    { main_unit = "wh3_main_sla_inf_chaos_furies_0", land_unit = 	"wh3_main_sla_inf_chaos_furies_0" },
    { main_unit = "wh3_main_sla_inf_daemonette_0", land_unit = 	"wh3_main_sla_inf_daemonette_0" },
    { main_unit = "wh3_main_sla_inf_daemonette_1", land_unit = 	"wh3_main_sla_inf_daemonette_1" },
    { main_unit = "wh3_main_sla_inf_marauders_0", land_unit = 	"wh3_main_sla_inf_marauders_0" },
    { main_unit = "wh3_main_sla_inf_marauders_1", land_unit = 	"wh3_main_sla_inf_marauders_1" },
    { main_unit = "wh3_main_sla_inf_marauders_2", land_unit = 	"wh3_main_sla_inf_marauders_2" },
    { main_unit = "wh3_main_sla_mon_fiends_of_slaanesh_0", land_unit = 	"wh3_main_sla_mon_fiends_of_slaanesh_0" },
    { main_unit = "wh3_main_sla_mon_keeper_of_secrets_0", land_unit = 	"wh3_main_sla_mon_keeper_of_secrets_0" },
    { main_unit = "wh3_main_sla_mon_soul_grinder_0", land_unit = 	"wh3_main_sla_mon_soul_grinder_0" },
    { main_unit = "wh3_main_sla_mon_spawn_of_slaanesh_0", land_unit = 	"wh3_main_sla_mon_spawn_of_slaanesh_0" },
    { main_unit = "wh3_main_sla_veh_exalted_seeker_chariot_0", land_unit = 	"wh3_main_sla_veh_exalted_seeker_chariot_0" },
    { main_unit = "wh3_main_sla_veh_hellflayer_0", land_unit = 	"wh3_main_sla_veh_hellflayer_0" },
    { main_unit = "wh3_main_sla_veh_seeker_chariot_0", land_unit = 	"wh3_main_sla_veh_seeker_chariot_0" },
    { main_unit = "wh3_main_tze_cav_chaos_knights_0", land_unit = 	"wh3_main_tze_cav_chaos_knights_0" },
    { main_unit = "wh3_main_tze_cav_doom_knights_0", land_unit = 	"wh3_main_tze_cav_doom_knights_0" },
    { main_unit = "wh3_main_tze_inf_chaos_furies_0", land_unit = 	"wh3_main_tze_inf_chaos_furies_0" },
    { main_unit = "wh3_main_tze_inf_forsaken_0", land_unit = 	"wh3_main_tze_inf_forsaken_0" },
    { main_unit = "wh3_main_tze_mon_exalted_flamers_0", land_unit = 	"wh3_main_tze_mon_exalted_flamer_0" },
    { main_unit = "wh3_main_tze_mon_flamers_0", land_unit = 	"wh3_main_tze_mon_flamers_0" },
    { main_unit = "wh3_main_tze_mon_lord_of_change_0", land_unit = 	"wh3_main_tze_mon_lord_of_change_0" },
    { main_unit = "wh3_main_tze_mon_screamers_0", land_unit = 	"wh3_main_tze_mon_screamers_0" },
    { main_unit = "wh3_main_tze_mon_soul_grinder_0", land_unit = 	"wh3_main_tze_mon_soul_grinder_0" },
    { main_unit = "wh3_main_tze_mon_spawn_of_tzeentch_0", land_unit = 	"wh3_main_tze_mon_spawn_of_tzeentch_0" },
    { main_unit = "wh3_main_tze_veh_burning_chariot_0", land_unit = 	"wh3_main_tze_veh_burning_chariot_0" },
    { main_unit = "wh_dlc01_chs_cav_gorebeast_chariot", land_unit = 	"wh_dlc01_chs_cav_gorebeast_chariot" },
    { main_unit = "wh_dlc01_chs_inf_chaos_warriors_2", land_unit = 	"wh_dlc01_chs_inf_chaos_warriors_2" },
    { main_unit = "wh_dlc01_chs_inf_chosen_2", land_unit = 	"wh_dlc01_chs_inf_chosen_2" },
    { main_unit = "wh_dlc01_chs_inf_forsaken_0", land_unit = 	"wh_dlc01_chs_inf_forsaken_0" },
    { main_unit = "wh_dlc01_chs_mon_dragon_ogre", land_unit = 	"wh_dlc01_chs_mon_dragon_ogre" },
    { main_unit = "wh_dlc01_chs_mon_dragon_ogre_shaggoth", land_unit = 	"wh_dlc01_chs_mon_dragon_ogre_shaggoth" },
    { main_unit = "wh_dlc01_chs_mon_trolls_1", land_unit = 	"wh_dlc01_chs_mon_trolls_1" },
    { main_unit = "wh_dlc02_vmp_cav_blood_knights_0", land_unit = 	"wh_dlc02_vmp_cav_blood_knights_0" },
    { main_unit = "wh_dlc03_bst_cav_razorgor_chariot_0", land_unit = 	"wh_dlc03_bst_cav_razorgor_chariot_0" },
    { main_unit = "wh_dlc03_bst_feral_manticore", land_unit = 	"wh_dlc03_bst_feral_manticore" },
    { main_unit = "wh_dlc03_bst_inf_bestigor_herd_0", land_unit = 	"wh_dlc03_bst_inf_bestigor_herd_0" },
    { main_unit = "wh_dlc03_bst_inf_centigors_0", land_unit = 	"wh_dlc03_bst_inf_centigors_0" },
    { main_unit = "wh_dlc03_bst_inf_centigors_1", land_unit = 	"wh_dlc03_bst_inf_centigors_1" },
    { main_unit = "wh_dlc03_bst_inf_centigors_2", land_unit = 	"wh_dlc03_bst_inf_centigors_2" },
    { main_unit = "wh_dlc03_bst_inf_chaos_warhounds_0", land_unit = 	"wh_dlc03_bst_inf_chaos_warhounds_0" },
    { main_unit = "wh_dlc03_bst_inf_chaos_warhounds_1", land_unit = 	"wh_dlc03_bst_inf_chaos_warhounds_1" },
    { main_unit = "wh_dlc03_bst_inf_cygor_0", land_unit = 	"wh_dlc03_bst_inf_cygor_0" },
    { main_unit = "wh_dlc03_bst_inf_gor_herd_0", land_unit = 	"wh_dlc03_bst_inf_gor_herd_0" },
    { main_unit = "wh_dlc03_bst_inf_gor_herd_1", land_unit = 	"wh_dlc03_bst_inf_gor_herd_1" },
    { main_unit = "wh_dlc03_bst_inf_minotaurs_0", land_unit = 	"wh_dlc03_bst_inf_minotaurs_0" },
    { main_unit = "wh_dlc03_bst_inf_minotaurs_1", land_unit = 	"wh_dlc03_bst_inf_minotaurs_1" },
    { main_unit = "wh_dlc03_bst_inf_minotaurs_2", land_unit = 	"wh_dlc03_bst_inf_minotaurs_2" },
    { main_unit = "wh_dlc03_bst_inf_razorgor_herd_0", land_unit = 	"wh_dlc03_bst_inf_razorgor_herd_0" },
    { main_unit = "wh_dlc03_bst_inf_ungor_herd_1", land_unit = 	"wh_dlc03_bst_inf_ungor_herd_1" },
    { main_unit = "wh_dlc03_bst_inf_ungor_raiders_0", land_unit = 	"wh_dlc03_bst_inf_ungor_raiders_0" },
    { main_unit = "wh_dlc03_bst_inf_ungor_spearmen_0", land_unit = 	"wh_dlc03_bst_inf_ungor_spearmen_0" },
    { main_unit = "wh_dlc03_bst_inf_ungor_spearmen_1", land_unit = 	"wh_dlc03_bst_inf_ungor_spearmen_1" },
    { main_unit = "wh_dlc03_bst_mon_chaos_spawn_0", land_unit = 	"wh_dlc03_bst_mon_chaos_spawn_0" },
    { main_unit = "wh_dlc03_bst_mon_giant_0", land_unit = 	"wh_dlc03_bst_mon_giant_0" },
    { main_unit = "wh_dlc04_emp_cav_knights_blazing_sun_0", land_unit = 	"wh_dlc04_emp_cav_knights_blazing_sun_0" },
    { main_unit = "wh_dlc04_emp_inf_flagellants_0", land_unit = 	"wh_dlc04_emp_inf_flagellants_0" },
    { main_unit = "wh_dlc04_emp_inf_free_company_militia_0", land_unit = 	"wh_dlc04_emp_inf_free_company_militia_0" },
    { main_unit = "wh_dlc04_vmp_veh_corpse_cart_0", land_unit = 	"wh_dlc04_vmp_veh_corpse_cart_0" },
    { main_unit = "wh_dlc04_vmp_veh_corpse_cart_1", land_unit = 	"wh_dlc04_vmp_veh_corpse_cart_1" },
    { main_unit = "wh_dlc04_vmp_veh_corpse_cart_2", land_unit = 	"wh_dlc04_vmp_veh_corpse_cart_2" },
    { main_unit = "wh_dlc04_vmp_veh_mortis_engine_0", land_unit = 	"wh_dlc04_vmp_veh_mortis_engine_0" },
    { main_unit = "wh_dlc05_bst_mon_harpies_0", land_unit = 	"wh_dlc05_bst_mon_harpies_0" },
    { main_unit = "wh_dlc05_wef_cav_glade_riders_0", land_unit = 	"wh_dlc05_wef_cav_glade_riders_0" },
    { main_unit = "wh_dlc05_wef_cav_glade_riders_1", land_unit = 	"wh_dlc05_wef_cav_glade_riders_1" },
    { main_unit = "wh_dlc05_wef_cav_hawk_riders_0", land_unit = 	"wh_dlc05_wef_cav_hawk_riders_0" },
    { main_unit = "wh_dlc05_wef_cav_sisters_thorn_0", land_unit = 	"wh_dlc05_wef_cav_sisters_thorn_0" },
    { main_unit = "wh_dlc05_wef_cav_wild_riders_0", land_unit = 	"wh_dlc05_wef_cav_wild_riders_0" },
    { main_unit = "wh_dlc05_wef_cav_wild_riders_1", land_unit = 	"wh_dlc05_wef_cav_wild_riders_1" },
    { main_unit = "wh_dlc05_wef_forest_dragon_0", land_unit = 	"wh_dlc05_wef_forest_dragon_0" },
    { main_unit = "wh_dlc05_wef_inf_deepwood_scouts_0", land_unit = 	"wh_dlc05_wef_inf_deepwood_scouts_0" },
    { main_unit = "wh_dlc05_wef_inf_deepwood_scouts_1", land_unit = 	"wh_dlc05_wef_inf_deepwood_scouts_1" },
    { main_unit = "wh_dlc05_wef_inf_dryads_0", land_unit = 	"wh_dlc05_wef_inf_dryads_0" },
    { main_unit = "wh_dlc05_wef_inf_eternal_guard_0", land_unit = 	"wh_dlc05_wef_inf_eternal_guard_0" },
    { main_unit = "wh_dlc05_wef_inf_eternal_guard_1", land_unit = 	"wh_dlc05_wef_inf_eternal_guard_1" },
    { main_unit = "wh_dlc05_wef_inf_glade_guard_0", land_unit = 	"wh_dlc05_wef_inf_glade_guard_0" },
    { main_unit = "wh_dlc05_wef_inf_glade_guard_1", land_unit = 	"wh_dlc05_wef_inf_glade_guard_1" },
    { main_unit = "wh_dlc05_wef_inf_glade_guard_2", land_unit = 	"wh_dlc05_wef_inf_glade_guard_2" },
    { main_unit = "wh_dlc05_wef_inf_wardancers_0", land_unit = 	"wh_dlc05_wef_inf_wardancers_0" },
    { main_unit = "wh_dlc05_wef_inf_wardancers_1", land_unit = 	"wh_dlc05_wef_inf_wardancers_1" },
    { main_unit = "wh_dlc05_wef_inf_waywatchers_0", land_unit = 	"wh_dlc05_wef_inf_waywatchers_0" },
    { main_unit = "wh_dlc05_wef_inf_wildwood_rangers_0", land_unit = 	"wh_dlc05_wef_inf_wildwood_rangers_0" },
    { main_unit = "wh_dlc05_wef_mon_great_eagle_0", land_unit = 	"wh_dlc05_wef_mon_great_eagle_0" },
    { main_unit = "wh_dlc05_wef_mon_treekin_0", land_unit = 	"wh_dlc05_wef_mon_treekin_0" },
    { main_unit = "wh_dlc05_wef_mon_treeman_0", land_unit = 	"wh_dlc05_wef_mon_treeman_0" },
    { main_unit = "wh_dlc06_chs_cav_marauder_horsemasters_0", land_unit = 	"wh_dlc06_chs_cav_marauder_horsemasters_0" },
    { main_unit = "wh_dlc06_chs_feral_manticore", land_unit = 	"wh_dlc06_chs_feral_manticore" },
    { main_unit = "wh_dlc06_chs_inf_aspiring_champions_0", land_unit = 	"wh_dlc06_chs_inf_aspiring_champions_0" },
    { main_unit = "wh_dlc06_dwf_art_bolt_thrower_0", land_unit = 	"wh_dlc06_dwf_art_bolt_thrower_0" },
    { main_unit = "wh_dlc06_dwf_inf_bugmans_rangers_0", land_unit = 	"wh_dlc06_dwf_inf_bugmans_rangers_0" },
    { main_unit = "wh_dlc06_dwf_inf_rangers_0", land_unit = 	"wh_dlc06_dwf_inf_rangers_0" },
    { main_unit = "wh_dlc06_dwf_inf_rangers_1", land_unit = 	"wh_dlc06_dwf_inf_rangers_1" },
    { main_unit = "wh_dlc06_grn_cav_squig_hoppers_0", land_unit = 	"wh_dlc06_grn_cav_squig_hoppers_0" },
    { main_unit = "wh_dlc06_grn_inf_nasty_skulkers_0", land_unit = 	"wh_dlc06_grn_inf_nasty_skulkers_0" },
    { main_unit = "wh_dlc06_grn_inf_squig_explosive_0", land_unit = 	"wh_dlc06_grn_inf_squig_explosive_0" },
    { main_unit = "wh_dlc06_grn_inf_squig_herd_0", land_unit = 	"wh_dlc06_grn_inf_squig_herd_0" },
    { main_unit = "wh_dlc06_grn_mon_spider_hatchlings_0", land_unit = 	"wh_dlc06_grn_mon_spider_hatchlings_0" },
    { main_unit = "wh_dlc07_brt_cav_grail_guardians_0", land_unit = 	"wh_dlc07_brt_cav_grail_guardians_0" },
    { main_unit = "wh_dlc07_brt_cav_knights_errant_0", land_unit = 	"wh_dlc07_brt_cav_knights_errant_0" },
    { main_unit = "wh_dlc07_brt_cav_questing_knights_0", land_unit = 	"wh_dlc07_brt_cav_questing_knights_0" },
    { main_unit = "wh_dlc07_brt_cav_royal_hippogryph_knights_0", land_unit = 	"wh_dlc07_brt_cav_royal_hippogryph_knights_0" },
    { main_unit = "wh_dlc07_brt_cav_royal_pegasus_knights_0", land_unit = 	"wh_dlc07_brt_cav_royal_pegasus_knights_0" },
    { main_unit = "wh_dlc07_brt_inf_battle_pilgrims_0", land_unit = 	"wh_dlc07_brt_inf_battle_pilgrims_0" },
    { main_unit = "wh_dlc07_brt_inf_foot_squires_0", land_unit = 	"wh_dlc07_brt_inf_foot_squires_0" },
    { main_unit = "wh_dlc07_brt_inf_grail_reliquae_0", land_unit = 	"wh_dlc07_brt_inf_grail_reliquae_0" },
    { main_unit = "wh_dlc07_brt_inf_men_at_arms_1", land_unit = 	"wh_dlc07_brt_inf_men_at_arms_1" },
    { main_unit = "wh_dlc07_brt_inf_men_at_arms_2", land_unit = 	"wh_dlc07_brt_inf_men_at_arms_2" },
    { main_unit = "wh_dlc07_brt_inf_peasant_bowmen_1", land_unit = 	"wh_dlc07_brt_inf_peasant_bowmen_1" },
    { main_unit = "wh_dlc07_brt_inf_peasant_bowmen_2", land_unit = 	"wh_dlc07_brt_inf_peasant_bowmen_2" },
    { main_unit = "wh_dlc07_brt_inf_spearmen_at_arms_1", land_unit = 	"wh_dlc07_brt_inf_spearmen_at_arms_1" },
    { main_unit = "wh_dlc07_brt_peasant_mob_0", land_unit = 	"wh_dlc07_brt_inf_peasant_mob_0" },
    { main_unit = "wh_dlc08_nor_cav_marauder_horsemasters_0", land_unit = 	"wh_dlc08_nor_cav_marauder_horsemasters_0" },
    { main_unit = "wh_dlc08_nor_feral_manticore", land_unit = 	"wh_dlc08_nor_feral_manticore" },
    { main_unit = "wh_dlc08_nor_inf_marauder_berserkers_0", land_unit = 	"wh_dlc08_nor_inf_marauder_berserkers_0" },
    { main_unit = "wh_dlc08_nor_inf_marauder_champions_0", land_unit = 	"wh_dlc08_nor_inf_marauder_champions_0" },
    { main_unit = "wh_dlc08_nor_inf_marauder_champions_1", land_unit = 	"wh_dlc08_nor_inf_marauder_champions_1" },
    { main_unit = "wh_dlc08_nor_inf_marauder_hunters_0", land_unit = 	"wh_dlc08_nor_inf_marauder_hunters_0" },
    { main_unit = "wh_dlc08_nor_inf_marauder_hunters_1", land_unit = 	"wh_dlc08_nor_inf_marauder_hunters_1" },
    { main_unit = "wh_dlc08_nor_inf_marauder_spearman_0", land_unit = 	"wh_dlc08_nor_inf_marauder_spearman_0" },
    { main_unit = "wh_dlc08_nor_mon_fimir_0", land_unit = 	"wh_dlc08_nor_mon_fimir_0" },
    { main_unit = "wh_dlc08_nor_mon_fimir_1", land_unit = 	"wh_dlc08_nor_mon_fimir_1" },
    { main_unit = "wh_dlc08_nor_mon_frost_wyrm_0", land_unit = 	"wh_dlc08_nor_mon_frost_wyrm_0" },
    { main_unit = "wh_dlc08_nor_mon_norscan_giant_0", land_unit = 	"wh_dlc08_nor_mon_norscan_giant_0" },
    { main_unit = "wh_dlc08_nor_mon_norscan_ice_trolls_0", land_unit = 	"wh_dlc08_nor_mon_norscan_ice_trolls_0" },
    { main_unit = "wh_dlc08_nor_mon_skinwolves_0", land_unit = 	"wh_dlc08_nor_mon_skinwolves_0" },
    { main_unit = "wh_dlc08_nor_mon_skinwolves_1", land_unit = 	"wh_dlc08_nor_mon_skinwolves_1" },
    { main_unit = "wh_dlc08_nor_mon_war_mammoth_0", land_unit = 	"wh_dlc08_nor_mon_war_mammoth_0" },
    { main_unit = "wh_dlc08_nor_mon_war_mammoth_1", land_unit = 	"wh_dlc08_nor_mon_war_mammoth_1" },
    { main_unit = "wh_dlc08_nor_mon_war_mammoth_2", land_unit = 	"wh_dlc08_nor_mon_war_mammoth_2" },
    { main_unit = "wh_dlc08_nor_mon_warwolves_0", land_unit = 	"wh_dlc08_nor_mon_marauder_warwolves_0" },
    { main_unit = "wh_dlc08_nor_veh_marauder_warwolves_chariot_0", land_unit = 	"wh_dlc08_nor_cav_marauder_warwolves_chariot_0" },
    { main_unit = "wh_main_brt_art_field_trebuchet", land_unit = 	"wh_main_brt_art_field_trebuchet" },
    { main_unit = "wh_main_brt_cav_grail_knights", land_unit = 	"wh_main_brt_cav_grail_knights" },
    { main_unit = "wh_main_brt_cav_knights_of_the_realm", land_unit = 	"wh_main_brt_cav_knights_of_the_realm" },
    { main_unit = "wh_main_brt_cav_mounted_yeomen_0", land_unit = 	"wh_main_brt_cav_mounted_yeomen_0" },
    { main_unit = "wh_main_brt_cav_mounted_yeomen_1", land_unit = 	"wh_main_brt_cav_mounted_yeomen_1" },
    { main_unit = "wh_main_brt_cav_pegasus_knights", land_unit = 	"wh_main_brt_cav_pegasus_knights" },
    { main_unit = "wh_main_brt_inf_men_at_arms", land_unit = 	"wh_main_brt_inf_men_at_arms" },
    { main_unit = "wh_main_brt_inf_peasant_bowmen", land_unit = 	"wh_main_brt_inf_peasant_bowmen" },
    { main_unit = "wh_main_brt_inf_spearmen_at_arms", land_unit = 	"wh_main_brt_inf_spearmen_at_arms" },
    { main_unit = "wh_main_chs_art_hellcannon", land_unit = 	"wh_main_chs_art_hellcannon" },
    { main_unit = "wh_main_chs_cav_chaos_chariot", land_unit = 	"wh_main_chs_cav_chaos_chariot" },
    { main_unit = "wh_main_chs_cav_chaos_knights_0", land_unit = 	"wh_main_chs_cav_chaos_knights_0" },
    { main_unit = "wh_main_chs_cav_chaos_knights_1", land_unit = 	"wh_main_chs_cav_chaos_knights_1" },
    { main_unit = "wh_main_chs_cav_marauder_horsemen_0", land_unit = 	"wh_main_chs_cav_marauder_horsemen_0" },
    { main_unit = "wh_main_chs_cav_marauder_horsemen_1", land_unit = 	"wh_main_chs_cav_marauder_horsemen_1" },
    { main_unit = "wh_main_chs_inf_chaos_marauders_0", land_unit = 	"wh_main_chs_inf_chaos_marauders_0" },
    { main_unit = "wh_main_chs_inf_chaos_marauders_1", land_unit = 	"wh_main_chs_inf_chaos_marauders_1" },
    { main_unit = "wh_main_chs_inf_chaos_warriors_0", land_unit = 	"wh_main_chs_inf_chaos_warriors_0" },
    { main_unit = "wh_main_chs_inf_chaos_warriors_1", land_unit = 	"wh_main_chs_inf_chaos_warriors_1" },
    { main_unit = "wh_main_chs_inf_chosen_0", land_unit = 	"wh_main_chs_inf_chosen_0" },
    { main_unit = "wh_main_chs_inf_chosen_1", land_unit = 	"wh_main_chs_inf_chosen_1" },
    { main_unit = "wh_main_chs_mon_chaos_spawn", land_unit = 	"wh_main_chs_mon_chaos_spawn" },
    { main_unit = "wh_main_chs_mon_chaos_warhounds_0", land_unit = 	"wh_main_chs_mon_chaos_warhounds_0" },
    { main_unit = "wh_main_chs_mon_chaos_warhounds_1", land_unit = 	"wh_main_chs_mon_chaos_warhounds_1" },
    { main_unit = "wh_main_chs_mon_giant", land_unit = 	"wh_main_chs_mon_giant" },
    { main_unit = "wh_main_chs_mon_trolls", land_unit = 	"wh_main_chs_mon_trolls" },
    { main_unit = "wh_main_dwf_art_cannon", land_unit = 	"wh_main_dwf_art_cannon" },
    { main_unit = "wh_main_dwf_art_flame_cannon", land_unit = 	"wh_main_dwf_art_flame_cannon" },
    { main_unit = "wh_main_dwf_art_grudge_thrower", land_unit = 	"wh_main_dwf_art_grudge_thrower" },
    { main_unit = "wh_main_dwf_art_organ_gun", land_unit = 	"wh_main_dwf_art_organ_gun" },
    { main_unit = "wh_main_dwf_inf_dwarf_warrior_0", land_unit = 	"wh_main_dwf_inf_dwarf_warrior_0" },
    { main_unit = "wh_main_dwf_inf_dwarf_warrior_1", land_unit = 	"wh_main_dwf_inf_dwarf_warrior_1" },
    { main_unit = "wh_main_dwf_inf_hammerers", land_unit = 	"wh_main_dwf_inf_hammerers" },
    { main_unit = "wh_main_dwf_inf_ironbreakers", land_unit = 	"wh_main_dwf_inf_ironbreakers" },
    { main_unit = "wh_main_dwf_inf_irondrakes_0", land_unit = 	"wh_main_dwf_inf_irondrakes_0" },
    { main_unit = "wh_main_dwf_inf_irondrakes_2", land_unit = 	"wh_main_dwf_inf_irondrakes_2" },
    { main_unit = "wh_main_dwf_inf_longbeards", land_unit = 	"wh_main_dwf_inf_longbeards" },
    { main_unit = "wh_main_dwf_inf_longbeards_1", land_unit = 	"wh_main_dwf_inf_longbeards_1" },
    { main_unit = "wh_main_dwf_inf_miners_0", land_unit = 	"wh_main_dwf_inf_miners_0" },
    { main_unit = "wh_main_dwf_inf_miners_1", land_unit = 	"wh_main_dwf_inf_miners_1" },
    { main_unit = "wh_main_dwf_inf_quarrellers_0", land_unit = 	"wh_main_dwf_inf_quarrellers_0" },
    { main_unit = "wh_main_dwf_inf_quarrellers_1", land_unit = 	"wh_main_dwf_inf_quarrellers_1" },
    { main_unit = "wh_main_dwf_inf_slayers", land_unit = 	"wh_main_dwf_inf_slayers" },
    { main_unit = "wh_main_dwf_inf_thunderers_0", land_unit = 	"wh_main_dwf_inf_thunderers_0" },
    { main_unit = "wh_main_dwf_veh_gyrobomber", land_unit = 	"wh_main_dwf_veh_gyrobomber" },
    { main_unit = "wh_main_dwf_veh_gyrocopter_0", land_unit = 	"wh_main_dwf_veh_gyrocopter_0" },
    { main_unit = "wh_main_dwf_veh_gyrocopter_1", land_unit = 	"wh_main_dwf_veh_gyrocopter_1" },
    { main_unit = "wh_main_emp_art_great_cannon", land_unit = 	"wh_main_emp_art_great_cannon" },
    { main_unit = "wh_main_emp_art_helblaster_volley_gun", land_unit = 	"wh_main_emp_art_helblaster_volley_gun" },
    { main_unit = "wh_main_emp_art_helstorm_rocket_battery", land_unit = 	"wh_main_emp_art_helstorm_rocket_battery" },
    { main_unit = "wh_main_emp_art_mortar", land_unit = 	"wh_main_emp_art_mortar" },
    { main_unit = "wh_main_emp_cav_demigryph_knights_0", land_unit = 	"wh_main_emp_cav_demigryph_knights_0" },
    { main_unit = "wh_main_emp_cav_demigryph_knights_1", land_unit = 	"wh_main_emp_cav_demigryph_knights_1" },
    { main_unit = "wh_main_emp_cav_empire_knights", land_unit = 	"wh_main_emp_cav_empire_knights" },
    { main_unit = "wh_main_emp_cav_outriders_0", land_unit = 	"wh_main_emp_cav_outriders_0" },
    { main_unit = "wh_main_emp_cav_outriders_1", land_unit = 	"wh_main_emp_cav_outriders_1" },
    { main_unit = "wh_main_emp_cav_pistoliers_1", land_unit = 	"wh_main_emp_cav_pistoliers_1" },
    { main_unit = "wh_main_emp_cav_reiksguard", land_unit = 	"wh_main_emp_cav_reiksguard" },
    { main_unit = "wh_main_emp_inf_crossbowmen", land_unit = 	"wh_main_emp_inf_crossbowmen" },
    { main_unit = "wh_main_emp_inf_greatswords", land_unit = 	"wh_main_emp_inf_greatswords" },
    { main_unit = "wh_main_emp_inf_halberdiers", land_unit = 	"wh_main_emp_inf_halberdiers" },
    { main_unit = "wh_main_emp_inf_handgunners", land_unit = 	"wh_main_emp_inf_handgunners" },
    { main_unit = "wh_main_emp_inf_spearmen_0", land_unit = 	"wh_main_emp_inf_spearmen_0" },
    { main_unit = "wh_main_emp_inf_spearmen_1", land_unit = 	"wh_main_emp_inf_spearmen_1" },
    { main_unit = "wh_main_emp_inf_swordsmen", land_unit = 	"wh_main_emp_inf_swordsmen" },
    { main_unit = "wh_main_emp_veh_luminark_of_hysh_0", land_unit = 	"wh_main_emp_veh_luminark_of_hysh_0" },
    { main_unit = "wh_main_emp_veh_steam_tank", land_unit = 	"wh_main_emp_veh_steam_tank_driver" },
    { main_unit = "wh_main_grn_art_doom_diver_catapult", land_unit = 	"wh_main_grn_art_doom_diver_catapult" },
    { main_unit = "wh_main_grn_art_goblin_rock_lobber", land_unit = 	"wh_main_grn_art_goblin_rock_lobber" },
    { main_unit = "wh_main_grn_cav_forest_goblin_spider_riders_0", land_unit = 	"wh_main_grn_cav_forest_goblin_spider_riders_0" },
    { main_unit = "wh_main_grn_cav_forest_goblin_spider_riders_1", land_unit = 	"wh_main_grn_cav_forest_goblin_spider_riders_1" },
    { main_unit = "wh_main_grn_cav_goblin_wolf_chariot", land_unit = 	"wh_main_grn_cav_goblin_wolf_chariot" },
    { main_unit = "wh_main_grn_cav_goblin_wolf_riders_0", land_unit = 	"wh_main_grn_cav_goblin_wolf_riders_0" },
    { main_unit = "wh_main_grn_cav_goblin_wolf_riders_1", land_unit = 	"wh_main_grn_cav_goblin_wolf_riders_1" },
    { main_unit = "wh_main_grn_cav_orc_boar_boy_big_uns", land_unit = 	"wh_main_grn_cav_orc_boar_boy_big_uns" },
    { main_unit = "wh_main_grn_cav_orc_boar_boyz", land_unit = 	"wh_main_grn_cav_orc_boar_boyz" },
    { main_unit = "wh_main_grn_cav_orc_boar_chariot", land_unit = 	"wh_main_grn_cav_orc_boar_chariot" },
    { main_unit = "wh_main_grn_cav_savage_orc_boar_boy_big_uns", land_unit = 	"wh_main_grn_cav_savage_orc_boar_boy_big_uns" },
    { main_unit = "wh_main_grn_cav_savage_orc_boar_boyz", land_unit = 	"wh_main_grn_cav_savage_orc_boar_boyz" },
    { main_unit = "wh_main_grn_inf_black_orcs", land_unit = 	"wh_main_grn_inf_black_orcs" },
    { main_unit = "wh_main_grn_inf_goblin_archers", land_unit = 	"wh_main_grn_inf_goblin_archers" },
    { main_unit = "wh_main_grn_inf_goblin_spearmen", land_unit = 	"wh_main_grn_inf_goblin_spearmen" },
    { main_unit = "wh_main_grn_inf_night_goblin_archers", land_unit = 	"wh_main_grn_inf_night_goblin_archers" },
    { main_unit = "wh_main_grn_inf_night_goblin_fanatics", land_unit = 	"wh_main_grn_inf_night_goblin_fanatics" },
    { main_unit = "wh_main_grn_inf_night_goblin_fanatics_1", land_unit = 	"wh_main_grn_inf_night_goblin_fanatics_1" },
    { main_unit = "wh_main_grn_inf_night_goblins", land_unit = 	"wh_main_grn_inf_night_goblins" },
    { main_unit = "wh_main_grn_inf_orc_arrer_boyz", land_unit = 	"wh_main_grn_inf_orc_arrer_boyz" },
    { main_unit = "wh_main_grn_inf_orc_big_uns", land_unit = 	"wh_main_grn_inf_orc_big_uns" },
    { main_unit = "wh_main_grn_inf_orc_boyz", land_unit = 	"wh_main_grn_inf_orc_boyz" },
    { main_unit = "wh_main_grn_inf_savage_orc_arrer_boyz", land_unit = 	"wh_main_grn_inf_savage_orc_arrer_boyz" },
    { main_unit = "wh_main_grn_inf_savage_orc_big_uns", land_unit = 	"wh_main_grn_inf_savage_orc_big_uns" },
    { main_unit = "wh_main_grn_inf_savage_orcs", land_unit = 	"wh_main_grn_inf_savage_orcs" },
    { main_unit = "wh_main_grn_mon_arachnarok_spider_0", land_unit = 	"wh_main_grn_mon_arachnarok_spider_0" },
    { main_unit = "wh_main_grn_mon_giant", land_unit = 	"wh_main_grn_mon_giant" },
    { main_unit = "wh_main_grn_mon_trolls", land_unit = 	"wh_main_grn_mon_trolls" },
    { main_unit = "wh_main_nor_cav_chaos_chariot", land_unit = 	"wh_main_nor_cav_chaos_chariot" },
    { main_unit = "wh_main_nor_cav_marauder_horsemen_0", land_unit = 	"wh_main_nor_cav_marauder_horsemen_0" },
    { main_unit = "wh_main_nor_cav_marauder_horsemen_1", land_unit = 	"wh_main_nor_cav_marauder_horsemen_1" },
    { main_unit = "wh_main_nor_inf_chaos_marauders_0", land_unit = 	"wh_main_nor_inf_chaos_marauders_0" },
    { main_unit = "wh_main_nor_inf_chaos_marauders_1", land_unit = 	"wh_main_nor_inf_chaos_marauders_1" },
    { main_unit = "wh_main_nor_mon_chaos_trolls", land_unit = 	"wh_main_nor_mon_chaos_trolls" },
    { main_unit = "wh_main_nor_mon_chaos_warhounds_0", land_unit = 	"wh_main_nor_mon_chaos_warhounds_0" },
    { main_unit = "wh_main_nor_mon_chaos_warhounds_1", land_unit = 	"wh_main_nor_mon_chaos_warhounds_1" },
    { main_unit = "wh_main_vmp_cav_black_knights_0", land_unit = 	"wh_main_vmp_cav_black_knights_0" },
    { main_unit = "wh_main_vmp_cav_black_knights_3", land_unit = 	"wh_main_vmp_cav_black_knights_3" },
    { main_unit = "wh_main_vmp_cav_hexwraiths", land_unit = 	"wh_main_vmp_cav_hexwraiths" },
    { main_unit = "wh_main_vmp_inf_cairn_wraiths", land_unit = 	"wh_main_vmp_inf_cairn_wraiths" },
    { main_unit = "wh_main_vmp_inf_crypt_ghouls", land_unit = 	"wh_main_vmp_inf_crypt_ghouls" },
    { main_unit = "wh_main_vmp_inf_grave_guard_0", land_unit = 	"wh_main_vmp_inf_grave_guard_0" },
    { main_unit = "wh_main_vmp_inf_grave_guard_1", land_unit = 	"wh_main_vmp_inf_grave_guard_1" },
    { main_unit = "wh_main_vmp_inf_skeleton_warriors_0", land_unit = 	"wh_main_vmp_inf_skeleton_warriors_0" },
    { main_unit = "wh_main_vmp_inf_skeleton_warriors_1", land_unit = 	"wh_main_vmp_inf_skeleton_warriors_1" },
    { main_unit = "wh_main_vmp_inf_zombie", land_unit = 	"wh_main_vmp_inf_zombie" },
    { main_unit = "wh_main_vmp_mon_dire_wolves", land_unit = 	"wh_main_vmp_mon_dire_wolves" },
    { main_unit = "wh_main_vmp_mon_fell_bats", land_unit = 	"wh_main_vmp_mon_fell_bats" },
    { main_unit = "wh_main_vmp_mon_vargheists", land_unit = 	"wh_main_vmp_mon_vargheists" },
    { main_unit = "wh_main_vmp_mon_varghulf", land_unit = 	"wh_main_vmp_mon_varghulf" },
    { main_unit = "wh_main_vmp_veh_black_coach", land_unit = 	"wh_main_vmp_veh_black_coach" }
}

units_by_culture = {

}

for k, culture_key in pairs(culture_keys) do
    units_by_culture[cultures[k]] = {}
    print("\n"..cultures[k].." "..culture_key)
    for _, unit in pairs(units) do
        if string.find(unit.main_unit, culture_key) then
            table.insert(units_by_culture[cultures[k]], unit)
            print(unit.main_unit)
        end
    end

end

file = io.open("raise_dead.txt", "w")
io.output(file)
io.write("{\n")
for key, value in pairs(units_by_culture) do
    io.write(string.format("\t[\"%s\"] = {\n", key))
    for i, unit in ipairs(value) do
        io.write(string.format("\t\t\"%s\"", unit.main_unit))
        if i ~= #value then
            io.write(",")
        end
        io.write("\n")
    end
    io.write("\t},\n")
end
io.write("}")


-- local pr_units = {}

--  for key, unit in pairs(units) do
--     local pr_unit = {
--         unit_name_loc = "land_units_onscreen_name_"..unit.land_unit,
--         unit_uic = unit.main_unit.."_mercenary",
--         main_unit = unit.main_unit,
--         glory_cost = 1
--     }
--     table.insert(pr_units, pr_unit)
--  end

 
-- file = io.open("raise_dead.txt", "w")
-- io.output(file)
-- io.write("{\n")
-- for key, value in pairs(pr_units) do
--     io.write(string.format("\t{unit_name_loc = \"%s\", unit_uic = \"%s\", main_unit = \"%s\", glory_cost = 1},\n",value.unit_name_loc, value.unit_uic, value.main_unit))
-- end
-- io.write("}")

